### ISSUE TITLE
Consume from C

### ISSUE THREAD

**Issue by nothingalike** [Emurgo/cardano-serialization-lib#107]
I'm not a rust developer. I have only messed with rust in a hobby fashion.

I want the ability to consume the rust binary from a C based application. Since this library compiles using the `#[wasm_bindgen]`, can I just create bindings using `#[no_mangle]` and adding `extern "C"` to the method signatures. The intention is to use it with FFI

**Comment by v-almonacid** [comment]
You might be interested in taking a look at our [mobile wrappers](https://github.com/Emurgo/react-native-haskell-shelley/blob/master/rust/src/ios/linear_fee.rs). For iOS, we wrap all the methods with an `extern C` decorator (plus some additional logic to handle pointers) and then you can just use [cbindgen](https://github.com/eqrion/cbindgen) to generate C/C++ bindings.

I'm not sure if we can add this functionality here without involving some important refactoring (but if you think it's possible, we welcome contributions). Probably consuming the mobile bindings is the most straightforward solution, just keep in mind they don't cover everything we have here yet.

**Comment by nothingalike** [comment]
Ok that repo might have what I need. Thank you for the heads up
