### ISSUE TITLE
How to use `Address` instead of `ByronAddress` as witness

### ISSUE THREAD

**Issue by faustbrian** [Emurgo/cardano-serialization-lib#120]
I am currently looking at https://github.com/Emurgo/cardano-serialization-lib/blob/master/example/index.spec.ts#L75 and https://github.com/Emurgo/cardano-serialization-lib/blob/master/example/index.spec.ts#L104 and trying to use a Shelley address for the same process by using `Address.from_bech32` but the witness methods all expect an instance of `ByronAddress`.

Is support for Shelley addresses fully implemented and if so, what would be the process of using a Shelley address as a witness?

**Comment by SebastienGllmt** [comment]
Shelley addresses (usually `BaseAddress` witnesses are created using `make_vkey_witness` (https://github.com/Emurgo/cardano-serialization-lib/blob/15d193f097618e8dae5c03d5d711da9e08c4f706/rust/src/utils.rs#L530)

And yes, all of Shelley (and every other hardfork) is supported.

You can find example code here (but this example code hasn't been updated for Mary yet) https://github.com/Emurgo/cardano-serialization-lib/blob/59426b43d105e6cf4f05e4b5945c0cb3dc483130/doc/getting-started/generating-transactions.md#example-code

**Comment by faustbrian** [comment]
Thanks, that got me a bit further but the `CardanoWasm.PrivateKey.from_bech32` method doesn't seem to exist anymore which is used in `const prvKey = CardanoWasm.PrivateKey.from_bech32("ed25519e_sk16rl5fqqf4mg27syjzjrq8h3vq44jnnv52mvyzdttldszjj7a64xtmjwgjtfy25lu0xmv40306lj9pcqpa6slry9eh3mtlqvfjz93vuq0grl80");`. What has this been replaced with?

**Comment by CherryDT** [comment]
@faustbrian Why did you stike-through your text? What solution did you find? I still cannot find a method to convert the result of `privateKey.to_bech32()` back to a `PrivateKey`. The [generating transactions example](https://docs.cardano.org/projects/cardano-serialization-lib/en/latest/getting-started/generating-keys.html) also shows the use of `CardanoWasm.PrivateKey.from_bech32` which is undefined...

**Comment by faustbrian** [comment]
@CherryDT our solution is here https://github.com/ArkEcosystem/platform-sdk/blob/master/packages/platform-sdk-ada/src/services/transaction.ts#L26-L136

**Comment by CherryDT** [comment]
@faustbrian Thank you but I'm a bit lost, I see here only handling of derived keys. Can you point me to the exact place you are loading a string starting with `ed25519e_` into a `CardanoWasm.PrivateKey` object?

**Comment by v-almonacid** [comment]
@CherryDT there is no method to get a `PrivateKey` struct from a bech32 string, you will need the raw bytes and then you can use `from_extended_bytes()` or `from_normal_bytes()`, depending on how you generated that private key.
