### ISSUE TITLE
as_bytes() method returns empty Uint8Array

### ISSUE THREAD

**Issue by beardsleysmind** [Emurgo/cardano-serialization-lib#121]
Hi.
I'm using @emurgo/cardano-serialization-lib-nodejs package, v^6.0.0.

Code:
`const bip32PrivateKey = CardanoWasm.Bip32PrivateKey.from_bech32('my-private-key-to-witness-tx-in-bech32');`
`const bytesKey = bip32PrivateKey.to_raw_key().as_bytes();`

The problem is in one of my projects (require syntax, pure js) the part `bip32PrivateKey.to_raw_key().as_bytes()` behaves as expected giving me non empty Uint8Array.
But in my other project (import syntax, typescript) the same lines give me empty Uint8Array.

I tried to use require syntax and typescript in both and that didn't helped, so I'm out of ideas.
Do you have any idea why the same code behaves differently?

**Comment by SebastienGllmt** [comment]
Haven't investigated this, but I could imagine maybe the underlying memory being `free`'d is causing the issue

**Comment by beardsleysmind** [comment]
I found out that my problem occurs when I use cardano wasm lib AND nem-sdk lib (https://github.com/QuantumMechanics/NEM-sdk) in one project. Have no idea what's going on yet. So I'm not sure if it's the problem with cardano lib.
Anyway thank you for your time.

**Comment by beardsleysmind** [comment]
I found out that the problem is with nem-sdk lib. Sorry for the issue!
