### ISSUE TITLE
Signing Mary transaction

### ISSUE THREAD

**Issue by faustbrian** [Emurgo/cardano-serialization-lib#133]
I'm currently working on an ADA integration over at https://github.com/ArkEcosystem/platform-sdk/pull/1034 but always run into the issue `LedgerFailure (UtxowFailure (MissingVKeyWitnessesUTXOW (WitHashes (fromList [KeyHash \"09a9dd24b43ce6f22de361f2423e62a8a72a6ebb1e972a69ebb3bdcc\"]))))` when the transaction gets broadcasted which is a bit odd because the passphrase and/or private key used to sign the transaction are correct.

```ts
// This is the transaction builder that uses values from the genesis block of the configured network.
const txBuilder = CardanoWasm.TransactionBuilder.new(
	CardanoWasm.LinearFee.new(
		CardanoWasm.BigNum.from_str(minFeeA.toString()),
		CardanoWasm.BigNum.from_str(minFeeB.toString()),
	),
	CardanoWasm.BigNum.from_str(minUTxOValue.toString()),
	CardanoWasm.BigNum.from_str(poolDeposit.toString()),
	CardanoWasm.BigNum.from_str(keyDeposit.toString()),
);

// Get a `Bip32PrivateKey` instance and turn it into a `PrivateKey` instance
const rootKey = deriveRootKey(input.sign.mnemonic);
const accountKey = deriveAccountKey(rootKey, 0);
// const privateKey = accountKey.to_raw_key();
// console.log(
// 	"privateKey",
// 	Buffer.from(privateKey.as_bytes()).toString("hex"),
// 	"publicKey",
// 	Buffer.from(privateKey.to_public().as_bytes()).toString("hex"),
// );
// These are the inputs (UTXO) that will be consumed to satisfy the outputs. Any change will be transferred back to the sender
const utxos: UnspentTransaction[] = await this.listUnspentTransactions(input.from);

// for (let i = 0; i < utxos.length; i++) {
const i = 0;
const utxo: UnspentTransaction = utxos[i];

txBuilder.add_input(
	Address.from_bech32(utxo.address),
	CardanoWasm.TransactionInput.new(
		CardanoWasm.TransactionHash.from_bytes(Buffer.from(utxo.transaction.hash, "hex")),
		parseInt(utxo.index),
	),
	createValue(utxo.value),
);

console.log("utxo", utxo);
// break;
// }

// These are the outputs that will be transferred to other wallets. For now we only support a single output.
txBuilder.add_output(
	CardanoWasm.TransactionOutput.new(
		CardanoWasm.Address.from_bech32(input.data.to),
		createValue(input.data.amount),
	),
);

// This is the expiration slot which should be estimated with #estimateExpiration
txBuilder.set_ttl(input.data.expiration);

// calculate the min fee required and send any change to an address
txBuilder.add_change_if_needed(CardanoWasm.Address.from_bech32(input.from));

// once the transaction is ready, we build it to get the tx body without witnesses
const txBody = txBuilder.build();
const txHash = CardanoWasm.hash_transaction(txBody);
const witnesses = CardanoWasm.TransactionWitnessSet.new();

// add keyhash witnesses
const vkeyWitnesses = CardanoWasm.Vkeywitnesses.new();
vkeyWitnesses.add(
	CardanoWasm.make_vkey_witness(
		CardanoWasm.TransactionHash.from_bytes(Buffer.from(utxo.transaction.hash, "hex")),
		deriveSpendKey(accountKey, 0).to_raw_key(),
	),
);
vkeyWitnesses.add(
	CardanoWasm.make_vkey_witness(
		CardanoWasm.TransactionHash.from_bytes(Buffer.from(utxo.transaction.hash, "hex")),
		deriveChangeKey(accountKey, 0).to_raw_key(),
	),
);
// vkeyWitnesses.add(CardanoWasm.make_vkey_witness(txHash, deriveStakeKey(accountKey, 0).to_raw_key()));
// vkeyWitnesses.add(CardanoWasm.make_vkey_witness(txHash, deriveChangeKey(accountKey, 0).to_raw_key()));
vkeyWitnesses.add(CardanoWasm.make_vkey_witness(txHash, accountKey.to_raw_key()));
witnesses.set_vkeys(vkeyWitnesses);

console.log("hash", Buffer.from(txHash.to_bytes()).toString("hex"));
```

This issue pops up when attempting to broadcast a transaction on testnet, haven't tried mainnet yet. Are any values that are being used wrong like the keys that are required for signing? Tried multiple different scenarios and values and always end up with the same error when broadcasting the transaction.

**Comment by SebastienGllmt** [comment]
> CardanoWasm.TransactionHash.from_bytes(Buffer.from(utxo.transaction.hash, "hex"))

This is incorrect, You have to use the hash of the tx you're building, not the hash of the tx the utxo belongs to (aka use `txHash` instead like you have later in the code). Transactions will fail if you add witnesses that aren't required to avoid people dumping unnecessary witnesses onto the chain.

**Comment by faustbrian** [comment]
> > CardanoWasm.TransactionHash.from_bytes(Buffer.from(utxo.transaction.hash, "hex"))
> 
> This is incorrect, You have to use the hash of the tx you're building, not the hash of the tx the utxo belongs to (aka use `txHash` instead like you have later in the code). Transactions will fail if you add witnesses that aren't required to avoid people dumping unnecessary witnesses onto the chain.

Changed it back to what we had previously https://github.com/ArkEcosystem/platform-sdk/pull/1034/commits/1f04ce01259c823215cd195cc920ad117333d158. Currently we are using 3 values to sign, which of those would be required or allowed to be used before the transaction gets rejected?

> Also, are you sure the UTXO belongs to the account key and not an address generated from the account key?

We derive UTXO for a specific address like this https://github.com/ArkEcosystem/platform-sdk/blob/feat/broadcast-tx-graphql/packages/platform-sdk-ada/src/services/transaction.ts#L215-L238. Is there any way to retrieve UTXO directly for an account key or how should we retrieve UTXO to sign a new transaction?

**Comment by SebastienGllmt** [comment]
You're going to have to build a mapping of which derivation path corresponds to which address in the wallet that way you know which path to use to derive the key for the witness

> Is there any way to retrieve UTXO directly for an account key or how should we retrieve UTXO to sign a new transaction?
You can't get the UTXO by querying addresses. You have to get UTXOs by querying the payment credentials inside the transactions. I don't use cardano-graphql so I'm not sure the best way to do that kind of query

**Comment by faustbrian** [comment]
Thanks, will give the derivation path mapping a shot and see if we can get the transaction accepted.

**Comment by marianogoldman** [comment]
@SebastienGllmt. Before going for the calculation of the full mapping, we're trying to have at least one transaction accepted with all data controlled. So we're trying a specific address which has only one utxo, but we can't get it through, so not even sure how to build the mapping if we can't get this one right. Perhaps you can easily spot what's wrong...

In [this test](https://github.com/ArkEcosystem/platform-sdk/blob/a1850682b95714e360fd9a8dcd3ce3f6cee05220/packages/platform-sdk-ada/test/submit-tx.test.ts#L150-L178) we're trying to do the transfer. 

This is [the code](https://github.com/ArkEcosystem/platform-sdk/blob/a1850682b95714e360fd9a8dcd3ce3f6cee05220/packages/platform-sdk-ada/src/services/transaction.ts#L33) that creates and signs the transaction.

**Comment by SebastienGllmt** [comment]
https://github.com/ArkEcosystem/platform-sdk/blob/a1850682b95714e360fd9a8dcd3ce3f6cee05220/packages/platform-sdk-ada/src/services/identity/shelley.ts#L39

for `deriveSpendKey`, `deriveChangeKey` and `deriveStakeKey` these should NOT be hardened addresses (in the same way they are not hardened in BIP44). Only derivation paths up the account key are hardened.

**Comment by faustbrian** [comment]
Thanks! Overlooked that bit, working fine now.
