### ISSUE TITLE
Validate an Address using the Public Key

### ISSUE THREAD

**Issue by kzka90** [Emurgo/cardano-serialization-lib#135]
I'm working on a project that uses this library and I'm looking to verify if an `Address` belongs to a `Public Key`.

Is this possible with the library? Is this even possible with **Cardano**?

I could easily do this using the` Private Key`, but validation is being done on the _server-side_ and I don't want in any way to send the `Private Key` over the **Network** in any kind of way. 

So how could I know if a pair of `Address+Public Key` belong together.

**Comment by SebastienGllmt** [comment]
Just hash the public key and then check if any address has the public key hash as the payment credential (tools like cardano-db-sync provide a `payment_cred` field for this)
You can look at the address spec in Cardano (https://github.com/cardano-foundation/CIPs/pull/78) to see how to get the payment credential for an address if you're looking to match a specific address.

**Comment by kzka90** [comment]
> Just hash the public key and then check if any address has the public key hash as the payment credential (tools like cardano-db-sync provide a `payment_cred` field for this)
> You can look at the address spec in Cardano ([cardano-foundation/CIPs#78](https://github.com/cardano-foundation/CIPs/pull/78)) to see how to get the payment credential for an address if you're looking to match a specific address.

My problem is, this validation needs to happen as well on addresses that have not made a single payment yet on the blockchain. (Newly created addresses).

Already tried to match the `Public.hash()` with anything available from the `BaseAddress`, but no luck on finding a validation.
