### ISSUE TITLE
Error: Cannot find module '@emurgo/cardano-serialization-lib-asmjs'

### ISSUE THREAD

**Issue by CyberCyclone** [Emurgo/cardano-serialization-lib#136]
I'm trying to get the asmjs version to run as the WASM version isn't compatible with the framework I'm using (MeteorJS). I've installed ```@emurgo/cardano-serialization-lib-asmjs``` as you normally do ```npm install --save @emurgo/cardano-serialization-lib-asmjs```

<img width="433" alt="image" src="https://user-images.githubusercontent.com/4373888/113708397-83c0ce80-9724-11eb-8a71-691452b19a44.png">

When I run it though it comes back as:

```
Error: Cannot find module '@emurgo/cardano-serialization-lib-asmjs'
```

In the description, it says ```Browser (pure JS - no WASM) ASM.js package```. Being an NPM module I would have expected this to still be compatible with NodeJS (server side) and not just limited to the browser.

I just wanted to double check that @emurgo/cardano-serialization-lib-asmjs can run from NodeJS and there's no special setup require?

**Comment by SebastienGllmt** [comment]
Does the latest build (6.1.0) work for you?

**Comment by lisicky** [comment]
outdated
