### ISSUE TITLE
Question - how to sign the transactions

### ISSUE THREAD

**Issue by laplasz** [Emurgo/cardano-serialization-lib#138]
Hi!

Just would like to get some help - is it possible to use this lib for signing transactions?
I saw example about transaction build.

Thanks in advance!

**Comment by SebastienGllmt** [comment]
Yes, you can create witnesses (signatures) and then add them to the transaction. Notably `make_daedalus_bootstrap_witness`, `make_icarus_bootstrap_witness` and `make_vkey_witness` generate signatures.

**Comment by laplasz** [comment]
THanks @SebastienGllmt 
So what I would like to do is to sign the transaction and get tx.signed - I will try to use `make_daedalus_bootstrap_witness`
