### ISSUE TITLE
Add support to calculate Minimum UTxO

### ISSUE THREAD

**Issue by kzka90** [Emurgo/cardano-serialization-lib#139]
I'm 1-month old in Cardano, but since the introduction of multi-assets I've noticed that the calculation of Minimum UTxO got a little complex. (Correct me if I'm wrong)

I found this doc explanation on how to calculate the Minimum ADA:
[https://github.com/input-output-hk/cardano-ledger-specs/blob/master/doc/explanations/min-utxo.rst](https://github.com/input-output-hk/cardano-ledger-specs/blob/master/doc/explanations/min-utxo.rst)

After checking the Doc, I think it'll be very helpful to have a function to calculate the Minimum ADA of a UTxO with X-Amount of Y-types of assets.

Or maybe there's already an easy way of directly calculating it and I haven't noticed it? 😅

**Comment by SebastienGllmt** [comment]
We have this function called `min_ada_required`. Often times it's easiest to look through the type definitions for our library to see what is available: https://github.com/Emurgo/cardano-serialization-lib/blob/master/rust/pkg/cardano_serialization_lib.js.flow

**Comment by kzka90** [comment]
Oh, my bad. And I even triple-read it. Thank you.

One question about this @SebastienGllmt :

What would happen if for some reason I miscalculate this minimum_ada_required. Would it burn the tokens or just invalidate the transaction?

**Comment by SebastienGllmt** [comment]
If you try and send less than `minimum_ada_required` to a UTXO entry the transaction will simply fail.
