### ISSUE TITLE
Building Ipv4 returns other values than introduced

### ISSUE THREAD

**Issue by jvieiro** [Emurgo/cardano-serialization-lib#145]
When running this code I expect that the second log shows me `127.0.0.1` as I inserted it at the first line. Instead of this, it shows me `127.` 
```
const ipv4 = CardanoWasm.Ipv4.new(Buffer.from("127.0.0.1", "utf-8"));
console.log(Buffer.from(ipv4.to_bytes()).toString("hex"));
const [decoded] = decodeAllSync(ipv4.to_bytes());
console.log(decoded.toString("utf-8"));
```

Also, I decoded the first log value on [cbor.me](http://cbor.me/) and returned `127.` too

**Comment by v-almonacid** [comment]
Unfortunately the JS API is not very descriptive, and sometimes it's better to look in the rust source code to get a more precise idea about the expected data types. In this case, `Ipv4` is actually

```
pub struct Ipv4([u8; 4]);
```

So it expects an array of 4 bytes, as a regular IP is actually defined at the low level.

You should probably try something like:

```js
const bytes = [127, 0, 0, 1];
const ipv4 = Ipv4.new(Buffer.from(bytes));
```

**Comment by enzoc4** [comment]
I just took a quick glance, so I may be missing something, but I think [this line](https://github.com/Emurgo/cardano-serialization-lib/blob/59fab61dd225ec64ca2b258f938ce546cf69bf3c/rust/src/lib.rs#L863) should probably be `data` instead of `data[..4]`.

Otherwise it will never return the wrong length error (and may even panic if the input is shorter).

**Comment by jvieiro** [comment]
> Unfortunately the JS API is not very descriptive, and sometimes it's better to look in the rust source code to get a more precise idea about the expected data types. In this case, `Ipv4` is actually
> 
> ```
> pub struct Ipv4([u8; 4]);
> ```
> 
> So it expects an array of 4 bytes, as a regular IP is actually defined at the low level.
> 
> You should probably try something like:
> 
> ```js
> const bytes = [127, 0, 0, 1];
> const ipv4 = Ipv4.new(Buffer.from(bytes));
> ```

It worked for me, thanks!
