### ISSUE TITLE
Fee calculation does not take metadata into account

### ISSUE THREAD

**Issue by Flavien** [Emurgo/cardano-serialization-lib#155]
I'm building transactions using the transaction builder and I am using `add_change_if_needed` to get the optimal fees calculation. However, if I add metadata to the transaction, submitting it fails with 

> transaction submit error ShelleyTxValidationError ShelleyBasedEraMary (ApplyTxError [LedgerFailure (UtxowFailure (UtxoFailure (FeeTooSmallUTxO (Coin xxx) (Coin xxx)))),LedgerFailure (UtxowFailure (MissingTxBodyMetadataHash (AuxiliaryDataHash {unsafeAuxiliaryDataHash = SafeHash "xxx"})))])

As far as I can tell, this is because the fees calculation doesn't take metadata into account.

**Comment by SebastienGllmt** [comment]
I don't think this is the root cause because we send transactions with metadata in Yoroi and they all get accepted just fine. Did you make sure to call `set_metadata` on the tx builder before  `add_change_if_needed`?

**Comment by Flavien** [comment]
Yes you're right, I wasn't calling `set_metadata` and calling it resolves the problem. Thanks!
