### ISSUE TITLE
FeeTooSmallUTxO when multiple assets are used in a UTXO

### ISSUE THREAD

**Issue by leobel** [Emurgo/cardano-serialization-lib#163]
Hi, I'm getting the min fee for a tx that will mint a token but sometimes the functions return a fee too small. This is the function:

    /**
     * @param {Transaction} tx
     * @param {LinearFee} linear_fee
     * @returns {BigNum}
     */
    declare export function min_fee(tx: Transaction, linear_fee: LinearFee): BigNum;

My code takes a structure coming from the cardano-wallet (`coinSelection`) and builds a tx using `TxBuilder`, then I set the mint object using `set_mint`, then sign it and get the fee with `min_fee`.

 To get the min fee I call `set_mint` this way:
 
    min_fee(tx, LinearFee.new(BigNum.from_str("44"), BigNum.from_str("155381")));

This is how I'm constructing the TransactionBody from the coinSelection:

    buildTransaction(coinSelection: CoinSelectionWallet, ttl: number, data?: TransactionMetadata, startSlot = 0, config = Config.Mainnet): TransactionBody {
		    const protocolParams = config.protocolParams;
		    let txBuilder = TransactionBuilder.new(
			    // all of these are taken from the mainnet genesis settings
			    // linear fee parameters (a*size + b)
			    LinearFee.new(BigNum.from_str("44"), BigNum.from_str("155381")),
			    // minimum utxo value
			    BigNum.from_str("1000000"),
			    // pool deposit
			    BigNum.from_str("500000000"),
			    // key deposit
			    BigNum.from_str("2000000")
		    );
    
		    // add tx inputs
		    coinSelection.inputs.forEach((input, i) => {
			    let address = Address.from_bech32(input.address);
			    let txInput = TransactionInput.new(
				    TransactionHash.from_bytes(Buffer.from(input.id, 'hex')),
				    input.index
			    );
			    let amount = Value.new(
				    BigNum.from_str(input.amount.quantity.toString())
			    );
			    txBuilder.add_input(address, txInput, amount);
		    });
    
		    // add tx outputs
		    coinSelection.outputs.forEach(output => {
			    let address = Address.from_bech32(output.address);
			    let amount = Value.new(
				    BigNum.from_str(output.amount.quantity.toString())
			    );
    
			    // add tx assets
			    if(output.assets && output.assets.length > 0){
				    let multiAsset = Seed.buildMultiAssets(output.assets);
				    amount.set_multiasset(multiAsset);
			    }
    
			    let txOutput = TransactionOutput.new(
				    address,
				    amount
			    );
			    txBuilder.add_output(txOutput);
		    });
    
		    // add tx change
		    coinSelection.change.forEach(change => {
			    let address = Address.from_bech32(change.address);
			    let amount = Value.new(
				    BigNum.from_str(change.amount.quantity.toString())
			    );
    
			    // add tx assets
			    if(change.assets && change.assets.length > 0){
				    let multiAsset = Seed.buildMultiAssets(change.assets);
				    amount.set_multiasset(multiAsset);
			    }
    
			    let txOutput = TransactionOutput.new(
				    address,
				    amount
			    );
			    txBuilder.add_output(txOutput);
		    });
    
		    // add tx metadata
		    if (data) {
			    txBuilder.set_metadata(data);
		    }
    
		    // set tx validity start interval
		    txBuilder.set_validity_start_interval(startSlot);
    
		    // set tx ttl
		    txBuilder.set_ttl(ttl);
    
		    // calculate fee
		    let fee = coinSelection.inputs.reduce((acc, c) => c.amount.quantity + acc, 0) 
		    - coinSelection.outputs.reduce((acc, c) => c.amount.quantity + acc, 0) 
		    - coinSelection.change.reduce((acc, c) => c.amount.quantity + acc, 0);
		    
		    // set tx fee
		    txBuilder.set_fee(BigNum.from_str(fee.toString()));
    
		    let txBody = txBuilder.build();
		    return txBody;
	    }
 
This is `Seed.buildMultiAssets()`:

	static buildMultiAssets(assets: WalletsAssetsAvailable[]): MultiAsset {
		let multiAsset = MultiAsset.new();
		assets.forEach(a => {
				let asset = Assets.new();
				let scriptHash = Seed.getScriptHashFromPolicy(a.policy_id);
				asset.insert(AssetName.new(Buffer.from(a.asset_name, 'hex')), BigNum.from_str(a.quantity.toString()));
				multiAsset.insert(scriptHash, asset);
		});
		return multiAsset;
	}
 
Here the code to create the `Mint` object:

	static buildTransactionMint(tokens: TokenWallet[]): Mint {
		let mint = Mint.new();
		tokens.forEach(t => {
			let mintAssets = MintAssets.new();
			let scriptHash = Seed.getScriptHashFromPolicy(t.asset.policy_id);
			mintAssets.insert(AssetName.new(Buffer.from(t.asset.asset_name)), Int.new_i32(t.asset.quantity));
			mint.insert(scriptHash, mintAssets);
		});

		return mint;
	}

After the `TransactionBody` is built I set the mint object this way:

    let txBody = buildTransaction(coinSelection, ttl, metadata); // metadata is of type `TransactionMetadata`
    txBody.set_mint(mint);

After that I sign the tx with `txBody` the `signingKeys`, `metadata` and the `scripts  // are of type NativeScripts[]`. 
To finally get the min fee using `min_fee`.

The thing is I'm not sure when specifically the issue shows up (it works sometimes) but there are some cases that could be a starting point. For example, the min_fee is wrong when I have 3 assets in one UTXO plus metadata like this:

    {
      inputs: [
        {
          amount: {
            quantity: 1444443,
            unit: "lovelace",
          },
          address: "addr1qyuxc75xmzzy7sy955pyz4tqg0ycgttjcv2u39ay929q2yp59kkfl90wf7f9vlm99fek6e9l5zh65td8jhw63hn9skqqya2xl3",
          id: "ef4911bd3ac3f45ad69a21b933a5c7cb9470cb77661f41f50e07476eb87c1b2a",
          derivation_path: [
            "1852H",
            "1815H",
            "0H",
            "0",
            "0",
          ],
          assets: [
            {
              asset_name: "54616e676f32",
              quantity: 1000000,
              policy_id: "a716bcf749e3afc27674da23c15fb24a63435f837760dcc823bca995",
            },
          ],
          index: 0,
        },
        {
          amount: {
            quantity: 1444443,
            unit: "lovelace",
          },
          address: "addr1qyuxc75xmzzy7sy955pyz4tqg0ycgttjcv2u39ay929q2yp59kkfl90wf7f9vlm99fek6e9l5zh65td8jhw63hn9skqqya2xl3",
          id: "b9f927b44c0905697c1767d77f6ceb798091d6a854c3f04543e23c688277ff01",
          derivation_path: [
            "1852H",
            "1815H",
            "0H",
            "0",
            "0",
          ],
          assets: [
            {
              asset_name: "54616e676f35",
              quantity: 1000000,
              policy_id: "19933db2e7c74625ab0a4174bab9a27170f97555634082c2f16d3bea",
            },
          ],
          index: 0,
        },
        {
          amount: {
            quantity: 1444443,
            unit: "lovelace",
          },
          address: "addr1qyuxc75xmzzy7sy955pyz4tqg0ycgttjcv2u39ay929q2yp59kkfl90wf7f9vlm99fek6e9l5zh65td8jhw63hn9skqqya2xl3",
          id: "4b5efe05d035d510bac0fa9dd84db70912c13a95efd97e2fdd9afb362438dc0a",
          derivation_path: [
            "1852H",
            "1815H",
            "0H",
            "0",
            "0",
          ],
          assets: [
            {
              asset_name: "54616e676f33",
              quantity: 1000000,
              policy_id: "fcd84d1acc1ad2780f0a231779ea5d9da20826c3c13c7a3dda6efa5a",
            },
          ],
          index: 0,
        },
      ],
      outputs: [
        {
          amount: {
            quantity: 1444443,
            unit: "lovelace",
          },
          address: "addr1qyuxc75xmzzy7sy955pyz4tqg0ycgttjcv2u39ay929q2yp59kkfl90wf7f9vlm99fek6e9l5zh65td8jhw63hn9skqqya2xl3",
          assets: [
            {
              policy_id: "7e634c9d8edfd106326767cf58fdf6666a2db4f3179cadb2b9054122",
              asset_name: "54616e676f",
              quantity: 1000000,
            },
          ],
        },
      ],
      change: [
        {
          amount: {
            quantity: 2696486,
            unit: "lovelace",
          },
          address: "addr1qxqlyjyrqcgar3xx8ayyhxphkmnqnt2w524hwg8y555vtkf59kkfl90wf7f9vlm99fek6e9l5zh65td8jhw63hn9skqqhxnp7w",
          derivation_path: [
            "1852H",
            "1815H",
            "0H",
            "1",
            "7",
          ],
          assets: [
            {
              asset_name: "54616e676f35",
              quantity: 1000000,
              policy_id: "19933db2e7c74625ab0a4174bab9a27170f97555634082c2f16d3bea",
            },
            {
              asset_name: "54616e676f32",
              quantity: 1000000,
              policy_id: "a716bcf749e3afc27674da23c15fb24a63435f837760dcc823bca995",
            },
            {
              asset_name: "54616e676f33",
              quantity: 1000000,
              policy_id: "fcd84d1acc1ad2780f0a231779ea5d9da20826c3c13c7a3dda6efa5a",
            },
          ],
        },
      ],
      withdrawals: [
      ],
      certificates: undefined,
      deposits: [
      ],
      metadata: "oQCheDg3ZTYzNGM5ZDhlZGZkMTA2MzI2NzY3Y2Y1OGZkZjY2NjZhMmRiNGYzMTc5Y2FkYjJiOTA1NDEyMqFlVGFuZ2+laWFyd2VhdmVJZGphcndlYXZlLWlkZmlwZnNJZGdpcGZzLWlkZG5hbWVlVGFuZ29rZGVzY3JpcHRpb25xVGFuZ28gY3J5cHRvIGNvaW5kdHlwZWRDb2lu",
    }
In this case, the error is this (`min_fee` returns 204177):

    HardForkApplyTxErrFromEra S (S (S (Z (WrapApplyTxErr {unwrapApplyTxErr = ApplyTxError [LedgerFailure (UtxowFailure (UtxoFailure (FeeTooSmallUTxO (Coin 210900) (Coin 204177))))]})))).

If no metadata is present the tx for 3 assets in one UTXO just works but when the assets are 5 the error happens again:

    {
      inputs: [
        {
          amount: {
            quantity: 2692805,
            unit: "lovelace",
          },
          address: "addr1qxuq6szwm8gdmxzvv7c0r2sgkyva69tmh2h8dseyg8uzdv359kkfl90wf7f9vlm99fek6e9l5zh65td8jhw63hn9skqqvjjcev",
          id: "ffc81613c24bb158858fdf4008934a6917b2772206603f9cb617432a1719f446",
          derivation_path: [
            "1852H",
            "1815H",
            "0H",
            "1",
            "9",
          ],
          assets: [
            {
              asset_name: "54616e676f32",
              quantity: 1000000,
              policy_id: "9a8565c9bd0fcf3add4fdd08956e40e1607a762b92f17dfaab2dfec5",
            },
            {
              asset_name: "54616e676f34",
              quantity: 1000000,
              policy_id: "a1c81493ce562eba9a5c6c6ed3e6a0514d9d1196afd5677d43c655e5",
            },
            {
              asset_name: "54616e676f33",
              quantity: 1000000,
              policy_id: "fcd84d1acc1ad2780f0a231779ea5d9da20826c3c13c7a3dda6efa5a",
            },
          ],
          index: 1,
        },
        {
          amount: {
            quantity: 1444443,
            unit: "lovelace",
          },
          address: "addr1qyuxc75xmzzy7sy955pyz4tqg0ycgttjcv2u39ay929q2yp59kkfl90wf7f9vlm99fek6e9l5zh65td8jhw63hn9skqqya2xl3",
          id: "ffc81613c24bb158858fdf4008934a6917b2772206603f9cb617432a1719f446",
          derivation_path: [
            "1852H",
            "1815H",
            "0H",
            "0",
            "0",
          ],
          assets: [
            {
              asset_name: "54616e676f33",
              quantity: 1000000,
              policy_id: "472b254819d86a3393726eb118b1ba860dd04fa630810b38c2e553fc",
            },
          ],
          index: 0,
        },
        {
          amount: {
            quantity: 1444443,
            unit: "lovelace",
          },
          address: "addr1qyuxc75xmzzy7sy955pyz4tqg0ycgttjcv2u39ay929q2yp59kkfl90wf7f9vlm99fek6e9l5zh65td8jhw63hn9skqqya2xl3",
          id: "b9f927b44c0905697c1767d77f6ceb798091d6a854c3f04543e23c688277ff01",
          derivation_path: [
            "1852H",
            "1815H",
            "0H",
            "0",
            "0",
          ],
          assets: [
            {
              asset_name: "54616e676f35",
              quantity: 1000000,
              policy_id: "19933db2e7c74625ab0a4174bab9a27170f97555634082c2f16d3bea",
            },
          ],
          index: 0,
        },
      ],
      outputs: [
        {
          amount: {
            quantity: 1444443,
            unit: "lovelace",
          },
          address: "addr1qyuxc75xmzzy7sy955pyz4tqg0ycgttjcv2u39ay929q2yp59kkfl90wf7f9vlm99fek6e9l5zh65td8jhw63hn9skqqya2xl3",
          assets: [
            {
              policy_id: "001ff1c3d7cc7083d2d569748ad941910246a58e460287f708f3c137",
              asset_name: "54616e676f34",
              quantity: 1000000,
            },
          ],
        },
      ],
      change: [
        {
          amount: {
            quantity: 3937119,
            unit: "lovelace",
          },
          address: "addr1q87p0ml3mj8xaxjrmcr7dgulkg7ylt0cgkh5l0l0twr2p6359kkfl90wf7f9vlm99fek6e9l5zh65td8jhw63hn9skqqu5wdxs",
          derivation_path: [
            "1852H",
            "1815H",
            "0H",
            "1",
            "10",
          ],
          assets: [
            {
              asset_name: "54616e676f35",
              quantity: 1000000,
              policy_id: "19933db2e7c74625ab0a4174bab9a27170f97555634082c2f16d3bea",
            },
            {
              asset_name: "54616e676f33",
              quantity: 1000000,
              policy_id: "472b254819d86a3393726eb118b1ba860dd04fa630810b38c2e553fc",
            },
            {
              asset_name: "54616e676f32",
              quantity: 1000000,
              policy_id: "9a8565c9bd0fcf3add4fdd08956e40e1607a762b92f17dfaab2dfec5",
            },
            {
              asset_name: "54616e676f34",
              quantity: 1000000,
              policy_id: "a1c81493ce562eba9a5c6c6ed3e6a0514d9d1196afd5677d43c655e5",
            },
            {
              asset_name: "54616e676f33",
              quantity: 1000000,
              policy_id: "fcd84d1acc1ad2780f0a231779ea5d9da20826c3c13c7a3dda6efa5a",
            },
          ],
        },
      ],
      withdrawals: [
      ],
      certificates: undefined,
      deposits: [
      ],
      metadata: undefined,
    }
This is the error (`min_fee` returns 200129):

    HardForkApplyTxErrFromEra S (S (S (Z (WrapApplyTxErr {unwrapApplyTxErr = ApplyTxError [LedgerFailure (UtxowFailure (UtxoFailure (FeeTooSmallUTxO (Coin 201700) (Coin 200129))))]}))))

I also test it with 4 assets in one UTXO and it works. Maybe I'm doing something intrinsically wrong but if I'm not I hope these examples help you find the issue.

**Comment by SebastienGllmt** [comment]
The fee depends on the number of bytes used to represent the transaction. Every single field you set in the transaction (including minting, metadata, and even setting the fee itself) changes the number of bytes and therefore changes the fee. The fee has to be the very last thing you set and the min_fee has to be calculated with enough leeway to include the fact the value of the fee value itself may increase

**Comment by leobel** [comment]
Hi @SebastienGllmt, thank you for the reply, but I've some cases where the `min_fee` for a `Transaction` instance is the same as the fee field itself (so no more changes on the tx size right?) but on submitting I get a `FeeToSmallUTXO` error saying the tx fee should be higher than the one provided (which is the same `min_fee` returns). Where should be the error in such cases?

**Comment by leobel** [comment]
> the min_fee has to be calculated with enough leeway to include the fact the value of the fee value itself may increase
@SebastienGllmt can you explain this a little bit

**Comment by SebastienGllmt** [comment]
You haven't provided any way to actually reproduce this issue so I would assume this is just a user-error. For example, you could be accidentally adding witnesses, etc. after having set the fee.

> @SebastienGllmt can you explain this a little bit

Any function that changes the content of the transaction changes the fee required for the transaction since a tx fee is just a function of the # of bytes it uses. You can even take the hex of final tx generated by the Rust library and compute the fee yourself for it based off the # of bytes.

**Comment by leobel** [comment]
@SebastienGllmt please let me know if the following info is enough to reproduce the issue:

Tx UTXO's

    {
      inputs: [
        {
          amount: {
            quantity: 99986100553,
            unit: "lovelace",
          },
          address: "addr1q8k57z5yswuacq3ejn3egy3gjy47rxuqwnrduslkvaflr7359kkfl90wf7f9vlm99fek6e9l5zh65td8jhw63hn9skqqvdlza0",
          id: "d0c8757e5916f7abe58226c08bc1e23d15d38e4ef605981d63c0bdf3725ba9ad",
          derivation_path: [
            "1852H",
            "1815H",
            "0H",
            "1",
            "15",
          ],
          assets: [
            {
              asset_name: "54616e676f",
              quantity: 999800,
              policy_id: "2c20e21ae1b6e3f0c68f359e5ef1ecf9ff930c34f227742fddb236dc",
            },
            {
              asset_name: "54616e676f31",
              quantity: 1000000,
              policy_id: "adff86cb36373459ee63f3c9fa7d7a59667a4f0c8a9223626331bf04",
            },
            {
              asset_name: "54616e676f31",
              quantity: 1000000,
              policy_id: "cc1c83517f40f1413c9f06ff5261d838415cc3aba0d21f4c28d75285",
            },
            {
              asset_name: "54616e676f35",
              quantity: 1000000,
              policy_id: "de66182eabe139882511dfdabc5275ce36c74093441f2a56e6ff1fa8",
            },
            {
              asset_name: "54616e676f32",
              quantity: 1000000,
              policy_id: "e2f7d559dea8af0531bbca42d951167010510cc5f1de1a0b6d96a659",
            },
          ],
          index: 1,
        },
        {
          amount: {
            quantity: 1444443,
            unit: "lovelace",
          },
          address: "addr1qyuxc75xmzzy7sy955pyz4tqg0ycgttjcv2u39ay929q2yp59kkfl90wf7f9vlm99fek6e9l5zh65td8jhw63hn9skqqya2xl3",
          id: "d0c8757e5916f7abe58226c08bc1e23d15d38e4ef605981d63c0bdf3725ba9ad",
          derivation_path: [
            "1852H",
            "1815H",
            "0H",
            "0",
            "0",
          ],
          assets: [
            {
              asset_name: "54616e676f35",
              quantity: 1000000,
              policy_id: "dcb33b9c21ad1572aededaa557677db9926145c4151bcee27701acc0",
            },
          ],
          index: 0,
        },
        {
          amount: {
            quantity: 2307111,
            unit: "lovelace",
          },
          address: "addr1qymckl28apex3qd7vhn44f838ehkqu5m8gl22q67qmdu03359kkfl90wf7f9vlm99fek6e9l5zh65td8jhw63hn9skqqkpla65",
          id: "5c97bdb9d092980e9113f361e0245818aa8adb8475c8231d71638489029d582a",
          derivation_path: [
            "1852H",
            "1815H",
            "0H",
            "1",
            "13",
          ],
          assets: [
            {
              asset_name: "54616e676f32",
              quantity: 1000000,
              policy_id: "4298dc597662cce4da9f8c03c882d1b3383e8c59f51624963fc327db",
            },
            {
              asset_name: "54616e676f31",
              quantity: 1000000,
              policy_id: "699c1e9c65d208a7c44cad7db5d277e049c263476fe173bff61dd636",
            },
            {
              asset_name: "54616e676f33",
              quantity: 1000000,
              policy_id: "8ddf15810a5dae8c762a6d36ee3b0e98e81fa6a106cf32b81224c005",
            },
            {
              asset_name: "54616e676f32",
              quantity: 1000000,
              policy_id: "9b9141d38813853f666519ba01eeea9cdd302796d6c25b05f1dcb74c",
            },
            {
              asset_name: "54616e676f34",
              quantity: 1000000,
              policy_id: "9c2059a1b11fa93a2af0e9d7fa7d970e94acd430114ce6820e720755",
            },
          ],
          index: 1,
        },
      ],
      outputs: [
        {
          amount: {
            quantity: 1444443,
            unit: "lovelace",
          },
          address: "addr1qyuxc75xmzzy7sy955pyz4tqg0ycgttjcv2u39ay929q2yp59kkfl90wf7f9vlm99fek6e9l5zh65td8jhw63hn9skqqya2xl3",
          assets: [
            {
              policy_id: "1df3fc21d55d3dc1a8e9a0ea21b150a1aeee79114c56f378d2aa3354",
              asset_name: "54616e676f",
              quantity: 1000000,
            },
          ],
        },
      ],
      change: [
        {
          amount: {
            quantity: 99988188219,
            unit: "lovelace",
          },
          address: "addr1q9jeldtkg5v2wqpefagndgxcad4s6vfty9yw0vk4slvcq4f59kkfl90wf7f9vlm99fek6e9l5zh65td8jhw63hn9skqqeyyzh8",
          derivation_path: [
            "1852H",
            "1815H",
            "0H",
            "1",
            "16",
          ],
          assets: [
            {
              asset_name: "54616e676f",
              quantity: 999800,
              policy_id: "2c20e21ae1b6e3f0c68f359e5ef1ecf9ff930c34f227742fddb236dc",
            },
            {
              asset_name: "54616e676f32",
              quantity: 1000000,
              policy_id: "4298dc597662cce4da9f8c03c882d1b3383e8c59f51624963fc327db",
            },
            {
              asset_name: "54616e676f31",
              quantity: 1000000,
              policy_id: "699c1e9c65d208a7c44cad7db5d277e049c263476fe173bff61dd636",
            },
            {
              asset_name: "54616e676f33",
              quantity: 1000000,
              policy_id: "8ddf15810a5dae8c762a6d36ee3b0e98e81fa6a106cf32b81224c005",
            },
            {
              asset_name: "54616e676f32",
              quantity: 1000000,
              policy_id: "9b9141d38813853f666519ba01eeea9cdd302796d6c25b05f1dcb74c",
            },
            {
              asset_name: "54616e676f34",
              quantity: 1000000,
              policy_id: "9c2059a1b11fa93a2af0e9d7fa7d970e94acd430114ce6820e720755",
            },
            {
              asset_name: "54616e676f31",
              quantity: 1000000,
              policy_id: "adff86cb36373459ee63f3c9fa7d7a59667a4f0c8a9223626331bf04",
            },
            {
              asset_name: "54616e676f31",
              quantity: 1000000,
              policy_id: "cc1c83517f40f1413c9f06ff5261d838415cc3aba0d21f4c28d75285",
            },
            {
              asset_name: "54616e676f35",
              quantity: 1000000,
              policy_id: "dcb33b9c21ad1572aededaa557677db9926145c4151bcee27701acc0",
            },
            {
              asset_name: "54616e676f35",
              quantity: 1000000,
              policy_id: "de66182eabe139882511dfdabc5275ce36c74093441f2a56e6ff1fa8",
            },
            {
              asset_name: "54616e676f32",
              quantity: 1000000,
              policy_id: "e2f7d559dea8af0531bbca42d951167010510cc5f1de1a0b6d96a659",
            },
          ],
        },
      ],
      withdrawals: [
      ],
      certificates: undefined,
      deposits: [
      ],
      metadata: "oQCheDgxZGYzZmMyMWQ1NWQzZGMxYThlOWEwZWEyMWIxNTBhMWFlZWU3OTExNGM1NmYzNzhkMmFhMzM1NKFlVGFuZ2+laWFyd2VhdmVJZGphcndlYXZlLWlkZmlwZnNJZGdpcGZzLWlkZG5hbWVlVGFuZ29rZGVzY3JpcHRpb25xVGFuZ28gY3J5cHRvIGNvaW5kdHlwZWRDb2lu",
    }

Token metadata:

    {
      "0": {
        "1df3fc21d55d3dc1a8e9a0ea21b150a1aeee79114c56f378d2aa3354": {
          Tango: {
            arweaveId: "arweave-id",
            ipfsId: "ipfs-id",
            name: "Tango",
            description: "Tango crypto coin",
            type: "Coin",
          },
        },
      },
    }

Token policy ID: `"1df3fc21d55d3dc1a8e9a0ea21b150a1aeee79114c56f378d2aa3354"`

Token policy.script: 

    {
        "type": "sig",
        "keyHash": "3872fb02d080d624215ca8d5860529b48e89bde41638df9a4bf52f28"
    }

Token script hash (`Ed25519KeyHash.to_bech32(prefix: string)`): `"script1rhelcgw4t57ur28f5r4zrv2s5xhwu7g3f3t0x7xj4ge4gk98f85"` (prefix: `script`)

Token script on hex (`Buffer.from(NativeScript.to_bytes()).toString('hex')`):
`"8200581c3872fb02d080d624215ca8d5860529b48e89bde41638df9a4bf52f28"`

Token script private key (`Bip32PrivateKey.to_bech32()`): `"xprv13ppd42p8eftn38wfpsfntjrujyt59e84ulzmrngyywvhe8480fvyq6pwn0y9k0f6a8d7zt76g369aj4awa67wglwdtny332hk6xjt00vu3weg0hqsn4qcehcawug2t2smtpqqnjh0hzg3sld8adg6qt085e6gdp9"`

Input utxo's recovery prhase:
`["over","decorate","flock","badge","beauty","stamp","chest","owner","excess","omit","bid","raccoon","spin","reduce","rival",]`

Token name: "Tango"
Token supply: 1000000

Final tx in hex:

    "83a70083825820d0c8757e5916f7abe58226c08bc1e23d15d38e4ef605981d63c0bdf3725ba9ad01825820d0c8757e5916f7abe58226c08bc1e23d15d38e4ef605981d63c0bdf3725ba9ad008258205c97bdb9d092980e9113f361e0245818aa8adb8475c8231d71638489029d582a01018282583901386c7a86d8844f4085a50241556043c9842d72c315c897a42a8a0510342dac9f95ee4f92567f652a736d64bfa0afaa2da795dda8de658580821a00160a5ba1581c1df3fc21d55d3dc1a8e9a0ea21b150a1aeee79114c56f378d2aa3354a14554616e676f1a000f424082583901659fb5764518a700394f5136a0d8eb6b0d312b2148e7b2d587d98055342dac9f95ee4f92567f652a736d64bfa0afaa2da795dda8de658580821b0000001747c2ac3bab581c2c20e21ae1b6e3f0c68f359e5ef1ecf9ff930c34f227742fddb236dca14554616e676f1a000f4178581c4298dc597662cce4da9f8c03c882d1b3383e8c59f51624963fc327dba14654616e676f321a000f4240581c699c1e9c65d208a7c44cad7db5d277e049c263476fe173bff61dd636a14654616e676f311a000f4240581c8ddf15810a5dae8c762a6d36ee3b0e98e81fa6a106cf32b81224c005a14654616e676f331a000f4240581c9b9141d38813853f666519ba01eeea9cdd302796d6c25b05f1dcb74ca14654616e676f321a000f4240581c9c2059a1b11fa93a2af0e9d7fa7d970e94acd430114ce6820e720755a14654616e676f341a000f4240581cadff86cb36373459ee63f3c9fa7d7a59667a4f0c8a9223626331bf04a14654616e676f311a000f4240581ccc1c83517f40f1413c9f06ff5261d838415cc3aba0d21f4c28d75285a14654616e676f311a000f4240581cdcb33b9c21ad1572aededaa557677db9926145c4151bcee27701acc0a14654616e676f351a000f4240581cde66182eabe139882511dfdabc5275ce36c74093441f2a56e6ff1fa8a14654616e676f351a000f4240581ce2f7d559dea8af0531bbca42d951167010510cc5f1de1a0b6d96a659a14654616e676f321a000f4240021a00035935031a0366d980075820f48d4186fb81681c56515fcc58e385c58ebe41fe766bc1aed8df46f02803b2e1080009a1581c1df3fc21d55d3dc1a8e9a0ea21b150a1aeee79114c56f378d2aa3354a14554616e676f1a000f4240a200848258205e4869645a659abd7a3e0255e150b00263ec00e6604f69e903d06b8da79be32d5840c87d4afe74e574a0358c72d27f5850453cd68ceca2c3f5fe2c8e5b2870f40b939052e0808991f4d8d339f8da39b2dd71eab192250593423dbec4143a9fedcf028258201a4c7690edbc56faaa35070a74639c2c0199858201a8fd2d2eb970ad31af525c5840f10198f91a1ab167207b53029f53250ab6c95d6cdf3b50156c8955c0084754a42c59ccd4847c2397a318d3be966b7a3a760b8ab78b1772e8fc9b85ad2b144e0c8258200090cd2ae094426ba319f0249e5c00efee29be01706f23b8363316af33cea28158407f85cb550dc61bc974f5d1adb953700b09338f3a272a846c57d08df3512f37d9292aae5272355288140b454b7781ec860f2471f771af6821f5f379c4f5de620b8258202bc6e181d6abe60831469525fe0a8ce2e064b1eb2f6e74e0a5a415fa7c956eec58408d7cceaf5e7699e6f25d69c2e01c2b9bbbb3f75e14d4cf211c213534567c13af4c8a95469a6a87b33630db0d53cbc08dba3243a8b77037472bb2b8097ea3ea0f01818200581c3872fb02d080d624215ca8d5860529b48e89bde41638df9a4bf52f28a100a178383164663366633231643535643364633161386539613065613231623135306131616565653739313134633536663337386432616133333534a16554616e676fa5696172776561766549646a617277656176652d69646669706673496467697066732d6964646e616d656554616e676f6b6465736372697074696f6e7154616e676f2063727970746f20636f696e647479706564436f696e"

fee from UTXOs is `inputs - outputs - change = 219445` and the bytes in tx is: 1456 so the actual fee `1456*44 + 155381 = 219445` looks ok. 

Traying to submit the tx: 

    {
        "type": "Tx MaryEra",
        "description": "",
        "cborHex": "83a70083825820d0c8757e5916f7abe58226c08bc1e23d15d38e4ef605981d63c0bdf3725ba9ad01825820d0c8757e5916f7abe58226c08bc1e23d15d38e4ef605981d63c0bdf3725ba9ad008258205c97bdb9d092980e9113f361e0245818aa8adb8475c8231d71638489029d582a01018282583901386c7a86d8844f4085a50241556043c9842d72c315c897a42a8a0510342dac9f95ee4f92567f652a736d64bfa0afaa2da795dda8de658580821a00160a5ba1581c1df3fc21d55d3dc1a8e9a0ea21b150a1aeee79114c56f378d2aa3354a14554616e676f1a000f424082583901659fb5764518a700394f5136a0d8eb6b0d312b2148e7b2d587d98055342dac9f95ee4f92567f652a736d64bfa0afaa2da795dda8de658580821b0000001747c2ac3bab581c2c20e21ae1b6e3f0c68f359e5ef1ecf9ff930c34f227742fddb236dca14554616e676f1a000f4178581c4298dc597662cce4da9f8c03c882d1b3383e8c59f51624963fc327dba14654616e676f321a000f4240581c699c1e9c65d208a7c44cad7db5d277e049c263476fe173bff61dd636a14654616e676f311a000f4240581c8ddf15810a5dae8c762a6d36ee3b0e98e81fa6a106cf32b81224c005a14654616e676f331a000f4240581c9b9141d38813853f666519ba01eeea9cdd302796d6c25b05f1dcb74ca14654616e676f321a000f4240581c9c2059a1b11fa93a2af0e9d7fa7d970e94acd430114ce6820e720755a14654616e676f341a000f4240581cadff86cb36373459ee63f3c9fa7d7a59667a4f0c8a9223626331bf04a14654616e676f311a000f4240581ccc1c83517f40f1413c9f06ff5261d838415cc3aba0d21f4c28d75285a14654616e676f311a000f4240581cdcb33b9c21ad1572aededaa557677db9926145c4151bcee27701acc0a14654616e676f351a000f4240581cde66182eabe139882511dfdabc5275ce36c74093441f2a56e6ff1fa8a14654616e676f351a000f4240581ce2f7d559dea8af0531bbca42d951167010510cc5f1de1a0b6d96a659a14654616e676f321a000f4240021a00035935031a0366d980075820f48d4186fb81681c56515fcc58e385c58ebe41fe766bc1aed8df46f02803b2e1080009a1581c1df3fc21d55d3dc1a8e9a0ea21b150a1aeee79114c56f378d2aa3354a14554616e676f1a000f4240a200848258205e4869645a659abd7a3e0255e150b00263ec00e6604f69e903d06b8da79be32d5840c87d4afe74e574a0358c72d27f5850453cd68ceca2c3f5fe2c8e5b2870f40b939052e0808991f4d8d339f8da39b2dd71eab192250593423dbec4143a9fedcf028258201a4c7690edbc56faaa35070a74639c2c0199858201a8fd2d2eb970ad31af525c5840f10198f91a1ab167207b53029f53250ab6c95d6cdf3b50156c8955c0084754a42c59ccd4847c2397a318d3be966b7a3a760b8ab78b1772e8fc9b85ad2b144e0c8258200090cd2ae094426ba319f0249e5c00efee29be01706f23b8363316af33cea28158407f85cb550dc61bc974f5d1adb953700b09338f3a272a846c57d08df3512f37d9292aae5272355288140b454b7781ec860f2471f771af6821f5f379c4f5de620b8258202bc6e181d6abe60831469525fe0a8ce2e064b1eb2f6e74e0a5a415fa7c956eec58408d7cceaf5e7699e6f25d69c2e01c2b9bbbb3f75e14d4cf211c213534567c13af4c8a95469a6a87b33630db0d53cbc08dba3243a8b77037472bb2b8097ea3ea0f01818200581c3872fb02d080d624215ca8d5860529b48e89bde41638df9a4bf52f28a100a178383164663366633231643535643364633161386539613065613231623135306131616565653739313134633536663337386432616133333534a16554616e676fa5696172776561766549646a617277656176652d69646669706673496467697066732d6964646e616d656554616e676f6b6465736372697074696f6e7154616e676f2063727970746f20636f696e647479706564436f696e"
    }  

I got this error: 
cardano-cli transaction submit --tx-file tx.signed --mainnet

    Command failed: transaction submit  Error: Error while submitting tx: ShelleyTxValidationError ShelleyBasedEraMary (ApplyTxError [LedgerFailure (UtxowFailure (UtxoFailure (FeeTooSmallUTxO (Coin 245600) (Coin 219445))))])

**Comment by SebastienGllmt** [comment]
Sounds like probably the issue is in the cardano-node setup and not with this library if manually calculating `1456*44 + 155381 = 219445`.

Some things to check

1. Is your local cluster using the correct protocol parameters (44 and 155381)
2. Do you get the same issue if you use the [cardano-submit-api](https://github.com/input-output-hk/cardano-node/tree/master/cardano-submit-api) ?

If you're still getting issues, I suggest maybe sending final tx hex to the people working on cardano-node / cardano-wallet because this doesn't sound like a problem related to the Rust library. You can even verify yourself that the minimum fee function really is just ax +b by looking at its implementation [here](https://github.com/input-output-hk/cardano-ledger-specs/blob/a2dc0efb9dec032d42d34f90452dd4ffda5eadbc/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/LedgerState.hs#L783)

**Comment by leobel** [comment]
Hi @SebastienGllmt you're right, the first item to check was my problem. Thank you so much for your time and help!
