### ISSUE TITLE
How to use this libaray in a java application

### ISSUE THREAD

**Issue by wumingmo** [Emurgo/cardano-serialization-lib#168]
Hi, 

We want to create and sign cardano transactions programmatically in a java application using this library. But those available packages looks like for application written in typescript language. Can we use this library in an applicatio written in java language?

Thank you

**Comment by SebastienGllmt** [comment]
You may be interested in https://satran004.medium.com/cardano-client-lib-a-java-library-to-interact-with-cardano-part-i-83fba0fee537 which uses our library internally for some functionality.

**Comment by wumingmo** [comment]
Thank you, @SebastienGllmt
