### ISSUE TITLE
how to transfer  Daedalus Dd-type addresses

### ISSUE THREAD

**Issue by benjamintshi** [Emurgo/cardano-serialization-lib#178]
eg:
const outputAddress = CardanoWasm.Address.from_bech32(
  "addr1q98vryjhl6uz4kyw0y4x9rjxzpdmfykzqdevxwats097946wcxf90l4c9tvgu7f2v28yvyzmkjfvyqmjcva6hq7tuttsv8550d"
);
const changeAddress = CardanoWasm.Address.from_bech32(
  "addr1v98vryjhl6uz4kyw0y4x9rjxzpdmfykzqdevxwats09794c5us38q"
);
i want to send some coin to address ( "DdzFFzCqrht1QDbnAeKcwXWymxUqCqWwiqq3QKWsPsgHk9RfcFwyZCUyzcd9gDMtj2pMGHURQpvhefFGw9tkAMuwstJ1868inGWKyDAa")
this address can not work.

**Comment by SebastienGllmt** [comment]
You can specify any address you want as an output including Byron addresses. 
You can use the `ByronAddress` struct and then use its `to_address` function to add it to an output

**Comment by benjamintshi** [comment]
@SebastienGllmt

**Comment by benjamintshi** [comment]
const outputByronAddress = CardanoWasm.ByronAddress.from_bytes(
  base58.decode(
    "DdzFFzCqrhsg9F1joqXWJdGKwn6MaNavCqPsrZcjADRjA4ifEtrBmREJZyCojtuexKjMKNFr6CoU7Gx6PPR7pq14JxvPZuuk2xVkzn8p"
  )
).to_address();
