### ISSUE TITLE
generating-transactions.md has a broken link

### ISSUE THREAD

**Issue by katomm** [Emurgo/cardano-serialization-lib#180]
generating-transactions.md has a broken link to https://docs.cardano.org/projects/cardano-node/en/latest/stake-pool-operations/keys_and_addresses.html

**Comment by vsubhuman** [comment]
I see this is already fixed: https://github.com/Emurgo/cardano-serialization-lib/commit/ee6403a210e0ab1f42f13202d62033756ea0e038

Thank you, @katomm!
