### ISSUE TITLE
Minimum UTxO calculation missmatch (7.1.0)

### ISSUE THREAD

**Issue by Scitz0** [Emurgo/cardano-serialization-lib#194]
It has been reported by users that for certain utxo's, often containing a large number of tokens, that the way cardano-serialization-lib calculates the minimum amount of Lovelace that output utxo is required to contain, doesn't match with our calculation.

I haven't found a way to replicate it using one of my own wallets but I was given access to a wallet in read-only(pub key) mode where I was able to replicate the issue. It's not a single occurrence either but has been reported by multiple users with large NFT collections. It's not about the number of tokens included in the output though as I have been able to construct large outputs without issue where the calculation from csl matches our calculation down to the Lovelace. Checked by first outputting the value from our calculation and then trying to construct the output with one Lovelace and watching the response from the error message where it prints the required amount. My guess is that it's related to the format of the asset name somehow. 

Our method to calculate minimum utxo has also been used in CLI tools for a long time without a single user reporting issues with it. 

The calculation is based on this documentation:
https://github.com/input-output-hk/cardano-ledger-specs/blob/master/doc/explanations/min-utxo.rst

And here is our code. It might be an error in our code but in that case, I cant spot it. 

```javascript
export const getMinUtxo       = (protoParams: IProtocolParams, tokens: IToken[]): string => {

  // using Number data type internally (fine for numbers of this size)

  let minUtxo                 = protoParams.minUTxOValue

  if(tokens.length === 0) return minUtxo.toString()

  // chain constants, based on: https://hydra.iohk.io/build/5949624/download/1/shelley-ma.pdf
  const k0                    = 0   // TODO: coinSize=0 in mary-era, 2 in alonzo-era
  const k1                    = 6
  const k2                    = 12  // assetSize=12
  const k3                    = 28  // pidSize=28
  const k4                    = 8   // word=8 bytes
  const utxoEntrySizeWithoutVal = 27  // 6 + txOutLenNoVal(14) + txInLen(7)
  const adaOnlyUTxOSize = utxoEntrySizeWithoutVal + k0

  const pidCollector          = []
  const assetsCollector       = []
  const nameCollector         = []

  for(const token of tokens) {

    if(pidCollector.indexOf(token.policy) === -1) pidCollector.push(token.policy)
    if(assetsCollector.indexOf(token.policy + token.name) === -1) assetsCollector.push(token.policy + token.name)
    if(token.name.length > 0 && nameCollector.indexOf(token.name) === -1) nameCollector.push(token.name)
  }

  const sumAssetNameLengths   = nameCollector.reduce((acc, val) => ( acc + (val.length/2) ), 0)
  const roundupBytesToWords   = Math.floor(((assetsCollector.length * k2) + sumAssetNameLengths + (pidCollector.length*k3) + (k4-1)) / k4)
  const tokenBundleSize       = k1 + roundupBytesToWords
  const minAda                = Math.floor(protoParams.minUTxOValue / adaOnlyUTxOSize) * (utxoEntrySizeWithoutVal + tokenBundleSize)

  if(minAda > Number(minUtxo)) { minUtxo = minAda }

  return minUtxo.toString()
}
```

**Comment by Scitz0** [comment]
Looking at it some more and the difference cant come from anywhere but min_ada_required() / bundle_size() functions. I guess the only way to do that is to compare each calculation given the same assets as input. 

To give you a sample set to try with I hex encoded the bytes from a Value that I tried to add to output that failed.
`Value 18666648 less than the minimum UTXO value 18777759`

If you could show me what min_ada_required() calculates at the different steps given this input Value I can compare with our code.

`821a011cd498b82f581c4fd307695d244431ca93599be34d9aea403f24cf30f2eadcd7a178e2a1487377616e6b70696501581c50000001f7d74d2f95f82c4cfeb13f4119c350c2f91090fd69757fbda34f43617264616e6f526f6e696e313130014f43617264616e6f526f6e696e323732014f43617264616e6f526f6e696e34313401581c5090573eaf3ca637bce1fb23afc98a7ae1bc803df151a3c82e0921b5a14e4b6174654665617244656164313001581c513cdfefd0c39c79ff77b77f28aca06e74a6f3bd63a2599f8481db41a15454686546697273744b6579686f6c64657230383101581c52f02b66a66da2935d8b2c6424956a000b15e971004b1e32d88e4820a15254484548494748505249455354455353303101581c531052a4c667b84648c74f362c0c1878c3001b0f7696815752a4bed1a1554e46545530303132506c616e657450616c7a30353301581c558430d47055f97e15bfeb264a68c8e1c5acef1712bd36ab31ceb22ca14346414d01581c55dd4519ca2ce4071ba005eb209506d2140cccba49cdc3419dda695ca148417269657330303501581c56cffff175760004b9f2da7d2120341baee137f2131b09e7a0ad3eb4a1581b7766303030344368616f7469634d617468656d617469637330313801581c570f3e65dc46e8edf8ac288f13385297e6f749a8fd84064cdcda2839a1534e465455303031384e46544372617a6530393101581c597ecdd4be1ffdcd9426ca4cfaaf75285650351045e21bfc7b7f0ba8a1465275706565730a581c5b597e4f6560f9403dcba7618fef04df235bfcb72552176c0e8a599ba1444265657201581c5d58881d98f367befbce25ff966ee22b4de8f099da0e7f71c089e542a35543436f756e747269657342726f6e7a654d6564616c01464368696e613801464a6170616e3901581c5df412e3eb27ffa1665302f8bf97f74f89fa42215d3e5b09464c1c14a14b4c75636b794e654b6f696e190649581c61aaaaad465f0f8a28aec3461beaf38990f671f2e4bc979ddda194c4a1581b5468654d6973616476656e74757265736f66426f6763686932316101581c62ea7cb573306f6c272a2ff066679f2e4216270311d8e71b5f765251ac4a4164616c6f746c303134014a4164616c6f746c303434014a4164616c6f746c313439014a4164616c6f746c323337014a4164616c6f746c323430014a4164616c6f746c343432014a4164616c6f746c343836014a4164616c6f746c363036014a4164616c6f746c363530014a4164616c6f746c363638014a4164616c6f746c363932014a4164616c6f746c38333801581c6590687768bf097900b546a15efb0e413010cbefca2ade9f629c6d43a14c566f78656c697a656432303801581c66fb86c135d9d1350d29abff0b1c549a4b8204885227f76346601782a1475448454d4f4f4e01581c68fb69abc121dfb77be74e5d589876ea7fa271a70a905a4bbc580a60a1554e465455303030365375736869427974657330333101581c6ce4f2fd965a3f782baa0b9aa421c21299d434ad6c566ed077d6d663a1504475636343616d65466972737430363601581c73c590cc5d909ff19c2521bf14f673928a1fe3ff0e2c6eaa7bd36d5da14a45617450697a7a61303101581c76c2ddb32f3d974be983c39789313ab26e1791ef7a1bb09a55d2ade9a158186e65766572466f72676574446973636f726452617265303401581c77e4da914068a50d9d9420dbdda80817b55516ac6304273879318d5aa14f43756c746f664c75636b794e656b6f01581c78517792ad45d22f70a8ec4a1d30c458925938a8e7a5d9acb2449a63ad4f434d42594e41444150555a5a4c45310153434d42594e41444150555a5a4c45424b524437014c434d42594e50555a5a4c4531014d434d42594e50555a5a4c453130014d434d42594e50555a5a4c453131014c434d42594e50555a5a4c4532014c434d42594e50555a5a4c4533014c434d42594e50555a5a4c4534014c434d42594e50555a5a4c4535014c434d42594e50555a5a4c4536014c434d42594e50555a5a4c4537014c434d42594e50555a5a4c4538014c434d42594e50555a5a4c453901581c787622826f8ebd1baa04e5a9a76ae0eac7392f730544528738faafcba14f526f62696e5265645374616d70303901581c7b5fd95985e08b72a5c37b9d3c7d863bb8a6fed82ef4741594be357da1487377616e6b70696501581c7b9e74668dad56367f9314485a402c726d3bb8561834fdf253c65c4ba14f566973696f6e73426c61636b4f696c01581c7c306b00720b3a941ede9d6e1c469ec678cea1d1be8f70ff146dd6c8a1487377616e6b70696501581c84c0acb101c14416ad92859c429058871e201804468d5f353be31d71a64f50756e6b7374657241727432343038014f50756e6b7374657241727436393534014f50756e6b7374657241727437343733014f50756e6b7374657241727437353237014f50756e6b7374657241727437363831014f50756e6b737465724172743736393501581c8579617b51f533912b1652b7baa57a97335490848ec750741699db3ca34a535452454e4754483031014a544845444556494c3031014b5448454c4f56455253303101581c88814632e81b0d0d92d76bf7c7321351618a331558eb76f699f62580a1444f50323301581c89ee9ed7ce189c466be5937af4dc9103d71cc9ec150efdf158d4fe13a35043617264616e6f417065334431313830015043617264616e6f417065334432363032015043617264616e6f41706533443237383601581c89fa6dc66a24799ccaee43a3a16930bb045a8152fdf2a2642034774fa14f506c616e657450616c7a313134303801581c8acb8d48ccee9f22265bcf1f41b4bcffbcecf5a5a85c5e4e1bb7bad0a1464f726967696e01581c8bd876119ed2152848cc364db9fab76c5ed8d98fdf53c2157ffd4092a1487377616e6b70696501581c8f80ebfaf62a8c33ae2adf047572604c74db8bc1daba2b43f9a65635a45243617264616e6f57617272696f7235393535015243617264616e6f57617272696f7236313933015243617264616e6f57617272696f7238393131015243617264616e6f57617272696f723938383101581c8fea90d673cbdd5b3da3309fb7cf1dcbb1c485ba6a7e5148468351a2a14f457570686f726963446f736573333601581c900c8cf13faf04300988e173b2695b74423da2be1615e544ddf7f9d7a14d48617070795768616c6530303101581c91acca0a2614212d68a5ae7313c85962849994aab54e340d3a68aabba14653483435363101581c922cb8a086179b1b0464f1b80c1679a210d9ed9b1e1b8374f27496e6a1445250313401581c92e7d5f2ac1994d2916d547395ab8ce650bb7387a0f70a9efbd543a6a1534e46545530303131436f6e6a7572657231363401581c942f26b14e57ab29ceac5f5d0e1ce392001ac486a019ab272f37c9c5a3581a434d42594e784261636b776172647347656f6d6574727942303801581a434d42594e784261636b776172647347656f6d6574727945303301581a434d42594e784261636b776172647347656f6d6574727947303801581c949dbdd63f3157100e3b98dffb20259f5053bcddb1ce6fd253c6da85a54e466c6f77496e64696142756c6c30014e466c6f77496e646961466f757231014d466c6f77496e6469614f6e6532014f466c6f77496e646961546872656536014d466c6f77496e64696154776f3601581c97305ec3684b4e5ac2977d44ee05fd453b038ae882e665fd6499484ca45818456e70696d6f6e7943616e61646143656e746175723030380156456e70696d6f6e7943616e616461476f6c656d3031330156456e70696d6f6e7943616e616461486f7273653032330157456e70696d6f6e7943616e6164614b6e6967687430383701581ca8731ef90e36acc7083d9bd501f733cb610ad67e7143d891fd45ab89a14e53776565744b697473756e65303901581cabe233937c19a90f826d94f121029a2fccf2bc411b9c5456e2ba49dba155496e746f5468654c6f6f6b696e67476c617373303401581cd3bbe5b2a27a392fbac2471e0c42f54ddd55da1005f86e9c18c3e082a1581a526f79616c4d6348756d70696e4b69747469657342656163683201`

**Comment by Scitz0** [comment]
I couldn't let this go so I implemented the rust function min_ada_required() as close as possible in js to debug and compare against our function and I found the issue.

The problem lies in this calculation:
https://github.com/Emurgo/cardano-serialization-lib/blob/7.1.0/rust/src/utils.rs#L724
E.g. sum_asset_name_lengths. It seems the cardano-serialization-lib implementation sums up the byte length of all asset names from all policies. But this doesn't take into consideration if there are two tokens with the same name but in different policies. 

From the documentation both libraries are based on you can read this:

> sumAssetNameLengths : the sum of the length of the ByteStrings representing distinct asset names eg. if B is as above,
> sumAssetNameLengths B = length myAssetNameSBS + length yourAssetNameSBS + length someAssetNameSBS

Note '**_distinct asset names_**'. For example Value posted in previous post you will notice that there is a token with the name 'swankpie' (`7377616e6b706965`) in three different policies:
`7b5fd95985e08b72a5c37b9d3c7d863bb8a6fed82ef4741594be357d`
`7c306b00720b3a941ede9d6e1c469ec678cea1d1be8f70ff146dd6c8`
`8bd876119ed2152848cc364db9fab76c5ed8d98fdf53c2157ffd4092`

This causes CSL to calculate sum_asset_name_lengths to `1333` while our code (that only counts unique asset names) gives a value of `1309 `.

**Comment by rooooooooob** [comment]
@Scitz0  Just to be sure, if you use the smaller of the two values it's accepted by the cardano main network, right? (i.e. they used the smaller interpretation in their ledger code) If so we we have a fix for it pending review. I just want to make sure since they seem separate to me if they're under different policy IDs as they increase the size of output on-chain, but if that's what the cardano node is expecting then that's what we'll use. Thanks for all the debugging!

**Comment by Scitz0** [comment]
> @Scitz0 Just to be sure, if you use the smaller of the two values it's accepted by the cardano main network, right? (i.e. they used the smaller interpretation in their ledger code) If so we we have a fix for it pending review. I just want to make sure since they seem separate to me if they're under different policy IDs as they increase the size of output on-chain, but if that's what the cardano node is expecting then that's what we'll use. Thanks for all the debugging!

Hi, I can confirm that the node indeed accept the transaction only counting unique asset names. I did a test in CNTools(that has the same implementation) on TestNet and created two different policies, both with a token called TestMinUtxo. Added some debugging code to verify and sum_asset_name_lengths was set to 11. Min utxo ended up being 1.666665 Ada and tx went through just fine.

**Comment by rhyslbw** [comment]
@rooooooooob `minUtxoValue` is now an obsolete protocol parameter, as it's replaced by a [calculation utxoEntrySize]((https://github.com/input-output-hk/cardano-ledger-specs/blob/master/alonzo/impl/src/Cardano/Ledger/Alonzo/Rules/Utxo.hs#L98-L111). Are you considering this in the fix?

**Comment by Scitz0** [comment]
We are talking about the same but different things here 😄 

This issue addresses the thing about unique asset names and how these are calculated. I have confirmed that the cardano-node implementation accepts the transaction if you only count unique asset names even if they are in different policies. 

Then we have the Alonzo changes regarding coin_size that currently is set to 0 in cardano-serialization-lib code but I have confirmed with @SebastienGllmt that they have a task to update this post Alonzo HF. This deals with Ada and native token calculation. I don't read scientific papers very well so not sure how Alonzo plutus scripts affect the calculation. I tried to read the above snippet from ledger-spec about dataHashSize but I will leave this for others to comment on as I don't fully understand how this affects the existing calculation. I assume dataHashSize needs to be added based on the existence of a plutus script.

It would be nice to see an update to https://github.com/input-output-hk/cardano-ledger-specs/blob/master/doc/explanations/min-utxo.rst now with Alonzo deployed.

**Comment by rhyslbw** [comment]
> We are talking about the same but different things here

Understood. I was just adding this as a side-note to see if it was being addressed at the same time, since the result of applying the new formula produces a slightly smaller min value.

> It would be nice to see an update to https://github.com/input-output-hk/cardano-ledger-specs/blob/master/doc/explanations/min-utxo.rst now with Alonzo deployed.

:100:
