### ISSUE TITLE
Maximum output size of 0 exceeded.

### ISSUE THREAD

**Issue by sinanouri** [Emurgo/cardano-serialization-lib#207]
I am getting Maximum output size of 0 exceeded error while trying to create transaction
here are my data:
from address: addr1qx7q3qspd7q703jhs39sfqqjxaq30yg4cym59dus39wukq4s32za72zds7hf5vk875rlqv9znzy7zs3v322vhhnzwwkqvkpgdn
to address: addr1q8y0rn06zzyyswheuva4d587q3h2dryjeamqqtrq7n4ge0he8jdv7gtds9nclsm60vf6a52ef5mljtrm2rlecncpff9st0er39
UTXOs: [
    {
        "txHash": "da762aa9c0316eee26e1693245dd263681cc3dfb50fc63f3419f818427f7af60",
        "index": 0,
        "value": "3000000"
    },
    {
        "txHash": "7e06336f0808208b525c2c19cbb904f53f1b5083e7e1bf3f77f501b1be221af4",
        "index": 0,
        "value": "1000000"
    }
]

my code:
`const CardanoWasm = require('@emurgo/cardano-serialization-lib-nodejs')
const bip39 = require('bip39')
// instantiate the tx builder with the Cardano protocol parameters - these may change later on
const txBuilder = CardanoWasm.TransactionBuilder.new(
    // all of these are taken from the mainnet genesis settings
    // linear fee parameters (a*size + b)
    CardanoWasm.LinearFee.new(CardanoWasm.BigNum.from_str('44'), CardanoWasm.BigNum.from_str('155381')),
    // minimum utxo value
    CardanoWasm.BigNum.from_str('1000000'),
    // pool deposit
    CardanoWasm.BigNum.from_str('500000000'),
    // key deposit
    CardanoWasm.BigNum.from_str('2000000')
);

// add a keyhash input - for ADA held in a Shelley-era normal address (Base, Enterprise, Pointer)
let words = " weapon nothing ... cactus tired"
let entropy = bip39.mnemonicToEntropy(words)
const rootKey = CardanoWasm.Bip32PrivateKey.from_bip39_entropy(
    Buffer.from(entropy, 'hex'),
    Buffer.from(''),
);
const prvKey = rootKey.to_raw_key()
txBuilder.add_key_input(
    prvKey.to_public().hash(),
    CardanoWasm.TransactionInput.new(
        CardanoWasm.TransactionHash.from_bytes(
            Buffer.from("da762aa9c0316eee26e1693245dd263681cc3dfb50fc63f3419f818427f7af60", "hex")
        ), // tx hash
        0, // index
    ),
    CardanoWasm.Value.new(CardanoWasm.BigNum.from_str('3000000'))
);
txBuilder.add_key_input(
    prvKey.to_public().hash(),
    CardanoWasm.TransactionInput.new(
        CardanoWasm.TransactionHash.from_bytes(
            Buffer.from("7e06336f0808208b525c2c19cbb904f53f1b5083e7e1bf3f77f501b1be221af4", "hex")
        ), // tx hash
        0, // index
    ),
    CardanoWasm.Value.new(CardanoWasm.BigNum.from_str('1000000'))
);

// base address
const shelleyOutputAddress = CardanoWasm.Address.from_bech32("addr1q8y0rn06zzyyswheuva4d587q3h2dryjeamqqtrq7n4ge0he8jdv7gtds9nclsm60vf6a52ef5mljtrm2rlecncpff9st0er39");
// pointer address
const shelleyChangeAddress = CardanoWasm.Address.from_bech32("addr1qx7q3qspd7q703jhs39sfqqjxaq30yg4cym59dus39wukq4s32za72zds7hf5vk875rlqv9znzy7zs3v322vhhnzwwkqvkpgdn");

// add output to the tx
txBuilder.add_output(
    CardanoWasm.TransactionOutput.new(
        shelleyOutputAddress,
        CardanoWasm.Value.new(CardanoWasm.BigNum.from_str('1000000'))
    ),
);

// set the time to live - the absolute slot value before the tx becomes invalid
txBuilder.set_ttl(410021);

// calculate the min fee required and send any change to an address
txBuilder.add_change_if_needed(shelleyChangeAddress)
console.log(txBuilder)
// once the transaction is ready, we build it to get the tx body without witnesses
const txBody = txBuilder.build();
const txHash = CardanoWasm.hash_transaction(txBody);
console.log(txHash)
const witnesses = CardanoWasm.TransactionWitnessSet.new();

// add keyhash witnesses
const vkeyWitnesses = CardanoWasm.Vkeywitnesses.new();
const vkeyWitness = CardanoWasm.make_vkey_witness(txHash, prvKey);
vkeyWitnesses.add(vkeyWitness);
witnesses.set_vkeys(vkeyWitnesses);

// create the finalized transaction with witnesses
const transaction = CardanoWasm.Transaction.new(
    txBody,
    witnesses,
    undefined, // transaction metadata
);

console.log(transaction)`

the error i get:

/home/ada/node_modules/@emurgo/cardano-serialization-lib-nodejs/cardano_serialization_lib.js:12283
    throw takeObject(arg0);
    ^
Maximum output size of 0 exceeded. Found: 65

**Comment by vsubhuman** [comment]
Hi! Plz see notes for the 9.0 release: https://github.com/Emurgo/cardano-serialization-lib/releases/tag/9.0.0

You need to add two new arguments to the transaction builder: max-value-size and max-tx-size 

For the next version I'll add some assertions there to fast fail on zero values.

**Comment by CherryDT** [comment]
In case someone gets this even though they pass a value: Note that for `max_value_size` and `max_tx_size` you can **not** pass a BigNum, otherwise you'll get this error (confusingly)! Pass a regular number instead.
