### ISSUE TITLE
Transaction validity range clarification

### ISSUE THREAD

**Issue by rhyslbw** [Emurgo/cardano-serialization-lib#210]
Do the `validity_start_interval` and `ttl` properties correspond to `invalid_before` and `invalid_hereafter` respectively?
https://github.com/Emurgo/cardano-serialization-lib/blob/886de9866d79c4c25eb0495a3351a1feca314b77/rust/src/lib.rs#L216-L231

**Comment by rooooooooob** [comment]
Can you please clarify more? If you're referring to the [invalid_before](https://github.com/input-output-hk/cardano-ledger-specs/blob/master/eras/alonzo/test-suite/cddl-files/alonzo.cddl#L339) and [invalid_hereafter](https://github.com/input-output-hk/cardano-ledger-specs/blob/master/eras/alonzo/test-suite/cddl-files/alonzo.cddl#L342) native scripts, then no. In the binary spec these two fields ttl and validity_start_interval are referred to as ["time to live"](https://github.com/input-output-hk/cardano-ledger-specs/blob/master/eras/alonzo/test-suite/cddl-files/alonzo.cddl#L54) and ["validity start interval"](https://github.com/input-output-hk/cardano-ledger-specs/blob/master/eras/alonzo/test-suite/cddl-files/alonzo.cddl#L59) which refer to the entire transaction, not for just one native script.

**Comment by rhyslbw** [comment]
_Sorry for the delayed response @rooooooooob._

It appears the CDDL is actually out of date, so you may end up dealing with a breaking change when it's updated to align with the ledger model. I'll close this issue since it doesn't really need tracking given you're generating the types.

- [invalidBefore](https://github.com/input-output-hk/cardano-ledger-specs/blob/30050926ef22dad47d45a774baaa14c3a69ba9f5/eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxBody.hs#L596)
- [invalidHereafter](https://github.com/input-output-hk/cardano-ledger-specs/blob/30050926ef22dad47d45a774baaa14c3a69ba9f5/eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxBody.hs#L585)
