### ISSUE TITLE
Error: magic header not detected

### ISSUE THREAD

**Issue by derneuere** [Emurgo/cardano-serialization-lib#223]
I installed the serialization lib by adding it to my package.json with the following line:
```
"@emurgo/cardano-serialization-lib-browser": "^9.1.0",
```
I then installed it with "yarn install". When I start my frontend I get the following error:

```
./node_modules/@emurgo/cardano-serialization-lib-browser/cardano_serialization_lib_bg.wasm
Module parse failed: magic header not detected
File was processed with these loaders:
 * ./node_modules/file-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
Error: magic header not detected
```

The documentation only talks about building the project, so I assumed that I can use it like a regular package. Are there any steps that I missed?

**Comment by lowkeyshift** [comment]
I have established this configuration, but I am confused at how I would get passed this error.

```./node_modules/@emurgo/cardano-serialization-lib-browser/cardano_serialization_lib_bg.wasm
WebAssembly module is included in initial chunk.
This is not allowed, because WebAssembly download and compilation must happen asynchronous.
Add an async splitpoint (i. e. import()) somewhere between your entrypoint and the WebAssembly module:
* multi (webpack)/hot/dev-server.js ./node_modules/react-scripts/node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js ./node_modules/react-dev-utils/webpackHotDevClient.js ./src/index.js --> ./src/index.js --> ./src/App.js --> ./node_modules/@emurgo/cardano-serialization-lib-browser/cardano_serialization_lib.js --> ./node_modules/@emurgo/cardano-serialization-lib-browser/cardano_serialization_lib_bg.wasm```

I am assuming that I would add the `useEffect()` in the .jsx files I want to use the wasm functionality in, correct?
Also I added a catch() at the end as I had an error about the async/promise not having a catch. This I believe is because of the version of react that I am using.

```
    useEffect(() => {
        async function start() {
            const wasm = await import('@emurgo/cardano-serialization-lib-browser').catch(console.error);
        }
        start();
      }, []);
      ```

I am not sure you are following the same repo, but I am trying to leverage the [Spacebudz](https://github.com/Berry-Pool/spacebudz/tree/3c5dd2b2dfb905d7649c9312563a2ab530867892/src/cardano) build of this, but make this work in my react app. Curious to your thoughts here.

**Comment by derneuere** [comment]
I don't use functional components that often. I used a class component and imported on componentDidMount. That did work.

**Comment by pedromtcosta** [comment]
> I have established this configuration, but I am confused at how I would get passed this error.
> 
> ```
> WebAssembly module is included in initial chunk.
> This is not allowed, because WebAssembly download and compilation must happen asynchronous.
> Add an async splitpoint (i. e. import()) somewhere between your entrypoint and the WebAssembly module:
> * multi (webpack)/hot/dev-server.js ./node_modules/react-scripts/node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js ./node_modules/react-dev-utils/webpackHotDevClient.js ./src/index.js --> ./src/index.js --> ./src/App.js --> ./node_modules/@emurgo/cardano-serialization-lib-browser/cardano_serialization_lib.js --> ./node_modules/@emurgo/cardano-serialization-lib-browser/cardano_serialization_lib_bg.wasm```
> 
> I am assuming that I would add the `useEffect()` in the .jsx files I want to use the wasm functionality in, correct?
> Also I added a catch() at the end as I had an error about the async/promise not having a catch. This I believe is because of the version of react that I am using.
> ```
> 
> ```
> useEffect(() => {
>     async function start() {
>         const wasm = await import('@emurgo/cardano-serialization-lib-browser').catch(console.error);
>     }
>     start();
>   }, []);
>   ```
> ```
> 
> I am not sure you are following the same repo, but I am trying to leverage the [Spacebudz](https://github.com/Berry-Pool/spacebudz/tree/3c5dd2b2dfb905d7649c9312563a2ab530867892/src/cardano) build of this, but make this work in my react app. Curious to your thoughts here.

This looks weird. This error happens if you try importing WASM dependencies using `import { } from 'my-module'`, but using the `await import('my-module')` it should work fine. Maybe there's somewhere else you are using the "regular" import syntax instead of the async one?

**Comment by lowkeyshift** [comment]
Ah, you are correct there were still some areas where I had files calling the normal way. Did you manage to get the Spacebudz code to work in your example? @pedromtcosta

**Comment by pedromtcosta** [comment]
I din't try the Spacebudz code actually, but the file you shared in your previous comment should work fine.

The useEffect is just an example, the important thing is that the module containing the WASM dependency is loaded asynchronously.
