### ISSUE TITLE
Bip32PrivateKey.to_raw_key, Bip32PrivateKey.to_public - Error: null pointer passed to rust

### ISSUE THREAD

**Issue by 34r7h** [Emurgo/cardano-serialization-lib#238]
Following up on #237, I think the docs are known, for quite some time, to be misleading. I followed an issue from February, #120 but still can't make sense of this problem. 

The class prototype has the methods. Is there a rust/wasm setup step somewhere? Perhaps another installation related soultion?

**package.json**
```
{
  "name": "serializer",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@emurgo/cardano-serialization-lib-asmjs": "^9.1.0",
    "@emurgo/cardano-serialization-lib-nodejs": "^9.1.0",
    "bech32": "^2.0.0",
    "ed25519-hd-key": "^1.2.0"
  },
  "type": "module"
}
```
**index.js**
```
import * as CW from "./node_modules/@emurgo/cardano-serialization-lib-asmjs/cardano_serialization_lib.js"
import {bech32} from 'bech32'

const okey = 'ed25519e_sk16rl5fqqf4mg27syjzjrq8h3vq44jnnv52mvyzdttldszjj7a64xtmjwgjtfy25lu0xmv40306lj9pcqpa6slry9eh3mtlqvfjz93vuq0grl80';
const prvKey = new CW.Bip32PrivateKey(bech32.decode(okey, 200));
console.log(
    prvKey.to_public.toString(), 
    Object.getOwnPropertyNames(
        Object.getPrototypeOf(prvKey)
    )
);

```
OUTPUT
```
to_public() {
        var ret = wasm.bip32privatekey_to_public(this.ptr);
        return Bip32PublicKey.__wrap(ret);
    } [
  'constructor',
  '__destroy_into_raw',
  'free',
  'derive',
  'to_128_xprv',
  'to_raw_key',
  'to_public',
  'as_bytes',
  'to_bech32',
  'chaincode'
]

file:///home/34r7h/serializer/node_modules/@emurgo/cardano-serialization-lib-asmjs/cardano_serialization_lib_bg.js:12145
    throw new Error(getStringFromWasm0(arg0, arg1));
          ^

Error: null pointer passed to rust
    at __wbindgen_throw (file:///home/34r7h/serializer/node_modules/@emurgo/cardano-serialization-lib-asmjs/cardano_serialization_lib_bg.js:12145:11)
    at wasm_bindgen__throw_str__hc7271211fb99102a (file:///home/34r7h/serializer/node_modules/@emurgo/cardano-serialization-lib-asmjs/cardano_serialization_lib.asm.js:357420:3)
    at wasm_bindgen____rt__throw_null__h7f1b1c9f753a0a7c (file:///home/34r7h/serializer/node_modules/@emurgo/cardano-serialization-lib-asmjs/cardano_serialization_lib.asm.js:357408:3)
    at Module.bip32privatekey_to_public (file:///home/34r7h/serializer/node_modules/@emurgo/cardano-serialization-lib-asmjs/cardano_serialization_lib.asm.js:327899:4)
    at Bip32PrivateKey.to_public (file:///home/34r7h/serializer/node_modules/@emurgo/cardano-serialization-lib-asmjs/cardano_serialization_lib_bg.js:1455:24)
    at file:///home/34r7h/serializer/index.js:24:29
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)

**Comment by 34r7h** [comment]
reference: https://github.com/rustwasm/wasm-bindgen/issues/166

**Comment by 34r7h** [comment]
Tested with browser wasm version, same errors

**Comment by 34r7h** [comment]
Maybe just dump support for Cardano and throw all resources at Ergo .)

**Comment by TenStrings** [comment]
I think you probably want to replace

`const prvKey = new CW.Bip32PrivateKey(bech32.decode(okey, 200));`

with something like 

`const prvKey = CW.Bip32PrivateKey.from_bech32(key);`

But also, I don't think that's a valid bip32 extended key, probably because it's missing the chain code. Maybe you actually wanted to use `PrivateKey`? I also think the hrp needs to be `xprv` for the extended one.

**Comment by 34r7h** [comment]
Thanks, good points. So PrivateKey doesn't have the from_bech method as expected from the docs. Was it removed for a reason?

**Comment by TenStrings** [comment]
No idea, probably by mistake? Maybe it was never there. I'm not a maintainer, I was just passing by. 

It wouldn't really be hard to add, in any case, but that's another issue.

You could also try decoding the bech32 string in js as you were trying to do, but I think you would need to get the words in base32 and convert them to a byte array first (and use `from_extended_bytes`).

**Comment by rooooooooob** [comment]
It doesn't look like we ever had it on the private key from looking at the git history. It's kind of weird since in the repo we borrowed the code from first it's there. I just made a PR #244 to address this.
