### ISSUE TITLE
ledgerjs-hw-app-cardano 4.0.0 contains a breaking change for CSL

### ISSUE THREAD

**Issue by Scitz0** [Emurgo/cardano-serialization-lib#240]
ledgerjs-hw-app-cardano 4.0.0 was officially released a week ago. This brings a couple of key changes, most importantly:

> validation of canonical ordering of cbor map keys compliant with [CIP 21](https://cips.cardano.org/cips/cip21) (withdrawals, token policy ids in outputs and mint, asset names within an asset group)

The validation of canonical ordering in ledgerjs first sort on asset name length, and secondly if equal length, string comparision.
Snippet of code validation done:
```
const sortedAssetNames = [...assetNamesHex].sort( (n1, n2) => {
  if (n1.length === n2.length) return n1.localeCompare(n2)
  else return n1.length - n2.length
})
validate(JSON.stringify(assetNamesHex) === JSON.stringify(sortedAssetNames), InvalidDataReason.MULTIASSET_INVALID_ASSET_GROUP_ORDERING)
```

This means that for three assets in the same policy called `AA`, `B` and `CC`, according to ledgerjs they should be sorted as `B > AA > CC`. But if you insert tokens in this order into a CSL Value object they are resorted as `AA > B > CC`. 

Due to the above, deployment of ledgerjs-hw-app-cardano 4.0.0 breaks compatibility with the current version of CSL. Ledgerjs 4.0.0 is mandatory for Ledger Cardano App 3.0.0 support already into the wild (albeit by mistake it seems, now pulled again). 

Can we get this issue prioretized?

**Comment by vsubhuman** [comment]
Thank you, @Scitz0 !

**Comment by vsubhuman** [comment]
Ok, @Scitz0, do you think then it would be enough for the `MultiAsset` to preserve the order of the asset names as they are being inserted, without forcing the new way of sorting?

**Comment by MarcelKlammer** [comment]
I also think, that sorting can be done by the lib user before inserting.

**Comment by Scitz0** [comment]
> Ok, @Scitz0, do you think then it would be enough for the `MultiAsset` to preserve the order of the asset names as they are being inserted, without forcing the new way of sorting?

Yip, this would be my preference.

**Comment by gitmachtl** [comment]
This is also related to https://github.com/vacuumlabs/cardano-hw-cli/issues/104
In that case cardano-cli is the "bad guy" that is not doing a proper sorting. Be aware of a changing txid when you do a rearrangement. So, the sorting should be done before generating many any txids out of it. Cardano-HW-CLI will have a new function in the future to sort txbodies before further processing, because IOG is refusing to do a proper sorting (https://github.com/input-output-hk/cardano-node/issues/2783)

**Comment by rooooooooob** [comment]
This is a part of a broader issue I think with canonical forms. Some of our types use btreemaps (lex order for canonical form but only when the keys are the same type and length) and others use the linkedhashmaps (insret order). Do we want to provide some functionality for explicitly serializing to canonical form, or just have that be the default?

**Comment by gitmachtl** [comment]
The sort should first happen by policyIDs. Inside of a policyID assetNames should be sorted by length and if they are the same length then they should be sorted lexicographically.

**Comment by vsubhuman** [comment]
> > Ok, @Scitz0, do you think then it would be enough for the `MultiAsset` to preserve the order of the asset names as they are being inserted, without forcing the new way of sorting?
> 
> Yip, this would be my preference.

This now ready in a PR, waiting for a review: https://github.com/Emurgo/cardano-serialization-lib/pull/243

@rooooooooob , @SebastienGllmt , @pedromtcosta , check plz when possible.

**Comment by rooooooooob** [comment]
**Why is preserving the order important if the node will only accept assets in canonical order?**

This is also related to many other issues since this isn't the only place that needs to be canonical form, although those are usually for hashing. And the fact that the cardano node used non-canonical forms in some places (indefinite lengths encodings) makes it even more of a complicated situation.

**Comment by Scitz0** [comment]
I'm fine with having CSL compliant with CIP-21 to deal with the sorting accordingly. My initial thought about preserving the order they are put in, was if this somehow un-complicated the implementation and put the burden on the implementer rather than forcing order in lib.

**Comment by vsubhuman** [comment]
@Scitz0 , let me try to get the fix for the ordering fat today then and we can release `9.1.1`, because `9.2` is now cancelled and planned as a major `10.0` release since we have a couple of breaking API changes there

**Comment by Scitz0** [comment]
> @Scitz0 , let me try to get the fix for the ordering quickly today then and we can release `9.1.1` right away, because `9.2` is now cancelled and planned as a major `10.0` release since we have a couple of breaking API changes there

Ok great, thanks 👌

**Comment by vsubhuman** [comment]
This fix is now available and will publish version 9.1.1 after getting a review approve on it: https://github.com/Emurgo/cardano-serialization-lib/pull/246

@rooooooooob @SebastienGllmt @pedromtcosta , check plz when possible.

**Comment by MarcelKlammer** [comment]
Thank you for reacting quickly. Much appreciated.

**Comment by vsubhuman** [comment]
New version is published:
- https://www.npmjs.com/package/@emurgo/cardano-serialization-lib-browser/v/9.1.1
- https://www.npmjs.com/package/@emurgo/cardano-serialization-lib-nodejs/v/9.1.1
- https://www.npmjs.com/package/@emurgo/cardano-serialization-lib-asmjs/v/9.1.1

**Comment by MarcelKlammer** [comment]
Compiled for web target, implemented and tested against 

"@cardano-foundation/ledgerjs-hw-app-cardano": "^4.0.0"

All fine. Thanks again.
