### ISSUE TITLE
Issue with the CIP2 random-improve coin-selection when small inputs and need to calculate change

### ISSUE THREAD

**Issue by vsubhuman** [Emurgo/cardano-serialization-lib#252]
The CIP2 coin-selection been added in this PR: https://github.com/Emurgo/cardano-serialization-lib/pull/232

See this fix for the random-improve test case where all amounts been multiplied by ten: https://github.com/Emurgo/cardano-serialization-lib/pull/251/commits/28f0988f3f387671a19aa07bc04a6b940bb60c1d#diff-67896f615f1e60f7474eb6194c0614a005522dc35fb07046855d77260954b972R2080-R2092

Without this fix, after there was a change to the minimum required coin calculation which made it impossible to just set the required number to `1` for test purposes, the test started failing **incosistently** with the `"Insufficient input in transaction"` error. And the reason for that is that random-improve branch of the coin selection works on the per-output basis and does not address the required fees explicitly.

You can see here that the fee for any new added input is being added to the `total_output` - https://github.com/Emurgo/cardano-serialization-lib/blob/28f0988f3f387671a19aa07bc04a6b940bb60c1d/rust/src/tx_builder.rs#L217

But then that `total_output` value is not used anywhere, there are only two loops going over outputs. So test was failing inconsistently because sometimes the random selection would get enough input to cover the fees, but sometimes, it doesn't.

**Comment by vsubhuman** [comment]
The issue can be reproduced by changing the amounts in that test case back to what it was before, or adjusting them in a way that it will always fail.

**Comment by vsubhuman** [comment]
@rooooooooob , here I have created a test case that fails consistently because there are three similar small available inputs, where two of them are enough to cover the output, but not enough to cover the output and the fee increased by adding these two inputs. Three of them would be enough to cover the output and the fees. But only two get added.

https://github.com/Emurgo/cardano-serialization-lib/pull/254

**Comment by vsubhuman** [comment]
@pedromtcosta , can you plz look into this? Maybe we can do the fix if you will have some time available

**Comment by pedromtcosta** [comment]
> @pedromtcosta , can you plz look into this? Maybe we can do the fix if you will have some time available
> 
> You can work right from this branch: #254 , to have the test right there

@vsubhuman I pushed some changes to this PR. Could you review them please?
