### ISSUE TITLE
nodejs wasm bundle fails to instantiate

### ISSUE THREAD

**Issue by shroomist** [Emurgo/cardano-serialization-lib#257]
I'm not using webpack or anything fancy.
just copying `wasm` file by hand where my index.mjs lives

```js
import {  readFileSync } from 'fs'
const buf = readFileSync('./cardano_serialization_lib_bg.wasm')

WebAssembly.instantiate(buf, {}).then(obj => {
  console.log(obj.instance.exports)
})
```

which fails with
```
UnhandledPromiseRejectionWarning: TypeError: WebAssembly.instantiate(): Import #0 module="__wbindgen_placeholder__" error: module is not an object or function
```

I'm simply not sure if anybody is using the nodejs package and how.
As far as I can tell above should be working, I've tested against node12 and node14

**Comment by shroomist** [comment]
Although I'm able to use it the regular way of importing the module.  🤦 
maybe we're just missing some more examples

**Comment by CyberCyclone** [comment]
It's a pity you didn't get this figured out. Not every framework supports wasm unfortunately so the typical `import` doesn't always work. Without any documentation on what need to be imported it's a lot of trial and error.

**Comment by ozgrakkurt** [comment]
The reason might be, that wasm file isn't really intended to be used directly. Instead normal import is expected to be used. wasm file is generated by wasm_bindgen

**Comment by CyberCyclone** [comment]
There's a lot of frameworks that doesn't support wasm via an import statement and there's suggestions that using wasm directly is the only way to get it to work without using the asm (full JS) implementation. 

https://developer.mozilla.org/en-US/docs/WebAssembly/Loading_and_running
