### ISSUE TITLE
Fee calculation problem on the test net

### ISSUE THREAD

**Issue by ypopovych** [Emurgo/cardano-serialization-lib#260]
Hi.

We are working on Cardano Swift wrappers and have an issue with submitting transactions on the test net. Seems as it calculates lesser fees than needed.

What we are doing:
1. Initialize TxBuilder with parameters 
```
linearFee: (constant: 155381, coefficient: 44)
poolDeposit: 500000000
keyDeposit: 2000000,
maxValueSize: 5000,
maxTxSize: 16384,
coinsPerUtxoWord: 34482
```
2. Add one output
```
TransactionOutput(address:"addr_test1qp5pud5nkx94drjk5f94qdd2u97p7x5apj359dy3d6xxzlac4rwdulp233ujjmc09g446unlhtt0ekdqds2t2qccxxmsf0s33a",  amount: 10000000)
```
3. Set TTL to `42792780`
4. Add UTXOs with `add_input_from` method and `LargerFirst` strategy.
5. Add change with `add_change_if_needed` with address: `addr_test1qrshw78yf3xcw3tz20hpj34a65ac4qx4uh24uvg9n9e7pedc4rwdulp233ujjmc09g446unlhtt0ekdqds2t2qccxxmsteww6y`
6. Calculated fee is `168317`

It creates a Transaction:
```
Inputs: ("0x18f9b26c2d03bd9dedb97d4f40cef00f807ae41f513131089d90ae07e1be7193", 1)
Outputs: 
("addr_test1qp5pud5nkx94drjk5f94qdd2u97p7x5apj359dy3d6xxzlac4rwdulp233ujjmc09g446unlhtt0ekdqds2t2qccxxmsf0s33a", 10000000)
("addr_test1qrshw78yf3xcw3tz20hpj34a65ac4qx4uh24uvg9n9e7pedc4rwdulp233ujjmc09g446unlhtt0ekdqds2t2qccxxmsteww6y", 608765447)
TTL: 42792780
Fee: 168317
```
And we get an error on submitting: `FeeTooSmallUTxO (Coin 350345) (Coin 168317)`.

Are we doing something wrong?

Thanks,
Yehor

**Comment by vsubhuman** [comment]
HI, @ypopovych ! That's a bit weird, cuz `168317` looks good to me for a tx like that, not sure why the node would request fee `350345` tbh

**Comment by vsubhuman** [comment]
If you think it might be an error in the serlib fee calculation - gon be great if you can create a branch with a testcase that shows how the tx-builder is all created and prepared and the shows the fee is not what's expected. But then again - I wouldn't spend time on that cuz rather the expectation of `350345` looks weird to me

**Comment by vsubhuman** [comment]
Which node you are using that it returns you this estimation? Linear fee parameters defo look good to me, same as what we are using in Yoroi for the testnet:
```
LinearFee: {
  coefficient: '44',
  constant: '155381',
},
```

**Comment by ypopovych** [comment]
We use Blockfrost test net API for our tests.

**Comment by ypopovych** [comment]
We found the problem on our side. We had a bug in address filtering, so TX was signed by more keys than needed. And node calculated different fees because of this.
