### ISSUE TITLE
Vue3 + Vite fails to import

### ISSUE THREAD

**Issue by kinqsley** [Emurgo/cardano-serialization-lib#265]
Hello, I am trying to get this lib import for [Vite](https://vitejs.dev/)

```
import init, { wasm } from '@emurgo/cardano-serialization-lib-browser/cardano_serialization_lib';
```

But i was facing the error as follows:

![image](https://user-images.githubusercontent.com/22793808/142804943-6e5e450e-78d7-49f4-a7c4-267f820d50be.png)

Does anyone have idea how to import the lib for Vite & Vue3?

**Comment by a01410207** [comment]
Did you find any solution for this?

**Comment by Koutelier** [comment]
@emurgo/cardano-serialization-lib-browser
this doesn't work with vite?

**Comment by radflipper** [comment]
I worked with this for awhile and was never able to get it to work correctly the way the Vite docs say it should. I think there's something different about the way the project is set up and the newer method for loading the WASM that vite is calling. IDK anyways there is a non-wasm js package that you can use with Vite if you're willing to give up on the WASM for now, alternatively it does work with webpack and I've done that successfully with Vue.

**Comment by lisicky** [comment]
It should help https://www.npmjs.com/package/vite-plugin-wasm
