### ISSUE TITLE
Difference in cborHex reprensatation of a Plutus script

### ISSUE THREAD

**Issue by AlainMgz** [Emurgo/cardano-serialization-lib#268]
Hey,

When interacting with scripts via cli we need to compile the validator to .plutus code, which is in cborHex (using [this](https://github.com/OnChainLabs/Martify/blob/main/app/market-plutus.hs) for instance).

When interacting with scripts via `cardano-serialization-lib` we also need this cborHex. It is used in the construction of a `PlutusScript` object like so :
```javascript
const scripts = Cardano.Instance.PlutusScripts.new();

scripts.add(Cardano.Instance.PlutusScript.new(fromHex(<cborHex>)));
```
 but copying the cborHex used before does not work. The tx will fail saying there is a missing witness for the said script. The right cborHex to use for `cardano-serialization-lib` is the one displayed by [cardano-scan](https://testnet.cardanoscan.io/transaction/5fbbe979324d68d9e6122384d279d4ebda407dc609017ea53a1c7dbfb7c3eb78?tab=contracts) under the Contracts tab.

My questions are why is there a difference between these two cbor representations of the same script, and how can we obtain the right one to use in `cardano-serialization-lib` without having to unlock something from the script via the cli. Because it is sometimes impossible to do so :

Let's say we have a parameterized script, with a pkh as param.
This pkh is the only pkh allowed to interact with the script and we want it to be a Nami pkh.
Therefore we cannot spend from script to get the right cbor since we cannot sign the tx from a Nami wallet in cli.

It would make sense if we could just use the cborHex compiled for cli. Thanks for any insight on this.

**Comment by Mercurial** [comment]
I also had this issue

**Comment by jfischoff** [comment]
I've found removing the first three bytes from the cbor bytes generated by `cardano-cli` works as well.

**Comment by vsubhuman** [comment]
Hi! Can you guys post an example of a script from CLI that does not work?

**Comment by jfischoff** [comment]
https://github.com/Canonical-LLC/revenue-sharing/blob/main/scripts/mainnet/revenue-sharing.plutus#L4

**Comment by mailtodanish** [comment]
> ad this issue and indeed tried the recommended solution and seems to have wo

let me know solution. I am also facing different hash so not able to unlock

**Comment by rooooooooob** [comment]
@mailtodanish can you post the hex CBOR of the script you are trying to unlock and what the two hashes are?

**Comment by rooooooooob** [comment]
Everyone, just use `PlutusScript.from_bytes()` instead of `PlutusScript.new()` if you are constructing it from the `"cborBytes"` from the cardano-cli.

I made a PR #336 that documents this so in the future there is no confusion.

**Comment by vsubhuman** [comment]
After some more looking into this, it turned out that compiler of the Plutus scripts for some reason appends two cbor tags to it, instead of one, e.g.

```
590e52590e4f010000332333222332233322233223233223322323233322232333222323333333322222222323332223233332222323233223232333222323233223322323233333222223322332233223322332233222232323232232232325335303333300b333357.......
```

this is a CBOR structure like:

```
59 0e52
590e4f010000332333222332233322233223233223322323233322232333222323333333322222222323332223233332222323233223232333222323233223322323233333222223322332233223322332233222232323232232232325335303333300b333357
```

Tag 59 means type `bytes` and the length 3666, followed by the payload. But the problem is that payload itself is also cbor encoded for whatever misterious reason:

```
59 0e4f
010000332333222332233322233223233223322323233322232333222323333333322222222323332223233332222323233223232333222323233223322323233333222223322332233223322332233222232323232232232325335303333300b333357
```

Tag 59 for `bytes` and the length 3663, without the 3 bytes of the first tag.

![image](https://user-images.githubusercontent.com/5585355/154497480-b87334c0-0719-4b9e-9695-f5de5c15b8dc.png)

No idea why that is needed. But yeah, calling `PlutusScript.from_bytes(...)` makes it to go through the deserializer, which removes the first tag via `raw.bytes()?`.

> I've found removing the first three bytes from the cbor bytes generated by `cardano-cli` works as well.

Doing the tag removing manually like this by a hardcoded number of bytes is dangerous, cuz cbor can take different number of bytes for a tag, depending on the script length, e.g. the "always true" script looks like this:

```
4e4d01000033222220051200120011
```

The two tags, in this case, are `4e` and `4d`, 1 byte each.

**Comment by tas2017** [comment]
> After some more looking into this, it turned out that compiler of the Plutus scripts for some reason appends two cbor tags to it, instead of one, e.g.
> 
> ```
> 590e52590e4f010000332333222332233322233223233223322323233322232333222323333333322222222323332223233332222323233223232333222323233223322323233333222223322332233223322332233222232323232232232325335303333300b333357.......
> ```
> 
> this is a CBOR structure like:
> 
> ```
> 59 0e52
> 590e4f010000332333222332233322233223233223322323233322232333222323333333322222222323332223233332222323233223232333222323233223322323233333222223322332233223322332233222232323232232232325335303333300b333357
> ```
> 
> Tag 59 means type `bytes` and the length 3666, followed by the payload. But the problem is that payload itself is also cbor encoded for whatever misterious reason:
> 
> ```
> 59 0e4f
> 010000332333222332233322233223233223322323233322232333222323333333322222222323332223233332222323233223232333222323233223322323233333222223322332233223322332233222232323232232232325335303333300b333357
> ```
> 
> Tag 59 for `bytes` and the length 3663, without the 3 bytes of the first tag.
> 
> ![image](https://user-images.githubusercontent.com/5585355/154497480-b87334c0-0719-4b9e-9695-f5de5c15b8dc.png)
> 
> No idea why that is needed. But yeah, calling `PlutusScript.from_bytes(...)` makes it to go through the deserializer, which removes the first tag via `raw.bytes()?`.
> 
> > I've found removing the first three bytes from the cbor bytes generated by `cardano-cli` works as well.
> 
> Doing the tag removing manually like this by a hardcoded number of bytes is dangerous, cuz cbor can take different number of bytes for a tag, depending on the script length, e.g. the "always true" script looks like this:
> 
> ```
> 4e4d01000033222220051200120011
> ```
> 
> The two tags, in this case, are `4e` and `4d`, 1 byte each.
> 
> So what the script compiler produces is not just a serialized cbor structure, but a serialized cbor wrapper over a serialized cbor structure. And the `PlutusScript` type matches that.

59077e59077b01000033232323232323232323232323232332232323232223222323253353330073333573466e1cd55cea802a40004642460020046eb4d5d09aab9e500623263533573803603203002e6eb4010cccd5cd19b8735573aa004900011991091980080180119191919191919191919191999ab9a3370e6aae754029200023333333333222222222212333333333300100b00a009008007006005004003002335015232323333573466e1cd55cea8012400046644246600200600460406ae854008c068d5d09aba2500223263533573805605205004e26aae7940044dd50009aba1500a33501501635742a012666aa030eb9405cd5d0a804199aa80c3ae501735742a00e66a02a0406ae854018cd4054cd5408c085d69aba150053232323333573466e1cd55cea801240004664424660020060046464646666ae68cdc39aab9d5002480008cc8848cc00400c008cd4099d69aba150023027357426ae8940088c98d4cd5ce01781681601589aab9e5001137540026ae854008c8c8c8cccd5cd19b8735573aa004900011991091980080180119a8133ad35742a004604e6ae84d5d1280111931a99ab9c02f02d02c02b135573ca00226ea8004d5d09aba2500223263533573805605205004e26aae7940044dd50009aba1500433501575c6ae85400ccd4054cd5408dd710009aba15002301d357426ae8940088c98d4cd5ce01381281201189aba25001135744a00226ae8940044d5d1280089aba25001135744a00226ae8940044d5d1280089aab9e5001137540026ae854008c8c8c8cccd5cd19b875001480188c848888c010014c060d5d09aab9e500323333573466e1d40092004232122223002005301a357426aae7940108cccd5cd19b875003480088c848888c004014c058d5d09aab9e500523333573466e1d40112000232122223003005375c6ae84d55cf280311931a99ab9c02202001f01e01d01c01b135573aa00226ea8004d5d09aba2500223263533573803603203002e2030264c6a66ae712410350543500018017135573ca00226ea80044dd50008919118011bac001320013550142233335573e0024a012466a01060086ae84008c00cd5d100100991919191999ab9a3370e6aae75400d20002333222123330010040030023232323333573466e1cd55cea80124000466442466002006004602a6ae854008cd4038050d5d09aba2500223263533573803403002e02c26aae7940044dd50009aba150033335500775ca00c6ae854008cd4029d71aba135744a004464c6a66ae7005805004c0484d5d1280089aab9e500113754002266aa002eb9d6889119118011bab00132001355012223233335573e0044a010466a00e66aa028600c6aae754008c014d55cf280118021aba200301213574200222440042442446600200800624464646666ae68cdc3a800a40004642446004006600a6ae84d55cf280191999ab9a3370ea0049001109100091931a99ab9c01201000f00e00d135573aa00226ea80048c8c8cccd5cd19b8735573aa004900011991091980080180118029aba15002375a6ae84d5d1280111931a99ab9c00f00d00c00b135573ca00226ea80048c8cccd5cd19b8735573aa002900011bae357426aae7940088c98d4cd5ce00680580500489baa00112232323333573466e1d400520042122200123333573466e1d40092002232122230030043006357426aae7940108cccd5cd19b87500348000848880088c98d4cd5ce00800700680600580509aab9d5001137540024646666ae68cdc3a800a4004424400446666ae68cdc3a801240004244002464c6a66ae7003002802402001c4d55ce9baa001232323232323333573466e1d4005200c21222222200323333573466e1d4009200a21222222200423333573466e1d400d2008233221222222233001009008375c6ae854014dd69aba135744a00a46666ae68cdc3a8022400c4664424444444660040120106eb8d5d0a8039bae357426ae89401c8cccd5cd19b875005480108cc8848888888cc018024020c030d5d0a8049bae357426ae8940248cccd5cd19b875006480088c848888888c01c020c034d5d09aab9e500b23333573466e1d401d2000232122222223005008300e357426aae7940308c98d4cd5ce00a00900880800780700680600580509aab9d5004135573ca00626aae7940084d55cf280089baa0012323232323333573466e1d400520022333222122333001005004003375a6ae854010dd69aba15003375a6ae84d5d1280191999ab9a3370ea0049000119091180100198041aba135573ca00c464c6a66ae7003402c0280240204d55cea80189aba25001135573ca00226ea80048c8c8cccd5cd19b875001480088c8488c00400cdd71aba135573ca00646666ae68cdc3a8012400046424460040066eb8d5d09aab9e500423263533573801401000e00c00a26aae7540044dd50008891119191999ab9a3370e6aae754009200023355009300635742a004600a6ae84d5d1280111931a99ab9c00a008007006135573ca00226ea8005261200111221233001003002491035054310011232300100122330033002002001332222232533500110061335738920112636f646520646964206e6f74206d617463680000532333573466e1c00400c018014d400c8004488008488005

How would I remove bytes here to make it acceptable by Plutus?
