### ISSUE TITLE
help, Vkeywitnesses

### ISSUE THREAD

**Issue by qichalerm** [Emurgo/cardano-serialization-lib#288]
Hello, I'm  studying this mint nft example. do you have an example of creating Vkeywitnesses?  Thank.

```
  const witnesses = Loader.Cardano.TransactionWitnessSet.new()
  witnesses.set_native_scripts(nativeScripts)
  
  const dummyVkeyWitness ="8258208814c250f40bfc74d6c64f02fc75a54e68a9a8b3736e408d9820a6093d5e38b95840f04a036fa56b180af6537b2bba79cec75191dc47419e1fd8a4a892e7d84b7195348b3989c15f1e7b895c5ccee65a1931615b4bdb8bbbd01e6170db7a6831310c";
  
  const vkeys = Loader.Cardano.Vkeywitnesses.new();
  vkeys.add(
     Loader.Cardano.Vkeywitness.from_bytes(
         Buffer.from(dummyVkeyWitness, "hex")
     )
  )
  witnesses.set_vkeys(vkeys);
```

**Comment by eric248550** [comment]
Where can I find this example?

**Comment by qichalerm** [comment]
@eric248550 
https://github.com/cheffNFT/twitternfts

**Comment by vsubhuman** [comment]
> Hello, I'm studying this mint nft example. do you have an example of creating Vkeywitnesses?

Hi, @qichalerm. You can check how Yoroi produces transaction witnesses here: https://github.com/Emurgo/yoroi-frontend/blob/f1affc9f90efdce2c5b7078b80a3add97d9499a3/packages/yoroi-extension/app/api/ada/transactions/shelley/transactions.js#L1277-L1281

**Comment by qichalerm** [comment]
Hi, @vsubhuman 
Do you have a sample create? Private key? for nami wallet
Thank.

const utxos = (await window.cardano.getUtxos()).map((utxo) =>
        Loader.Cardano.TransactionUnspentOutput.from_bytes(Buffer.from(utxo, "hex"))
)
const txhash = Loader.Cardano.hash_transaction(rawTxBody)
// make_vkey_witness 
// private key

**Comment by qichalerm** [comment]
Hi,
How can I restore Ed25519KeyHash ? 
Thank.

const address = Buffer.from((await window.cardano.getUsedAddresses())[0], "hex")
const paymentKeyHash = Loader.Cardano.BaseAddress.from_address(
        Loader.Cardano.Address.from_bytes(address)
    )
    .payment_cred()
    .to_keyhash()

**Comment by qichalerm** [comment]
got key hash. I don't know right?, but registered via pool.pm Not Found ? Thank🙏

- nami wallet 

`
const address = Buffer.from((await window.cardano.getUsedAddresses())[0], "hex")
const paymentKeyHash = Loader.Cardano.BaseAddress.from_address(
    Loader.Cardano.Address.from_bytes(address)
)
  .payment_cred()
  .to_keyhash()

const nativeScripts = Loader.Cardano.NativeScripts.new()
const script = Loader.Cardano.ScriptPubkey.new(paymentKeyHash) 
const nativeScript = Loader.Cardano.NativeScript.new_script_pubkey(script)
const lockScript = Loader.Cardano.NativeScript.new_timelock_expiry(
  Loader.Cardano.TimelockExpiry.new(ttl)
)

nativeScripts.add(nativeScript)
nativeScripts.add(lockScript)
const finalScript = Loader.Cardano.NativeScript.new_script_all(
  Loader.Cardano.ScriptAll.new(nativeScripts)
)
const policyId = Buffer.from(finalScript.hash(0).to_bytes()).toString('hex')

//-------- script , key hash
const getkeyhash =
Buffer.from(Loader.Cardano.StakeCredential.from_keyhash(paymentKeyHash).to_keyhash().to_bytes()).toString('hex') 
`

`
const witnesses = Loader.Cardano.TransactionWitnessSet.new()
witnesses.set_native_scripts(nativeScripts)
const txhash = Loader.Cardano.hash_transaction(rawTxBody)
const vkeyWit =  Loader.Cardano.make_vkey_witness(
                    txhash, 
                    Loader.Cardano.PrivateKey.from_normal_bytes(
   Loader.Cardano.StakeCredential.from_keyhash(
       paymentKeyHash
   ).to_bytes()
)
                )
const vkeys = Loader.Cardano.Vkeywitnesses.new();
vkeys.add(vkeyWit)
vkeys.add(vkeyWit)
witnesses.set_vkeys(vkeys);

const rawTx = Loader.Cardano.Transaction.new(
   rawTxBody,
   witnesses,
   aux_data
)
`

**Comment by bolajahmad** [comment]
any reason why i have to add the vkeyWit twice???

vkeys.add(vkeywit)
vkeys.add(vkeywit)
