### ISSUE TITLE
NFT. how can get key hash

### ISSUE THREAD

**Issue by qichalerm** [Emurgo/cardano-serialization-lib#289]
Hi, 🙏
I am using Nami wallet mint nft and cardano-serialization-lib.
When I show policy.script value , I get an object with only attribute is something called "ptr",  I want to know how can I get the "policy.script keyshash"

Thank

**Comment by vsubhuman** [comment]
@qichalerm , check here:

https://github.com/Emurgo/cardano-serialization-lib/blob/15bd42ec3d1a181f78c56afe48a864e5782ddd42/rust/src/tx_builder.rs#L739

**Comment by vsubhuman** [comment]
Or do you mean you want to get the embedded address key that is needed for signing?

**Comment by qichalerm** [comment]
hi, @vsubhuman 
I want to use in the configuration time lock. 
example.
![Screenshot_20211213-181413_Chrome](https://user-images.githubusercontent.com/27846492/145802821-ff0ca712-f95e-4ee9-92c4-1e859b40f699.jpg)

**Comment by qichalerm** [comment]
> 

okay,  thank
