### ISSUE TITLE
ExUnits on Reedemers.

### ISSUE THREAD

**Issue by waalge** [Emurgo/cardano-serialization-lib#292]
I don't understand ExUnits and I don't understand how people find the numbers they do (eg [spacebudz][2]).

I had an issue  with submission error `ExUnitsTooBigUTxO`. 
I dropped the units on the [redeemer][1] the Tx was submitted successfully. 
But it was pretty arbitrary. 

What, if any, is the relationship between these ExUnits and those use to compute the script fee? 
How do I know the right numbers?

If anyone can signpost docs that explain how to join the dots between the protocol parameters and fees, I'd be very grateful. 

[1]: https://github.com/Emurgo/cardano-serialization-lib/blob/efaa6dde55f2971186d29622f60e285e5285ff71/rust/src/plutus.rs#L484
[2]:  https://github.com/Berry-Pool/spacebudz/blob/299c936d8c77f4a55e203a448b0262494c94d627/src/cardano/market/index.js#L119

**Comment by Karakatiza666** [comment]
To whoever comes across:
I got this error when I created two redeemers, and gave each maxTxExMem and maxTxExSteps.
In my case, I needed to allocate resources to each redeemer inversely proportional to their total number, e.g.:
const redeemerQty = 2
insertRedeemer(0, maxTxExMem / redeemerQty, maxTxExSteps / redeemerQty)
insertRedeemer(1, maxTxExMem / redeemerQty, maxTxExSteps / redeemerQty)
