### ISSUE TITLE
Error converting Bech32 address to Key Hash

### ISSUE THREAD

**Issue by rumourscape** [Emurgo/cardano-serialization-lib#294]
```javascript
const paymentKeyHash = Loader.Cardano.BaseAddress.from_address(
      Loader.Cardano.Address.from_bech32('addr_test1vr6se86ucxts7dcnmh6a7xk68au7rrxm8gd7eekd4w44x5c026zfc')
    ).payment_cred().to_keyhash();
```

It gives me this error:
```error
TypeError: Cannot read properties of undefined (reading 'payment_cred')
```

How can I fix this or is there any other way to create Ed25519KeyHash from a bech32 address.

**Comment by rooooooooob** [comment]
@rumourscape It looks like you have an enterprise one not a base address - which is why `BaseAddress.from_address()` is returning `undefined`. Try swapping it out for `EnterpriseAddress.from_address()` and it should work.

**Comment by rumourscape** [comment]
Thanks, that worked.
