### ISSUE TITLE
asmjs takes 17s to calculate txBuilder.min_fee()

### ISSUE THREAD

**Issue by honungsburk** [Emurgo/cardano-serialization-lib#328]
I've experienced performance issues using the asmjs of the library. Profiling my own code I noticed that `txBuilder.min_fee()` takes roughly ~17s to execute (this is using v9.1.4). I saw that some work has already been put into trying to resolve this issue, namely #213 and #214. Reading #323 I believe these changes to already been merged but perhaps the problem persists? Are there any other improvements that are yet to be merged?

**Comment by vsubhuman** [comment]
Best improvement for that is switching to the WASM version if possible https://www.npmjs.com/package/@emurgo/cardano-serialization-lib-browser

**Comment by honungsburk** [comment]
Yeah, that sounds like a good solution
