### ISSUE TITLE
Add to_json on transactions

### ISSUE THREAD

**Issue by SebastienGllmt** [Emurgo/cardano-serialization-lib#34]
I'm not sure what are the implications of doing this (maybe for some reason it gets really ugly), but the old Byron WASM bindings has a `to_json` function on transactions. This was very useful for quick debugging.

**Comment by stephenhuh** [comment]
i would definitely love to see this

**Comment by vsubhuman** [comment]
https://github.com/Emurgo/cardano-serialization-lib/pull/345
