### ISSUE TITLE
TransactionBuilderConfigBuilder null pointer passed to rust 10.0.0-beta.9

### ISSUE THREAD

**Issue by AdamMachera** [Emurgo/cardano-serialization-lib#344]
When I try to create TransactionBuilderConfigBuilder in version 10.0.0-beta.9

``` var configBuilder = new TransactionBuilderConfigBuilder()
        .fee_algo(
            LinearFee.new
                (
                    BigNum.from_str(protocolParams.min_fee_a.toString()), 
                    BigNum.from_str(protocolParams.min_fee_b.toString())
                )
        )
        .pool_deposit(BigNum.from_str(protocolParams.pool_deposit.toString()))
        .key_deposit(BigNum.from_str(protocolParams.key_deposit.toString()))
        .coins_per_utxo_word(BigNum.from_str(protocolParams.coins_per_utxo_word))
        .max_value_size(Number.parseInt(protocolParams.max_val_size))
        .max_tx_size(protocolParams.max_tx_size)
        .prefer_pure_change(true)
        .build()
```

I'm getting null pointer passed to rust.

**Comment by edu-d-rai** [comment]
Hi, are you still having this issue?
`let txConfigBuilder = S.TransactionBuilderConfigBuilder.new();
    const feealgo = S.LinearFee.new(
      S.BigNum.from_str(protocolParameters.linearFee.minFeeA),
      S.BigNum.from_str(protocolParameters.linearFee.minFeeB)
    );
    txConfigBuilder = txConfigBuilder.fee_algo(feealgo);
    txConfigBuilder = txConfigBuilder.coins_per_utxo_word(
      S.BigNum.from_str(protocolParameters.coinsPerUtxoWord)
    );
    txConfigBuilder = txConfigBuilder.pool_deposit(
      S.BigNum.from_str(protocolParameters.poolDeposit)
    );
    txConfigBuilder = txConfigBuilder.key_deposit(
      S.BigNum.from_str(protocolParameters.keyDeposit)
    );
    txConfigBuilder = txConfigBuilder.max_value_size(
      protocolParameters.maxValSize
    );
    txConfigBuilder = txConfigBuilder.max_tx_size(protocolParameters.maxTxSize);
    const txConfig = txConfigBuilder.build();`
    I did this and it worked...super ugly, but yeah...

**Comment by vsubhuman** [comment]
> I'm getting null pointer passed to rust.

Can you check in which line you are getting the error and then how do you pass the parameter in that line?

e.g. 

```
.coins_per_utxo_word(BigNum.from_str(protocolParams.coins_per_utxo_word))
.max_value_size(Number.parseInt(protocolParams.max_val_size))
.max_tx_size(protocolParams.max_tx_size)
```

- Are you making sure `protocolParams.coins_per_utxo_word` exists?
- `protocolParams.max_val_size` is parsed into int, but `protocolParams.max_tx_size` isn't for some reason

**Comment by AdamMachera** [comment]
Please try using 
```
TransactionBuilderConfigBuilder.new()
        .fee_algo(
```
instead of 
```
new TransactionBuilderConfigBuilder()
        .fee_algo(
```

**Comment by vsubhuman** [comment]
> Please try using
> 
> ```
> TransactionBuilderConfigBuilder.new()
>         .fee_algo(
> ```
> 
> instead of
> 
> ```
> new TransactionBuilderConfigBuilder()
>         .fee_algo(
> ```

@AdamMachera , I am not sure I understand what you mean by this comment and whether yu still experiencing the problem.

```
TransactionBuilderConfigBuilder.new()
```

This is the only correct way to instantiate WASM types, if you are using this approach there should be no issues happening if you are passing all the arguments to the builder methods correctly.

**Comment by vsubhuman** [comment]
Reopen the issue with a proper example and explanation in case you still experiencing problems
