### ISSUE TITLE
Bug introduced in 9.1.3 - transaction metadata cannot be deserialized if null is passed for it.

### ISSUE THREAD

**Issue by 0xtrossets** [Emurgo/cardano-serialization-lib#346]
Submitting transaction with cardano-rosetta,

9.1.3 causes an issue when a transaction is built with no metadata and that transaction is submitted.

**Comment by rooooooooob** [comment]
@0xtrossets can you post the CBOR (as a hex string) that you are trying to submit?

It's weird since we have the Alonzo binary spec defined as
```
transaction =
  [ transaction_body
  , transaction_witness_set
  , bool
  , auxiliary_data / null
  ]
```
which should allow a null. This part of the code hasn't changed in a few months at least but it's possible that cardano-rosetta/cardano-node was modified and someone forgot to update the binary spec to match it, which has happened once before, coincidentally with the same `transaction` part when they added that `bool` field.

**Comment by 0xtrossets** [comment]
@rooooooooob 
Here is the request body to Rosetta:
```json
{
"signed_transaction":"8179036438346134303038313832353832303739636535666264343963313938653566333663373263363462353336343636356536336433313662643264323762363766396463643432323961363232333030323031383638323538316437306337363766613231373433646464623765656466613139663763376636303762653736373663333038333938323664663166643735643861316230303030303031373438373665383030383235383164373062643532386136373936633936376564356466323463383832396534376636313739636635303435613764643831613632663535616366383162303030303030326539306564643030303832353831643730656235623834666463666563616637626334323764336664373433333333323434643334653130623539303566363038393465396634636131623030303030303435643936346238303038323538316437303238353561383561633234633463373833386466383837663032643035656435616631303530326662386432316633303833643733343363316230303030303035643231646261303030383235383164373065316231356466353536323065303665333139393837383661363533633231303865363361633164313436386337316564343965333764353162303030303030373436613532383830303832353833393030386363633136306334616432303938393734313339326635316235663736336431623163356632343937633339313866376166323735643437343066336334613863656134643237653536333164383637653462343864656130666465653239313363663438643533643337323834393162303038363830316165633163323338303032316130303066343234303033316130326339663866336131303038313832353832303661316633636363353265663364633137663730373566313932396466623865346438653266353430343639343033633665663637613034656431613162643135383430646637363262333366326338306361663636343866333662353637323831393564376538643166626461383235346632656238653537353966663231663664386462383534636161313230393939386433643339316430303434393134396562393633646630623165646634366337306131323661303637333462383637306366356636",
"network_identifier":
    {"blockchain":"cardano","network":"42"}
}
```

Actually I think the bug was introduced in either 9.1.1 or 9.1.2

**Comment by vsubhuman** [comment]
> Here is the request body to Rosetta:
> 
> ```json
> {
> "signed_transaction":"8179036438346134303038313832353832303739636535666264343963313938653566333663373263363462353336343636356536336433313662643264323762363766396463643432323961363232333030323031383638323538316437306337363766613231373433646464623765656466613139663763376636303762653736373663333038333938323664663166643735643861316230303030303031373438373665383030383235383164373062643532386136373936633936376564356466323463383832396534376636313739636635303435613764643831613632663535616366383162303030303030326539306564643030303832353831643730656235623834666463666563616637626334323764336664373433333333323434643334653130623539303566363038393465396634636131623030303030303435643936346238303038323538316437303238353561383561633234633463373833386466383837663032643035656435616631303530326662386432316633303833643733343363316230303030303035643231646261303030383235383164373065316231356466353536323065303665333139393837383661363533633231303865363361633164313436386337316564343965333764353162303030303030373436613532383830303832353833393030386363633136306334616432303938393734313339326635316235663736336431623163356632343937633339313866376166323735643437343066336334613863656134643237653536333164383637653462343864656130666465653239313363663438643533643337323834393162303038363830316165633163323338303032316130303066343234303033316130326339663866336131303038313832353832303661316633636363353265663364633137663730373566313932396466623865346438653266353430343639343033633665663637613034656431613162643135383430646637363262333366326338306361663636343866333662353637323831393564376538643166626461383235346632656238653537353966663231663664386462383534636161313230393939386433643339316430303434393134396562393633646630623165646634366337306131323661303637333462383637306366356636",
> "network_identifier":
>     {"blockchain":"cardano","network":"42"}
> }
> ```

@0xtrossets , the provided hex string is not really a correct serialized version of a `Transaction` anyway, it's an array of length 1, with the element of type `text`

![image](https://user-images.githubusercontent.com/5585355/154417963-69f48c99-18bc-469d-8678-c8f2863bb946.png)

The text encoded within that single array element is: 

```
84a4008182582079ce5fbd49c198e5f36c72c64b5364665e63d316bd2d27b67f9dcd4229a6223002018682581d70c767fa21743dddb7eedfa19f7c7f607be7676c30839826df1fd75d8a1b000000174876e80082581d70bd528a6796c967ed5df24c8829e47f6179cf5045a7dd81a62f55acf81b0000002e90edd00082581d70eb5b84fdcfecaf7bc427d3fd743333244d34e10b5905f60894e9f4ca1b00000045d964b80082581d702855a85ac24c4c7838df887f02d05ed5af10502fb8d21f3083d7343c1b0000005d21dba00082581d70e1b15df55620e06e31998786a653c2108e63ac1d1468c71ed49e37d51b000000746a528800825839008ccc160c4ad20989741392f51b5f763d1b1c5f2497c3918f7af275d4740f3c4a8cea4d27e5631d867e4b48dea0fdee2913cf48d53d3728491b0086801aec1c2380021a000f4240031a02c9f8f3a100818258206a1f3ccc52ef3dc17f7075f1929dfb8e4d8e2f540469403c6ef67a04ed1a1bd15840df762b33f2c80caf6648f36b56728195d7e8d1fbda8254f2eb8e5759ff21f6d8db854caa1209998d3d391d00449149eb963df0b1edf46c70a126a06734b8670cf5f6
```

Which is a correct cbor of a Transaction and which is parsed in the latest serialization-lib version with no problems.

So please refer this issue to the library or the tool that you are using to construct these requests, as they are adding an additional layer of cbor wrapping over the transaction object itself, or handle the unwrapping of that array manually, before attempting to deserialize the transaction itself.

**Comment by rooooooooob** [comment]
@0xtrossets Yeah I'm getting the same results as @vsubhuman it looks like it's just wrapped hex-encoded text which is strange (and very bloated since you get the doubling of bytes needed to represent in hex twice by having this be done twice for 4x total), and you should be passing the inner hex text to the serialization lib instead. I'm going to close this. Feel free to open it again if you run into some other issue with `null` transaction metadata.

**Comment by 0xtrossets** [comment]
Sorry, that's the format that's required for the cardano-rosetta endpoint. I'll post the difference in cardano-serialization-lib outputs soon.
