### ISSUE TITLE
how to create TX using multiple UTXO from different addresses?

### ISSUE THREAD

**Issue by mailtodanish** [Emurgo/cardano-serialization-lib#355]
how to create TX using multiple UTXO from different addresses?
 generate TX that consumes UTXO from my NAMI wallet and one utxo from some other address.

**Comment by rooooooooob** [comment]
Whether they're from multiple addresses or the same shouldn't matter. If you're using the transaction builder use its `add_input()` (or its related `add_*_input()`) just as you would with 1 input, but instead you just call it twice with the appropriate utxo info. As long as you have the info needed for the utxo (tx hash + index in that tx) you're fine. You'll probably want to know its value which you'll need to look up on-chain too so you can make sure the tx is balanced.
