### ISSUE TITLE
Bindgen update 

### ISSUE THREAD

**Issue by vsubhuman** [Emurgo/cardano-serialization-lib#362]
> To be clear, this doesn't include the fix for the stack space leak in wasm-bindgen (they haven't pushed a release for this yet). Instead, it's meant to fix https://github.com/rustwasm/wasm-bindgen/issues/2605

_Originally posted by @SebastienGllmt in https://github.com/Emurgo/cardano-serialization-lib/issues/314#issuecomment-1006284759_

New version 0.2.79 is now available in bindgen - https://github.com/rustwasm/wasm-bindgen/releases/tag/0.2.79

**Comment by lisicky** [comment]
updated to 0.2.92 :D
