### ISSUE TITLE
Locking NFT in the smart contract - UTxO Balance Insufficient

### ISSUE THREAD

**Issue by AdamMachera** [Emurgo/cardano-serialization-lib#369]
I was able to use Alessandro custom implementation of the CoinSelection.randomImprove but we would like to move to official cardano-serialization-lib version 10.0.0.3

`export const offer = async (api: CardanoApi, policyId: string, assetName: string, askingPrice: string): Promise<string> => {
    const cardano = cardanoApiAdapter(api)
    const protocolParameters = await getProtocolProtocolParams()

    const txBuilder = await createTransactionBuilder(protocolParameters)
    const selfAddress = await cardano.getWalletAddress()
    const baseAddress = BaseAddress.from_address(selfAddress)!
    const pkh = toHex(baseAddress.payment_cred().to_keyhash()?.to_bytes() as Uint8Array);

    const transactionWitnessSet = TransactionWitnessSet.new();

    const offerDatum = createSalesOfferDatum(pkh, askingPrice, policyId, assetName);
    const offerDatumHash = hash_plutus_data(toPlutusData(offerDatum));
    console.log(`offerDatumHash ${offerDatumHash} pkh: ${pkh} askingPrice: ${askingPrice} policyId: ${policyId} assetName: ${assetName}`);
    const contractOutput = TransactionOutput.new(
        getContractAddress(),
        getContractOutput(nftMoveFixedPrice, policyId, assetName)
    );
    contractOutput.set_data_hash(offerDatumHash);

    const utxos  = TransactionUnspentOutputs.new();
    const walletOutputs  = await cardano.getUtxos();
    walletOutputs.forEach(utxo => utxos.add(utxo))

    const aux_data: AuxiliaryData = await addOfferMetadata(txBuilder, selfAddress, askingPrice, assetName, policyId, "offer")

    console.log('add_output')
    txBuilder.add_output(contractOutput);
    console.log('add_input_from')
    **txBuilder.add_inputs_from(utxos, 3)**
    console.log('add_change_if_needed')
    txBuilder.add_change_if_needed(selfAddress);
    
    const txBody = txBuilder.build();
    const transaction = Transaction.new(
        txBody,
        transactionWitnessSet,
        aux_data
    );

    let signedtxVkeyWitnesses: TransactionWitnessSet
    try {
        signedtxVkeyWitnesses = await cardano.signTx(transaction, true);
    }
    catch (err) {
        throw handleSignError(err)
    }

    transactionWitnessSet.set_vkeys(signedtxVkeyWitnesses.vkeys()!);

    const signedTx = Transaction.new(
        txBody,
        transactionWitnessSet,
        transaction.auxiliary_data()
    );

    try {
        const txHash = await cardano.submitTx(signedTx);
        console.log(`txHash for sales offer: ${txHash}`);
        return txHash
    } catch (err) {
        appInsights.trackException({ exception: err as Error }, {
            sellerAddress: selfAddress.to_bech32(),
            sellerPkh: pkh,
            policyId: policyId,
            assetName: assetName,
            price: askingPrice,
            method: "offer"
        });
        throw err;
    }
}

export const addOfferMetadata = async (txBuilder: TransactionBuilder, address: Address, price: string, assetName: string, policyId: string, operation: string) => {
    const aux_data: AuxiliaryData = AuxiliaryData.new();
    const generalTransactionMetadata: GeneralTransactionMetadata = GeneralTransactionMetadata.new();
    const meta: OfferMetadata = {
        addr: splitAddress(address.to_bech32()),
        price: price,
        asset: assetName,
        policy: policyId,
        op: operation
    };

    const metadata = CardanoSerialization.encode_json_str_to_metadatum(JSON.stringify(meta), CardanoSerialization.MetadataJsonSchema.BasicConversions);
    generalTransactionMetadata.insert(BigNum.from_str("405"), metadata)
    aux_data.set_metadata(generalTransactionMetadata)
    txBuilder.set_auxiliary_data(aux_data)
    return aux_data
}
`

However the code is failing on this line:
txBuilder.add_inputs_from(utxos, 3)
with exception
**UTxO Balance Insufficient**

Any idea what I'm doing wrong

**Comment by mailtodanish** [comment]
I am also facing same issue

**Comment by vsubhuman** [comment]
Hi! The error "UTxO Balance Insufficient" means the total value of all provided inputs is not enough to cover the required output. I see you are creating the output like this:

```
const contractOutput = TransactionOutput.new(
    getContractAddress(),
    getContractOutput(nftMoveFixedPrice, policyId, assetName)
);
contractOutput.set_data_hash(offerDatumHash);
```

You need to make sure the total value of inputs that are being passed into `txBuilder.add_inputs_from(utxos, 3)` is greater than `nftMoveFixedPrice` plus the transaction fee.

If you can provide an example with specific input values that is **incorrectly** failing with the same error - then we will be able to debug and correct it. For now please check how many inputs you have there and what are their values, compared to the `nftMoveFixedPrice` value.

**Comment by AdamMachera** [comment]
Thanks, It is working.

**Comment by tas2017** [comment]
Hi Adam. can u share how u fixed this? Im also receiving same error
