### ISSUE TITLE
How can i parse the signed tx ?

### ISSUE THREAD

**Issue by bajian** [Emurgo/cardano-serialization-lib#378]
```
let txSignedBody = CardanoWasm.Transaction.new(
    txBody,
    witnesses,
    undefined // transaction metadata
);

let txSignedHex = Buffer.from(txSignedBody.to_bytes()).toString('hex');

console.log(txSignedHex);
//84a400818258208561258e210352fba2ac0488afed67b3427a27ccf1d41ec030c98a8199bc22ec0001828258390079467c69a9ac66280174d09d62575ba955748b21dec3b483a9469a65cc339a35f9e0fe039cf510c761d4dd29040c48e9657fdac7e9c01d941a000f4240825820409493315cd92eb5d8c4304e67b7e16ae36d61d34502694657811a2c8e0102031a001bf74f021a00028d31031a000641a5a10081825820e9b5aa0c60fbc886ee6dfaa25d3b4e20d6d2c527d9cfa44ffad432e5de2505c55840924bcdbe5ef5bbaad9af7c55d866325d68c9f5f5b80ef573093dccf7ab1d140fb9dcd759659ee40fe8d993c0220c19072e30b5d3be7d2be9e5d052a47348da04f5f6
```
I got the signed hex by the code above .
But i dont know how to parse and check the tx before broadcasting it .
Any method in this library or other cardano component to solve my question?

**Comment by bajian** [comment]
I found the `/construction/parse` api in the cardano-rosetta,but it seems not suitable for the sign  in this format ?
Any bro can help me? Give me an example, thank you!

**Comment by vsubhuman** [comment]
> I got the signed hex by the code above .
> But i dont know how to parse and check the tx before broadcasting it .
> Any method in this library or other cardano component to solve my question?

```
const tx = CardanoWasm.Transaction.from_bytes(
  Buffer.from(txSignedHex, 'hex')
);

const txBody = tx.body();
// etc.
```

**Comment by bajian** [comment]
Thank you. @vsubhuman
 
But how can i get the body as text type?
```
console.log(tx.body().inputs().get(0));
// TransactionInput { ptr: 1179800 }
```
I want to get the original address ,input and the mount

**Comment by bajian** [comment]
> Do you mean the address and the amount of inputs? Or address and amount of the outputs?
Yes. All of them. I want to check them before broadcasting to the node.

**Comment by bajian** [comment]
Such as the `decoderawtransaction` in bitcoin to decode the hex-encoded transaction
https://developer.bitcoin.org/reference/rpc/decoderawtransaction.html

**Comment by vsubhuman** [comment]
> Such as the `decoderawtransaction` in bitcoin to decode the hex-encoded transaction https://developer.bitcoin.org/reference/rpc/decoderawtransaction.html

There's no export to JSON support in this library yet, you can only extract the required fields manually through the API methods.

The JSON support is planned to be added in the next version tho, and there's a PR for it. Around next week there probably will be a beta release of the next version with that change, so you will be able to try it out. Not until then, unfortunately.

https://github.com/Emurgo/cardano-serialization-lib/pull/345

**Comment by bajian** [comment]
Got it. Thanks a lot!
