### ISSUE TITLE
TS errors in example folder

### ISSUE THREAD

**Issue by 34r7h** [Emurgo/cardano-serialization-lib#380]
Fresh debian 10 with lib compiled. Went into example folder to run npm install. I get these errors after running `npm run js:build`. I removed the 3 extra bignums on line 70 but no clue what to do regarding bignum type errors from lines 84 and 91
```
~/cardano-serialization-lib/example$ npm run js:build

> cardano-serialization-lib-example@1.0.0 js:build
> rm -rf dist && tsc

index.spec.ts:70:7 - error TS2554: Expected 1 arguments, but got 4.

70       CardanoWasm.BigNum.from_str('1000000'),
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
71       CardanoWasm.BigNum.from_str('500000000'),
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
72       CardanoWasm.BigNum.from_str('2000000')
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

index.spec.ts:84:7 - error TS2345: Argument of type 'BigNum' is not assignable to parameter of type 'Value'.
  Type 'BigNum' is missing the following properties from type 'Value': coin, set_coin, multiasset, set_multiasset

84       CardanoWasm.BigNum.from_str('3000000')
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

index.spec.ts:91:9 - error TS2345: Argument of type 'BigNum' is not assignable to parameter of type 'Value'.

91         CardanoWasm.BigNum.from_str("1000000"),
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 3 errors.

```

**Comment by vsubhuman** [comment]
A big update to all the documentation is upcoming over here. Meanwhile you can check the API changes in the version 10.0.0 release notes: https://github.com/Emurgo/cardano-serialization-lib/releases/tag/10.0.0

**Comment by 34r7h** [comment]
considering how many projects rely on this repo, i suggest being a bit more thoughtful to breaking changes. in fact, if the developers know about the breaking changes, why not just catch possible errors and either return decent logs or change the args where appropriate. i really don't care about precise calculation of min fees so plz just round it up instead of breaking. plz be more considerate
