### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by 0xChief** [Emurgo/cardano-serialization-lib#385]
In NextJs, I'm importing a dependency that uses the @emurgo/cardano-serialization-lib-asmjs it gives the following error. 

`./node_modules/@harmonicpool/cardano-wallet-interface/node_modules/@emurgo/cardano-serialization-lib-asmjs/cardano_serialization_lib_bg.js`
`Critical dependency: the request of a dependency is an expression`
`error - SyntaxError: Cannot use import statement outside a module`

How can I fix it? 

## Current setup
I'm importing through
`import { Wallet } from '@harmonicpool/cardano-wallet-interface';`

I've added the suggested to next.config.js
`  webpack: (config) => {
    const experiments = config.experiments || {};
    config.experiments = {
    ...experiments,
    syncWebAssembly: true,
    };
    return config
},`

and in tsconfig.json, I've set a couple other variables suggested when finding this issue online. 
`    "lib": ["esnext"],
    "module": "commonjs",
`

**Comment by SebastienGllmt** [comment]
It's just a warning. You can ignore it

**Comment by 0xChief** [comment]
Needed to dynamically import the module. It would error out and not build otherwise
