### ISSUE TITLE
Get auxilary_data from old tx and set it to new one via the constructor Transaction.new results wrong auxilary_data

### ISSUE THREAD

**Issue by zarej** [Emurgo/cardano-serialization-lib#396]
Version: "@emurgo/cardano-serialization-lib-browser": "^10.0.4"

I have created transactiob from `cardano-cli transaction build` with option `--cddl-format`. `cborHex` is output of build transaction. From the original transaction I am extracting `txAuxilaryData` and in a new signed transaction I am setting `S.Transaction.new(txBody, witnesses, txAuxilaryData)`. The problem is that I got error on submit `ConflictingMetadataHash`
```typescript
  const txBytes = Buffer.from(cborHex, 'hex')
  const tx = S.Transaction.from_bytes(txBytes)
  const txBody = tx.body()
  const txAuxilaryData = tx.auxiliary_data()
  const txHash = S.hash_transaction(txBody)

  const witnesses = S.TransactionWitnessSet.new()
  const vkeyWitnesses = S.Vkeywitnesses.new()
  vkeyWitnesses.add(S.make_vkey_witness(txHash, signKey))
  witnesses.set_vkeys(vkeyWitnesses)

  const transaction = S.Transaction.new(txBody, witnesses, txAuxilaryData)
  const cborSignedHex = Buffer.from(transaction.to_bytes()).toString('hex')
  
  console.log('Transaction Unsigned', cborHex)
  console.log('Transaction Signed', cborSignedHex)
```

Looks like metadata in `auxilary_data` is not correct and fails the hash check.

Here is a complete cbor from an unsigned transaction (the one I got from cardano-cli):
```
[{0: [[h'A9F767B8F3CF33CC313852752007ED15AF5643AC538183E6BBB22B85288BC419', 0]], 13: [], 1: [[h'009ED7D88109A20FC0FFE82926040F0768A6BD1DBECEB8124A9050FF8589FC61D21DDFCBD4D43652BF05C40C346FA794871423B65052D7614C', 994818087], [h'70D5FA699784D82763328FBAEE27412967A95F3371DFD69DF3CEECE8E7', 5000000, h'6E80AE87F613760535696DD314E18866750FE2366B5C2A1CD090ED004A5F36B1']], 2: 181913, 3: 52151178, 8: 0, 14: [], 7: h'3C345FD0695DBD97C97F3FCC9E4D4A88093C0AB1C81FD79B26A0EE3186FE1358'}, {}, true, 259({0: {3327: {"datum": {"constructor": 0, "fields": [{"bytes": "9ed7d88109a20fc0ffe82926040f0768a6bd1dbeceb8124a9050ff85"}, {"int": 31427963354}]}, "userAddress": ["addr_test1qz0d0kyppx3qls8laq5jvpq0qa52d0gahm8tsyj2jpg0lpvfl3say8", "wle02dgdjjhuzugrp5d7nefpc5ywm9q5khv9xq2ja4ae"], "wantedAmount": 33082066688}}})]
```
And here is after ` S.Transaction.new(txBody, witnesses, txAuxilaryData)`
```
[{0: [[h'A9F767B8F3CF33CC313852752007ED15AF5643AC538183E6BBB22B85288BC419', 0]], 1: [[h'009ED7D88109A20FC0FFE82926040F0768A6BD1DBECEB8124A9050FF8589FC61D21DDFCBD4D43652BF05C40C346FA794871423B65052D7614C', 994818087], [h'70D5FA699784D82763328FBAEE27412967A95F3371DFD69DF3CEECE8E7', 5000000, h'6E80AE87F613760535696DD314E18866750FE2366B5C2A1CD090ED004A5F36B1']], 2: 181913, 3: 52145430, 7: h'3C345FD0695DBD97C97F3FCC9E4D4A88093C0AB1C81FD79B26A0EE3186FE1358', 8: 0, 13: [], 14: []}, {0: [[h'C15B990344122B12494A5EDD1020D9EB32E34B0F82691F8E31645DDAB712FF2B', h'FE2E6A9D261C47F57418D43F8F4F7C5211C72089B37BD036753AACD0607E01283409FD3239F4C68DA7BB61121DFA1472929E3C21BFC6BD8168501D4E0EBC8504']]}, true, {3327: {"datum": {"constructor": 0, "fields": [{"bytes": "9ed7d88109a20fc0ffe82926040f0768a6bd1dbeceb8124a9050ff85"}, {"int": 31427963354}]}, "userAddress": ["addr_test1qz0d0kyppx3qls8laq5jvpq0qa52d0gahm8tsyj2jpg0lpvfl3say8", "wle02dgdjjhuzugrp5d7nefpc5ywm9q5khv9xq2ja4ae"], "wantedAmount": 33082066688}}]
```
Looks like tag `259({0: ...})` has been lost I have just metadata JSON.

**Comment by zarej** [comment]
The main problem here is when the transaction is regenerated from bytes in `S.Transaction.from_bytes(txBytes)`  it is losing tag 259 and map 0. So from `259({0: { metadata }}) ` we get just `{ metadata }`

**Comment by Nats08100** [comment]
Hi there,

I confim this issue using "@emurgo/cardano-serialization-lib-browser": "^10.0.5-beta.1", and also with 10.0.4.

It happens the same way: loosing the tag 259, which prevents correctly submiting the transaction ... :-(

Is there any workaround to apply ? 
Or could it be planned to be corrected in a future version ?

Thanks by advance!

**Comment by mesudip** [comment]
Can confirm.

Submitting the  transaction is giving `ConflictingMetadataHash` errror message

**Comment by mesudip** [comment]
For  now, workaround is to reconstruct the transaction with the modified `AuxiliaryDataHash` 
For this you can  recreate `txBody` and set recalculated `auxiliary_data_hash`

**Note** If you have used other fields like `validity`, `requiredSigners`,  `mint`, `collateral`, ... of the txbody, you will have to set them too
```js
  let tx = Transaction.from_bytes(Uint8Array.from(Buffer.from(txString, 'hex')))
  let txBody = tx.body()
  txBody = TransactionBody.new(txBody.inputs(),txBody.outputs(),txBody.fee(),txBody.ttl())
  txBody.set_auxiliary_data_hash(hash_auxiliary_data(tx.auxiliary_data()))
  
  // recreate transaction with modified txbody
  tx = Transaction.new(txBody, tx.witness_set(), tx.auxiliary_data())
  
  // sign the transaction
  const witnesesRaw = await provider.signTx( Buffer.from(tx.to_bytes()).toString('hex'), true)
```

**Comment by Nats08100** [comment]
Hi there,

thank you for your response @mesudip !

I understand what it deals with, but what I'm missing now, is how to modify "in practice" the auxiliary_data, in order to add the tag 259 and map 0 (which would be the fix finally...).

In my code, I'm working with a transaction which is like that : `84a800818258200aa12e279773dfb3b8ed1...26c61626c61626c61`.

Do you have any sample code that could help me modify this transaction in this sense ? 
It would be a great help !
