### ISSUE TITLE
Correct way to print policy id of an asset?

### ISSUE THREAD

**Issue by siegfried** [Emurgo/cardano-serialization-lib#397]
I noticed that to get the HEX string of a `AssetName` is by `name()`, not `to_bytes()`.

```typescript
  const testAssetName = '7453554e444145'
  const testAssetNameBytes = Buffer.from(testAssetName, 'hex')
  console.log(testAssetNameBytes.toString('ascii'))                              // tSUNDAE
  const parsedAssetName = cardano.lib.AssetName.new(testAssetNameBytes)
  console.log(Buffer.from(parsedAssetName.to_bytes()).toString('ascii'))       // GtSUNDAE
  console.log(Buffer.from(parsedAssetName.name()).toString('ascii'))            // tSUNDAE
```

Is it safe and correct to get HEX string of policy ID (type: `ScriptHash`) by `to_bytes()`? `console.log(Buffer.from(policyId.to_bytes()).toString('hex'))`

**Comment by jmhrpr** [comment]
`to_bytes()` returns CBOR representation so prepends information about the length of the bytestring, `.name()` returns the asset name in bytes. For most cases I'd assume you'd want `.name()`.

**Comment by siegfried** [comment]
@jmhrpr There is no `.name()` of `Policy ID`.
