### ISSUE TITLE
csl-v10.0.4.wasm 404 (Not Found)

### ISSUE THREAD

**Issue by qichalerm** [Emurgo/cardano-serialization-lib#398]
hello

Uncaught (in promise) CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0

Thank

**Comment by sgarbesi** [comment]
@qichalerm did you have a fix for this?

**Comment by gavinharris-dev** [comment]
I did some digging and I think it is something introduced by the Eternl Wallet: https://github.com/ccwalletio/tracker/issues/119

**Comment by sgarbesi** [comment]
> I did some digging and I think it is something introduced by the Eternl Wallet: [ccwalletio/tracker#119](https://github.com/ccwalletio/tracker/issues/119)

Disabling the Eterni extension fixed it.

**Comment by scottbolasevich** [comment]
awesome thanks for the fast response.. sorry to ask such a possibly obvious question but how can i "disable" the Eterni extension? thanks!

**Comment by sgarbesi** [comment]
> awesome thanks for the fast response.. sorry to ask such a possibly obvious question but how can i "disable" the Eterni extension? thanks! and for clarification the project im using a npm package i used was using this component the cardano-serialization-lib so that's likely where my disconnect is coming from

It's a Google Chrome extension. Disable Eterni in your extensions.

**Comment by scottbolasevich** [comment]
haha i see now.. ya that one went way over my head im building a dApp on algorand.. so im working w/ wallet connect etc i figured it was related.. thank you so much !
