### ISSUE TITLE
Need an example for creating delegation transaction

### ISSUE THREAD

**Issue by congle-ibl** [Emurgo/cardano-serialization-lib#40]
Hi all,

Please help to give me an example for creating delegation transaction. I found that there was only 2 examples on how to create a new address and make a transfer transaction.

Thank you in advance.

**Comment by SebastienGllmt** [comment]
Hey, I suggest you look at how we do things in Yoroi for examples.
Once we've shipped Shelley support for the Yoroi extension, I'll have more time to go back and do proper documentation. Hope you understand
https://github.com/Emurgo/yoroi-frontend
