### ISSUE TITLE
Recreate transaction body from CBOR hex of transaction?

### ISSUE THREAD

**Issue by mbarbas11** [Emurgo/cardano-serialization-lib#406]
I want to create an external transaction, by passing the CBOR of the unsigned transaction to json. However, the new transaction object requires the transaction body. Is there a way to restore the transaction from the CBOR? Or can I not do it this way.

**Comment by rooooooooob** [comment]
@mbarbas11 what do you mean to json? Are you using the unmerged branch of #345 ? Or is this JSON external to this library? Or are you just having some object like `{ "cborHex": "0822aabb89797a9ce87565b987a87d8978e975454987987c342984" }`?

If you have the CBOR hex itself you can just use `Transaction.from_bytes(Buffer.from('your hex string here', 'hex'))` which should parse the `Transaction` from the CBOR hex string. If you're using it from rust it would be `Transaction.from_bytes(hex::decode("your hex string here").unwrap()).unwrap()` (you might not want those unwraps in production code though in case of bad inputs)

>However, the new transaction object requires the transaction body. 

Are you talking about `Transaction.new()`, which requires a `TransactionBody`?

That is if you're constructing a transaction from its individual components. if you already have the hex of a whole transaction then you can directly parse it with `Transaction.from_bytes()`.

**Comment by mbarbas11** [comment]
Yes, sorry. My JSON has nothing to do with external libraries, just an object passing the hex and derivation path so I can grab the signers needed to make the transaction. 

I believe I follow, but I would like to clarify. So with the unsigned CBOR hex string, I can recreate that transaction with `Transaction.from_bytes(Buffer.from('your hex string here', 'hex'))` .

Then following that I can create a tx object with `Transaction.new(tx.body(), witnesses, metadata)`, using the body of the restored transaction?

**Comment by rooooooooob** [comment]
Yeah if the hex is for the entire tx (not the body) that should work. Although for that `metadata` you might want to pass in `tx.auxiliary_data()` unless you're sure that `metadata` is the same as what was in that tx.

**Comment by mbarbas11** [comment]
Sounds good. Thanks for the help!
