### ISSUE TITLE
Attaching Datums to UTXO

### ISSUE THREAD

**Issue by bakon11** [Emurgo/cardano-serialization-lib#411]
Hi,

I wad wondering if anyone could provide an example of attaching a datum to a UTXO.

Just to be clear I am not looking to attach TX metadata but actual datum to UTXO that doesn't do anything with a Plutus script but just holds arbitary data about the UTXO.

```typescript
    //DATUMS!!!
    const fields = CardanoWasm.PlutusList.new();
    fields.add(CardanoWasm.PlutusData.new_bytes(Buffer.from('3f7826896a48c593598465a096d63606ceb8206', 'hex')));
    fields.add(CardanoWasm.PlutusData.new_integer(CardanoWasm.BigInt.from_str("1888")));
    fields.add(CardanoWasm.PlutusData.new_integer(CardanoWasm.BigInt.from_str("1")));
    const constrDatum = CardanoWasm.ConstrPlutusData.new(
      CardanoWasm.BigNum.from_str('0'),
      fields
    );
    const datum = CardanoWasm.PlutusData.new_constr_plutus_data(constrDatum);
```
Adding this to my txBuilder builds a TX that constructs succesfully and submits but the datum is not attached to the UTXO.    

Was wondering if maybe I'm missing something in this step?

```typescript
    // create the finalized transaction with witnesses
    const transaction = await CardanoWasm.Transaction.new(
      newTX.body(),
      witnesses,
      includeMeta == 1 ? newTX.auxiliary_data() : undefined, //metadata
    );
```

Thank you.

**Comment by zachyking** [comment]
@bakon11 check here https://github.com/Emurgo/cardano-serialization-lib/releases Release 10.0.0 - 5. Building outputs

`TransactionOutputBuilder.new()
.with_address(Address)
.with_data_hash(DataHash)
...`

**Comment by bakon11** [comment]
Just had to `CardanoWasm.hash_plutus_data(datum)` the datum before passing it to `.with_data_hash(DataHash)`
