### ISSUE TITLE
Cardano wallet address verification.

### ISSUE THREAD

**Issue by totsteps** [Emurgo/cardano-serialization-lib#413]
Hi, how can I validate whether a given Cardano address is valid?

The [is_valid()](https://github.com/Emurgo/cardano-serialization-lib/blob/86dc681190521d28a7b5e870ddf8849daca3b3f3/rust/src/address.rs#L246) doesn't seem to work or is there something that I am missing.

Thanks.

**Comment by ozgrakkurt** [comment]
Hi, can you try `Address::from_bytes` and if it doesn't seem to work can you give more details?

**Comment by totsteps** [comment]
Sorry I should have provided more details.

What I am trying to do is, validate a given Cardano address by calling a `ByronAddress.is_valid` from 
[@emurgo/cardano-serialization-lib-nodejs](https://www.npmjs.com/package/@emurgo/cardano-serialization-lib-nodejs)

Not sure if it's the correct way of doing it, the code looks something like this:
```js
const wasm = require("@emurgo/cardano-serialization-lib-nodejs");

const ADDRESS = "some ADA address";

const isValid = wasm.ByronAddress.from_bytes(ADDRESS);

console.log(isValid);
```

**Comment by ozgrakkurt** [comment]
@totsteps Seems to throw error with that code. Can you give me a value where it isn't a valid address and it accepts it or other way around?

**Comment by SebastienGllmt** [comment]
ByronAddress is one specific kind of address, but there are other kinds of addresses in Cardano. For the general Address type, the only way is to try and parse and then catch if an error is thrown

**Comment by talhahussain7** [comment]
@SebastienGllmt  Yes, The Shelley address has a different address prefix.

How do we detect what type of Cardano address it is tho. Does the lib contain a function for that?

**Comment by totsteps** [comment]
> the only way is to try and parse and then catch if an error is thrown
This gets the job done.

@SebastienGllmt @ozgrakkurt thanks for the help 🙏.
