### ISSUE TITLE
Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'

### ISSUE THREAD

**Issue by iamhamzaawan** [Emurgo/cardano-serialization-lib#416]
I'm building React web app with Webpack and rails, using wasm to load some libraries, deployed on a Live server.
But get the error message on web console: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'

Everything went right when running on local. Struggling for a week but couldn't find any solution, please help me.

the only code related to WebAssembly below

```
class Loader {
  async load() {
    if (this._wasm) return;
    /**
     * @private
     */
    this._wasm = await import("@emurgo/cardano-serialization-lib-browser/");
  }

  get Cardano() {
    return this._wasm;
  }
}

export default new Loader();

```

**Comment by ggaabe** [comment]
Hi @iamhamzaawan, which version of Webpack are you running? If you're on Webpack 5+, Have you enabled wasm imports in the [experimental Webpack features](https://webpack.js.org/configuration/experiments/) by setting `asyncWebAssembly: true`?

Also, we tend to import a specific module from `cardano-serialization-lib-browser`, and then access its `default` property once its been imported. See the example below:
```javascript
this._wasm = await (
      await import('@emurgo/cardano-serialization-lib-browser/cardano_serialization_lib')
).default; 
```

**Comment by ggaabe** [comment]
@iamhamzaawan We also had this issue when trying to deploy to iOS; everything worked in dev, but failed in prod. The root cause of this issue was that dev served the files over localhost, but prod served them over the `file://` protocol, which strips the MIME type. In iOS, you have to define custom file extension MIME types in the info.plist file. 

This is the change we had to add to the `dict` in our plist to get that to work:

```xml
	<key>UTExportedTypeDeclarations</key>
	<array>
		<dict>
			<key>UTTypeIdentifier</key>
			<string>[YOUR BUNDLE IDENTIFIER HERE]</string>
			<key>UTTypeConformsTo</key>
			<array>
				<string>public.data</string>
			</array>
			<key>UTTypeDescription</key>
			<string>wasm files</string>
			<key>UTTypeTagSpecification</key>
			<dict>
                <key>public.filename-extension</key>
                	<string>wasm</string>
                <key>public.mime-type</key>
                	<string>application/wasm</string>
			</dict>
		</dict>
	</array>
```

**Comment by iamhamzaawan** [comment]
Hey @ggaabe thanks for answering my question and helping me. As i am using the webpacker with rails application i am not sure where i can add experiments and `asyncWebAssembly: true` in the app as there is no `webpack.config.js` file where we can add this and for webpacker configuration we use `webpacker.yml`, I have tried adding it in that file but didn't get any results. Also, i have tried appending default while importing cardano library but that wasn't helpful too. :(

**Comment by ozgrakkurt** [comment]
This is a general issue with static file servers. You generally need to tell them to serve .wasm files with application/wasm mime type you can find related info on the server you use by googling it with something like `nginx wasm mime type`

**Comment by ozgrakkurt** [comment]
@iamhamzaawan Hi which http server do you use to serve the static files you have in production mode? I can maybe help you find a solution

**Comment by iamhamzaawan** [comment]
Thanks for help guys but i finally find the solution. I was using Nginx and I just added the `application/wasm` mime type in config of Nginx and it solved the problem.
