### ISSUE TITLE
User has accepted the transaction sign, but the wallet was unable to sign the transaction (e.g. not having some of the private keys

### ISSUE THREAD

**Issue by HT-Moh** [Emurgo/cardano-serialization-lib#419]
Hi, I am having an issue to mint NFT 
I am getting the following error on `assetsToValue` 
`Deserialization failed in ScriptHash because: Invalid cbor: expected tuple 'hash length' of length 28 but got length Len(13).`
Library  `"@emurgo/cardano-serialization-lib-browser": "^10.0.4",` 

```javascript
async createLockingPolicyScript(
    protocolParameters: ProtocolParameters
  ): Promise<Result<{ id: string; script: NativeScript; ttl: number }>> {
    let [address] = await this.wallet.getUsedAddresses()
    return getResult(() => {
      if (!protocolParameters.slot) throw new Error('Protol params error')
      const slot = protocolParameters.slot
      const ttl = slot + 1000
      address = Loader.Cardano.Address.from_bytes(Buffer.from(address, 'hex'))
      if (!address || typeof address === 'undefined')
        throw new Error('address error')
      const paymentKeyHash = this.getAddressKeyHash(address)
      if (!paymentKeyHash.isOk || !paymentKeyHash.data)
        throw new Error('Address key error')
      const nativeScripts = Loader.Cardano.NativeScripts.new()
      const script = Loader.Cardano.ScriptPubkey.new(paymentKeyHash.data)
      const nativeScript = Loader.Cardano.NativeScript.new_script_pubkey(script)
      const lockScript = Loader.Cardano.NativeScript.new_timelock_expiry(
        Loader.Cardano.TimelockExpiry.new(ttl)
      )
      nativeScripts.add(nativeScript)
      nativeScripts.add(lockScript)
      const finalScript = Loader.Cardano.NativeScript.new_script_all(
        Loader.Cardano.ScriptAll.new(nativeScripts)
      )
      const policy = Loader.Cardano.ScriptHash.from_bytes(
        finalScript
          .hash(Loader.Cardano.ScriptHashNamespace.NativeScript)
          .to_bytes()
      ).to_bytes()
      const policyId = Buffer.from(policy.toString(), 'hex').toString('hex')
      return { id: policyId, script: finalScript, ttl }
    })
  }
```
```javascript
  public async MintTx(metadata: {
    name: string | any[]
    quantity: { toString: () => any }
    metadata: any
  }) {
    const protocolParameters = await this._protocol.getProtocolParameters()
    const policy = await this.createLockingPolicyScript(protocolParameters)
    if (!policy.isOk) return policy
    const name = metadata.name.slice(0, 32) as string
    const assets = [{ name: name, quantity: metadata.quantity.toString() }]

    const METADATA = {
      [policy.data.id]: {
        [name]: {
          ...metadata.metadata
        }
      }
    }
    console.log(metadata)
    try {
      const transaction = await this.mintTx(
        assets,
        METADATA,
        policy.data,
        protocolParameters
      )
      console.log(transaction)
      //console.log(signedTx)
      //const txHash = await submitTx(signedTx);
      return await this.signAndSubmitTransaction(transaction)
    } catch (error: any) {
      return { error: error.info || error.toString() }
    }
  }
  protected async mintTx(
    assets: { name: any; quantity: any }[],
    metadata: any,
    policy: { id: string; script: NativeScript; ttl: number | undefined },
    protocolParameters: ProtocolParameters
  ) {
    const address = Buffer.from(
      (await this.wallet.getUsedAddresses())[0],
      'hex'
    )
    const checkValue = await assetsToValue(
      assets.map((asset: { name: string; quantity: any }) => ({
        unit: policy.id + asciiToHex(asset.name),
        quantity: asset.quantity
      }))
    )
}
```
```javascript
export const assetsToValue = async (assets: any) => {
  const multiAsset = Loader.Cardano.MultiAsset.new()
  const lovelace = assets.find((asset: any) => asset.unit == 'lovelace')

  // Get the policy ids off all assets
  const policies = [
    ...new Set(
      assets
        .filter((asset: any) => asset.unit !== 'lovelace')
        .map((asset: any) => asset.unit.slice(0, 56))
    )
  ]
  // Loop through all policies and get their quantity
  // eslint-disable-next-line unicorn/no-array-for-each
  policies.forEach((policy: any) => {
    const policyAssets = assets.filter(
      (asset: any) => asset.unit.slice(0, 56) === policy
    )
    const assetsValue = Loader.Cardano.Assets.new()
    // eslint-disable-next-line unicorn/no-array-for-each
    policyAssets.forEach((asset: any) => {
      assetsValue.insert(
        Loader.Cardano.AssetName.new(Buffer.from(asset.unit.slice(56), 'hex')),
        Loader.Cardano.BigNum.from_str(asset.quantity)
      )
    })
    multiAsset.insert(
      Loader.Cardano.ScriptHash.from_bytes(Buffer.from(policy, 'hex')),
      assetsValue
    )
  })
  const value = Loader.Cardano.Value.new(
    Loader.Cardano.BigNum.from_str(lovelace ? lovelace.quantity : '0')
  )
  if (assets.length > 1 || !lovelace) value.set_multiasset(multiAsset)
  return value
}
````

Error is triggered here `  multiAsset.insert(
      Loader.Cardano.ScriptHash.from_bytes(Buffer.from(policy, 'hex')),
      assetsValue
    )`

**Comment by HT-Moh** [comment]
I fixed the issue by changing : 

```
     const policyId = Buffer.from(
        this.lib.ScriptHash.from_bytes(
          finalScript.hash(0).to_bytes()
        ).to_bytes()
      ).toString('hex')
```
```
 const policy = Loader.Cardano.ScriptHash.from_bytes(
        finalScript
          .hash(Loader.Cardano.ScriptHashNamespace.NativeScript)
          .to_bytes()
      ).to_bytes()
      const policyId = Buffer.from(policy.toString(), 'hex').toString('hex')
```
Now the tx is build but I have the following error: 

```
"transaction submit error ShelleyTxValidationError ShelleyBasedEraAlonzo (ApplyTxError [UtxowFailure (WrappedShelleyEraFailure (MissingScriptWitnessesUTXOW (fromList [ScriptHash \"8d8deb3c5a7a35f6742b5378ce9c81348e272563d16d6913a1ad7eb8\"]))),UtxowFailure (WrappedShelleyEraFailure (MissingTxMetadata (AuxiliaryDataHash {unsafeAuxiliaryDataHash = SafeHash \"49fd5c3a53f13f2d8ee9e3973c407c30b76155f1af28c233b2907603e35a5a57\"}))),UtxowFailure (WrappedShelleyEraFailure (UtxoFailure (UtxosFailure (CollectErrors [NoRedeemer (Minting (PolicyID {policyID = ScriptHash \"8d8deb3c5a7a35f6742b5378ce9c81348e272563d16d6913a1ad7eb8\"})),NoWitness (ScriptHash \"8d8deb3c5a7a35f6742b5378ce9c81348e272563d16d6913a1ad7eb8\")])))),UtxowFailure (WrappedShelleyEraFailure (UtxoFailure (FeeTooSmallUTxO (Coin 177997) (Coin 177733))))])"
```

**Comment by ozgrakkurt** [comment]
@HT-Moh Hi, it looks like the ADA utxo you have isn't enough to pay the transaction fee.

one problem might be if you are calculating the fee and then adding input it will change the fee again so it won't match. Simple way to do it is to add a input like 2-3 ADA and you will get the change back anyway. Also you can check [this](https://github.com/ozgrakkurt/cardano-mint-nft) about minting nfts

**Comment by ozgrakkurt** [comment]
@HT-Moh the error might be because how you create the witness here:
```js
Loader.Cardano.PrivateKey.from_normal_bytes(
  Loader.Cardano.StakeCredential.from_keyhash(
    paymentKeyHashResult.data
  ).to_bytes()
)
```
I don't think that really produces the private key of the policy. You can read a private key from cardano-cli generated `.skey` file cbor like this:
```js
const policyPrivateKey = CardanoWasm.PrivateKey.from_normal_bytes(
  cbor.decodeFirstSync(
    "582009ca7f508dd5a5f9823d367e98170f25606799f49ae7363a47a11d7d3502c91f"
  )
);
```

**Comment by tqueri** [comment]
When calling the function wallet.signTx("...") add the second parameter (partial sign true).
`
wallet.signTx(myTx, true); `

Good luck sir

**Comment by HT-Moh** [comment]
@tqueri  thanks. 
I set partial sign to true and got 
```
"transaction submit error ShelleyTxValidationError ShelleyBasedEraAlonzo (ApplyTxError [UtxowFailure (WrappedShelleyEraFailure (MissingScriptWitnessesUTXOW (fromList [ScriptHash \"6aa9bd37f4ae4466d4bf8cf548e920bb95c20cf95442b98cb3b87ddb\"]))),UtxowFailure (WrappedShelleyEraFailure (MissingTxMetadata (AuxiliaryDataHash {unsafeAuxiliaryDataHash = SafeHash \"aca2e5023d9ef21ea01d24ed2c54884f221dfbac5b0e6e6f1a58c43b9f58ec8f\"}))),UtxowFailure (WrappedShelleyEraFailure (UtxoFailure (UtxosFailure (CollectErrors [NoRedeemer (Minting (PolicyID {policyID = ScriptHash \"6aa9bd37f4ae4466d4bf8cf548e920bb95c20cf95442b98cb3b87ddb\"})),NoWitness (ScriptHash \"6aa9bd37f4ae4466d4bf8cf548e920bb95c20cf95442b98cb3b87ddb\")]))))])"
```

**Comment by HT-Moh** [comment]
Unfortunately, nothing works, I tried all possible combinations, this is supposed to be fairly simple I have one policy that I generated and I use it as a witness for the NFT. and using NAMI to sign the tx to pay for the minting. 
I tried to sign the tx partially and then submitted it does not work as well, keep getting not helpful errors.  
I would like to understand what is wrong with my code. 

```bash
cardano-cli address key-gen \
            --verification-key-file policy.vkey \
            --signing-key-file policy.skey
``` 
I created the script so 
```
  async createLockingPolicyScript(
    protocolParameters: ProtocolParameters
  ): Promise<Result<{ id: string; script: NativeScript; ttl: number }>> {
    return getResult(() => {
      if (!protocolParameters.slot) throw new Error('Protocol params error')
      const slot = protocolParameters.slot
      const ttl = slot + 2000
      const pk = Loader.Cardano.PrivateKey.from_normal_bytes(
        cbor.decodeFirstSync(
          'POLICY_SIGNING_KEY'
        )
      )
      const nativeScripts = Loader.Cardano.NativeScripts.new()
      const script = Loader.Cardano.ScriptPubkey.new(pk.to_public().hash())
      const nativeScript = Loader.Cardano.NativeScript.new_script_pubkey(script)
      const lockScript = Loader.Cardano.NativeScript.new_timelock_expiry(
        Loader.Cardano.TimelockExpiry.new(ttl)
      )
      nativeScripts.add(nativeScript)
      nativeScripts.add(lockScript)
      const finalScript = Loader.Cardano.NativeScript.new_script_all(
        Loader.Cardano.ScriptAll.new(nativeScripts)
      )
      const policyId = Buffer.from(
        this.lib.ScriptHash.from_bytes(
          finalScript.hash(0).to_bytes()
        ).to_bytes()
      ).toString('hex')
      console.log('Policy ID:')
      console.log(policyId)
      //const policyId = Buffer.from(policy.toString(), 'hex').toString('hex')
      return { id: policyId, script: finalScript, ttl }
    })
  }
```
I add the witness like so 
```javascript
   const policyPrivateKey = Loader.Cardano.PrivateKey.from_normal_bytes(
      cbor.decodeFirstSync(
        'POLICY SIGNING KEY'
      )
    )
    // vkeys.add(vkeyWit)
    // witnesses.set_vkeys(vkeys)

    vkeyWitnesses.add(
      Loader.Cardano.make_vkey_witness(txHash, policyPrivateKey)
    )

```
I tried both submitting tx directly / partially signing with policy and then submitting. 

```
    witnesses.set_vkeys(vkeyWitnesses)

    const witnessScripts = Loader.Cardano.NativeScripts.new()
    witnessScripts.add(mintScript)
    witnesses.set_native_scripts(witnessScripts)
    const unsignedTx = txBuilder.build_tx()
    // create signed transaction
    const transaction = Loader.Cardano.Transaction.new(
      unsignedTx.body(),
      witnesses,
      unsignedTx.auxiliary_data()
    )
    if (this.checkTxSize(transaction, protocolParameters.maxTxSize)) {
      return transaction
    }
```
partially signing 
```
    if (this.checkTxSize(transaction, protocolParameters.maxTxSize)) {
      // return transaction
      const serializedTx = toHex(transaction.to_bytes())
      const txVkeyWitnesses = await this.wallet.signTx(serializedTx, true)

      const signedtxVkeyWitnesses =
        Loader.Cardano.TransactionWitnessSet.from_bytes(
          fromHex(txVkeyWitnesses)
        )
      const c = Loader.Cardano.TransactionWitnessSet.new()
      c.set_vkeys(signedtxVkeyWitnesses.vkeys() as Vkeywitnesses)
      // signedtxVkeyWitnesses.set_native_scripts(witnessScripts)
      // signedtxVkeyWitnesses.set_vkeys(vkeyWitnesses)
      return Loader.Cardano.Transaction.new(
        Loader.Cardano.TransactionBody.from_bytes(
          transaction.body().to_bytes()
        ),
        Loader.Cardano.TransactionWitnessSet.from_bytes(c.to_bytes()),
        unsignedTx.auxiliary_data()
      )
    }
```

{error: 'Wallet could not send the tx.'}

I thought the NAME of the asset should be on hex the problem: 
I changed this::
```
    const assets = [{ name: name, quantity: metadata.quantity.toString() }]
```
to
```
 const name = metadata.name.slice(0, 32) as string
    const assets = [
      { name: asciiToHex(name), quantity: metadata.quantity.toString() }
    ]
```
Keep getting same errors.

> I could mint with cardano-cli without any problem.
> I don't want to copy existing working code, I would like to understand what's wrong with mine. 

The objective a simple I want to mint native NFT with policy ID and pay for it using the connected walled to the APP

**Comment by HT-Moh** [comment]
Everything works now. thank you.

**Comment by SumenjakZiga** [comment]
Hey, @HT-Moh  can you share the solution? I ran into the same problem.

transaction submit error ShelleyTxValidationError ShelleyBasedEraAlonzo (ApplyTxError [UtxowFailure (WrappedShelleyEraFailure (MissingScriptWitnessesUTXOW (fromList [ScriptHash \"2e5fe74296429d39475e5cdcf3e1587f06d106cccb182a9e67b5a62a\"]))),UtxowFailure (WrappedShelleyEraFailure (UtxoFailure (UtxosFailure (CollectErrors [NoRedeemer (Minting (PolicyID {policyID = ScriptHash \"2e5fe74296429d39475e5cdcf3e1587f06d106cccb182a9e67b5a62a\"})),NoWitness (ScriptHash \"2e5fe74296429d39475e5cdcf3e1587f06d106cccb182a9e67b5a62a\")]))))])

**Comment by vsubhuman** [comment]
> Hey, @HT-Moh can you share the solution? I ran into the same problem.
> 
> transaction submit error ShelleyTxValidationError ShelleyBasedEraAlonzo (ApplyTxError [UtxowFailure (WrappedShelleyEraFailure (MissingScriptWitnessesUTXOW (fromList [ScriptHash "2e5fe74296429d39475e5cdcf3e1587f06d106cccb182a9e67b5a62a"]))),UtxowFailure (WrappedShelleyEraFailure (UtxoFailure (UtxosFailure (CollectErrors [NoRedeemer (Minting (PolicyID {policyID = ScriptHash "2e5fe74296429d39475e5cdcf3e1587f06d106cccb182a9e67b5a62a"})),NoWitness (ScriptHash "2e5fe74296429d39475e5cdcf3e1587f06d106cccb182a9e67b5a62a")]))))])

@SumenjakZiga , this error message suggests your transaction is missing a Plutus script redeemer, not a user signature. Can you plz show an example of how you are building your transaction? Specifically, how you add Plutus inputs and how you handle the witness set before building the transaction.

**Comment by SumenjakZiga** [comment]
Yes, that is what I don't understand. I'm not using a Plutus script, just a multisig mint. Everything works fine, and I can send ADA from wallet to wallet, but as soon as I introduce `add_mint_asset_and_output_min_required_coin` everything starts to fall apart. 

Client:
`
const shelleyOutputAddress = Address.from_bech32(this.state.addressBech32SendADA); // Buyer
const shelleyChangeAddress = Address.from_bech32(this.state.changeAddress); // Change addr

// output
txBuilder.add_output(
    TransactionOutput.new(
        shelleyChangeAddress,
        Value.new(BigNum.from_str(this.state.lovelaceToSend.toString()))
    )
)

// NativeScript
const test = "c617c315b82238d60a6aa9ac6fd06b2384ffcbb902e3ce5c0e846840" // key-hash created with cardano-cli
const pubkeyWitness = NativeScript.new_script_pubkey(ScriptPubkey.new(Ed25519KeyHash.from_bytes(Buffer.from(test, 'hex'))))

// asset
txBuilder.add_mint_asset_and_output_min_required_coin(
      pubkeyWitness,
      AssetName.new(Buffer.from("test")),
      Int.new_i32(1),
      TransactionOutputBuilder.new()
        .with_address(shelleyOutputAddress )
        .next()
)

// tx-in
const txUnspentOutputs = await this.getTxUnspentOutputs();
txBuilder.add_inputs_from(txUnspentOutputs, 2)

txBuilder.add_change_if_needed(shelleyChangeAddress)
const txBody = txBuilder.build();

const transactionWitnessSet = TransactionWitnessSet.new();
const tx = Transaction.new(
      txBody,
      TransactionWitnessSet.from_bytes(transactionWitnessSet.to_bytes())
 )

let txVkeyWitnesses = await this.API.signTx(Buffer.from(tx.to_bytes(), "utf8").toString("hex"), true);
// txBody and txWitness are send to the server

let sendJSON = { txBody: testTx, txWitness: txVkeyWitnesses };
    console.log("json: ", JSON.stringify(sendJSON))

fetch("http://localhost:8080/mint", {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
},
      body: JSON.stringify(sendJSON)
})
 .then(response => {
        console.log(response);
})
.catch(err => {
        console.error(err);
});
`
Server-side uses Lucid from alessandrokonrad

`
app.post('/mint', (req, res) => {
    const request = req.body;
    const sKeyStr = "sKey created with:
                               cardano-cli address key-gen --verification-key-file test.key --signing-key-file test.skey"
    const sKey = C.PrivateKey.from_normal_bytes(cbor.decodeFirstSync(Buffer.from(sKeyStr, 'hex')))

    let transaction = C.Transaction.from_bytes(Buffer.from(request.txBody, 'hex'))
    let signatureSet = C.TransactionWitnessSet.from_bytes(Buffer.from(request.txWitness, 'hex'))
    const signatureList = signatureSet.vkeys()
    const transaction_body = transaction.body();
    const txBodyHash = C.hash_transaction(transaction_body);
    const witness = C.make_vkey_witness(
        txBodyHash,
        sKey
    );
    signatureList.add(witness)
   signatureSet.set_vkeys(signatureList)

    const txNativeScripts = transaction.witness_set().native_scripts()
    if(txNativeScripts) signatureSet.set_native_scripts(txNativeScripts)
    const signedTx = C.Transaction.new(transaction.body(), signatureSet)
    sendAda(signedTx)
}

const sendAda = async (tx) => {
    const resF = await lucid.provider.submitTx(tx)
}
`
The keyHash in the error above is different from the keyHash that I created locally with cardano-cli. My guess is that the server-side witness can't sign or is not the right one to sign, because of the keyHash differences.

**Comment by vsubhuman** [comment]
@SumenjakZiga , yeah there's a problem in your code that you are not actually passing the script witness along with your transaction to the backend and you are losing it when building the tx with the old deprecated `.build()` function.

When you call `.txBuilder.add_mint_asset_and_output_min_required_coin` - the passed script is actually being added to the underlying witness set in the builder.

When you call `.build()` - it only returns you the transaction body, so the witness set gets ignored.

Then you create a new **empty** witness set as `const transactionWitnessSet = TransactionWitnessSet.new();` and you never set your native script as a witness there.

On the backend you try to handle the native scripts with this:
```
const txNativeScripts = transaction.witness_set().native_scripts()
if(txNativeScripts) signatureSet.set_native_scripts(txNativeScripts)
```

But the script is never there because you have never put it into the witness set in the first place, before calling the backend.

## How to fix

What I would recommend best is to stop using the `.build()` function and switch to `.build_tx(): Transaction`. It will return a full transaction body with the witness set included and therefore the script will already be there.

Then you can completely remove this part where you create a new fake transaction with an empty witness set:

```
const txUnspentOutputs = await this.getTxUnspentOutputs();
txBuilder.add_inputs_from(txUnspentOutputs, 2)

txBuilder.add_change_if_needed(shelleyChangeAddress)
const tx = txBuilder.build_tx();

let txVkeyWitnesses = await this.API.signTx(Buffer.from(tx.to_bytes(), "utf8").toString("hex"), true);`
```

And then keep the rest as it is. That way your backend should receive a transaction that does contain the native script witness.

**Comment by SumenjakZiga** [comment]
Thank you, it works!
