### ISSUE TITLE
Get the datum hash of DataHash from pre-built transaction output

### ISSUE THREAD

**Issue by kelizarov** [Emurgo/cardano-serialization-lib#421]
HI. I have a rpoblem with obtaining a Datum hash that is present in my pre-built transaction output. 

Case scenario:
1. I build a raw transaction outside of cardano-serialization-lib (in PAB to be precise)
2. Using a forked `cardano-wallet` I try to balance the transaction and provide all inputs to request body. Using MELD's fork https://github.com/MELD-labs/cardano-wallet
3. But for balancing I need to provide full infrormation about inputs and outputs. I've managed to collect most info except for Datum hash that is part of an output.
Here's a snippet that I use to build a body for balance request where I try to rebuild the input information of existing transaction:
```
 for (let i = 0; i < rawTx.body().inputs().len(); i++)
     {
         let input = rawTx.body().inputs().get(i);
         let output = rawTx.body().outputs().get(i);

         scriptInputs.push(
             {
                 "id": toHexString(input.transaction_id().to_bytes()),
                 "index": input.index(),
                 "address": output.address().to_bech32(),
                 "amount": {
                     "unit": "lovelace",
                     "quantity": Number(output.amount().coin().to_str()),
                 },
                 "assets": [],
                 "datum": output.data_hash() ? toHexString(output.data_hash().to_bytes()) : null
             }
         )
     }
```
But when I try to process it I get the wrong hash. For example this is the hash that the code above generates from Tx:
```
{"id":"f580995751b947a4d08b15178cc5373ac05252a5e6c08249ca9edcbea9cd73e8","index":0,"address":"addr_test1wzzfjxluz6thjcg5x3eeujhm2rc0ku86lzjztap4amchrucdfyyh2","amount":{"unit":"lovelace","quantity":2000000},"assets":[],"datum":"c34ae3d4f8961c10f424a171401c87845d46e521d626f81fd2e7b4d8012bded5"}
```
But when I do from `cardano-cli` I get this hash:
```
cardano-cli query utxo --address addr_test1wzzfjxluz6thjcg5x3eeujhm2rc0ku86lzjztap4amchrucdfyyh2 --testnet-magic 1097911063                                                                                                                               │
                           TxHash                                 TxIx        Amount                                                                                                                                                                        │ 
    │--------------------------------------------------------------------------------------                                                                                                                                                                      │
    │f580995751b947a4d08b15178cc5373ac05252a5e6c08249ca9edcbea9cd73e8     0        2000000 lovelace + TxOutDatumHash ScriptDataInAlonzoEra "80b465f0aaa9c486e97c7ec95c883e07eddcb4465c55c96969fdb963284fde20"
```

Can anybody help me understand what am I doing wrong here?

**Comment by ozgrakkurt** [comment]
You call `data_hash` on the output object to get the datum hash you can then do `Buffer.from(dataHash.to_bytes().toString('hex'))`

**Comment by kelizarov** [comment]
I've tried doing `Buffer.from(output.data_hash().to_bytes()).toString("hex")` but that gave the same result, where datum hashes doesn't match what's stored on-chain.

**Comment by kelizarov** [comment]
Okay I'm going to close this issue, because my code was reading utxo data incorrect which led to misinterpreting the datum hashes. My issue was that in raw transaction that I've received from PAB doesn't include all information about the inputs (tx hash and index), so I had to query data about datum hash somewhere else. The datum I've received in code above was actually linked to newly output in that tx and it was indeed a different one. Apologies for a confusing question.
