### ISSUE TITLE
get_fee_if_set

### ISSUE THREAD

**Issue by bakon11** [Emurgo/cardano-serialization-lib#422]
Just quick question when using `get_fee_if_set`.

Using it this way returns `BigNum { ptr: 1203504 }` Just wondering how do I deserialize this to get a readable number?

Thank you.

```typescript
const fee: any = await txBuilder.get_fee_if_set();
```

**Comment by tqueri** [comment]
`get_fee_if_set().to_str()`

**Comment by bakon11** [comment]
FYI: That presented solution does not work.

Thanks.

**Comment by bakon11** [comment]
> 

I stand corrected, I must have been doing something weird when I first tried it haha.
