### ISSUE TITLE
add_inputs_from results in error when using utxos from extension wallets

### ISSUE THREAD

**Issue by eselkin** [Emurgo/cardano-serialization-lib#423]
Versions - 10.0.4 and 10.0.5-beta1
When trying to add inputs using
```
txBuilder.add_inputs_from(txOutInputs, CoinSelectionStrategyCIP2.RandomImprove);
```
I get this error (the coin selection strategy does not matter, it errors on all of them):

```
{code: -1, info: "Inputs do not conform to this spec or are otherwise invalid."}
```

The utxos are coming directly out of any chrome extension CIP30 wallet (I've tried nami, eternl, and flint). The utxos are initially an array of the hex encoded strings of data. The contents seem correct and I iterate over the list and construct the TransactionUnspentOutputs with their byte values.

...(similar to others' examples)...
```
  const txOutputs = TransactionUnspentOutputs.new()
  utxos.forEach((utxo) => {
    txOutputs.add(TransactionUnspentOutput.from_bytes(Buffer.from(utxo, 'hex')))
  })
```
Inspecting each TransactionUnspentOutput constructed shows all the valid fields you'd expect. The amounts on output, the addresses, etc. So they seem to be conforming as far as I can see. I'm not sure why the error is popping up. Also, I can't find the error in the code base so it may be a dependency.

Any help on making the inputs succeed would be greatly appreciated!

**Comment by radflipper** [comment]
Check out this issue:
https://github.com/Emurgo/cardano-serialization-lib/issues/390

**Comment by eselkin** [comment]
I'm stupid. Closing this issue, I was submitting the Transaction as opposed to a hex string of the bytes.
