### ISSUE TITLE
Burning NFT

### ISSUE THREAD

**Issue by iliketowritecode** [Emurgo/cardano-serialization-lib#432]
Does anyone know how I would burn an NFT, after it's generated from this example? https://github.com/Emurgo/cardano-serialization-lib/blob/6af4284b32841a13ebe86fdcc6f10dd1d74ddfdc/doc/getting-started/minting-nfts.md

Tried adding the following to the code (after I minted an NFT), but i'm getting a `ValueNotConservedUTxO` error :
```
txBuilder.add_mint_asset(mintScript, CardanoWasm.AssetName.new(Buffer.from("asdNFT5")), CardanoWasm.Int.new_negative(CardanoWasm.BigNum.from_str("1")));
``` 

If anyone know's how I would burn an NFT, instead of minting one.. that would be amazing!

**Note**: I have a feeling I need to attach the min ada required with the NFT i'm burning, right? There's something i'm not doing here during the burn process.

**Comment by vsubhuman** [comment]
Hi, @iliketowritecode ! You need to make sure that you are providing the burned NFT on the inputs to the transaction, i.e.:
1. Add input with that NFT present
2. Add negative mint
3. Do not have the NFT mentioned anywhere in the outputs

After that the transaction should work, as long as there's enough input ADA to cover the fees and any change. Check that your transaction has these conditions correctly plz. If yes - send the resulting transaction hex or base64 and we can check why it could be getting `ValueNotConservedUTxO`

**Comment by iliketowritecode** [comment]
> Hi, @iliketowritecode ! You need to make sure that you are providing the burned NFT on the inputs to the transaction, i.e.:
> 
> 1. Add input with that NFT present
> 2. Add negative mint
> 3. Do not have the NFT mentioned anywhere in the outputs
> 
> After that the transaction should work, as long as there's enough input ADA to cover the fees and any change. Check that your transaction has these conditions correctly plz. If yes - send the resulting transaction hex or base64 and we can check why it could be getting `ValueNotConservedUTxO`

Thanks so much for getting back to me so quick. Few more questions if you don't mind!

If i'm burning an NFT, do I need to add a UTXO with enough ADA in it to the inputs (like so):
```
  txBuilder.add_key_input(
    privKeyHash,
    CardanoWasm.TransactionInput.new(
      CardanoWasm.TransactionHash.from_bytes(Buffer.from(utxo.tx_hash, "hex")),
      utxo.tx_index
    ),
    CardanoWasm.Value.new(CardanoWasm.BigNum.from_str(utxo.amount))
  );
  ```

Or is the above code only necessary when i'm minting the NFT?

For the different steps you mentioned:

```
  txBuilder.add_mint_asset(mintScript,
    CardanoWasm.AssetName.new(Buffer.from("asdNFT5")), CardanoWasm.Int.new_negative(CardanoWasm.BigNum.from_str("1")));
```

This is the code for Step 1 and 2, yes? (It adds the NFT "asdNFT5" and the negative amount?)

Are these 2 code blocks above not enough to send the transaction? 

And I think this is the base64 tx?
```
hKUAgYJYIILFzsDN8okmNoR/rx7pIaT6eZJNnaIIG6g8QL9Wc9HYAQGCglg5AMq2s0GtewRSM2ti2ZyKaQeSaj//ebqrYc7wUS3KtrNBrXsEUjNrYtmcimkHkmo//3m6q2HO8FEtghoAFIUeoVgcIqqTDjqg0MhDsB+lKWA5KeBMi12C7PL6w70Q1aFHYXNkTkZUNQGCWDkAyrazQa17BFIza2LZnIppB5JqP/95uqthzvBRLcq2s0GtewRSM2ti2ZyKaQeSaj//ebqrYc7wUS0aG1avqwIaAAK42QMaA3I2wwmhWBwiqpMOOqDQyEOwH6UpYDkp4EyLXYLs8vrDvRDVoUdhc2RORlQ1AaIAgoJYIPuWCd4L3VsIYUrVR/gjcH9FczaVh9uMuH8KDVbHChXQWEDezl/9ZyC7EKfs3T88xa2/n1K4KVBfVsb4nKjKiqNRAfUTGU9doyZWCZDFROMx398ZsdVO0kWYqkfPJQ94ppoEglgg9wGu4zbhB8haTRK49SWkDM+lBzkAwCQ2tqVHa/W8Gw9YQJkLKZ5gFSBwsqFKmk8gz4F8Jeji3tUT2QJUxrdV7mZVxiOEGbUK9LQKzMz3DVuCkmYazJAFPdyDBWxJcwIxbAwBgYIBgoIAWBxtUNaJLyS+gQJIhakzPG0JO/OiMFf8XREdtz46ggUaA3I2w/X2
```

**Comment by vsubhuman** [comment]
> If i'm burning an NFT, do I need to add a UTXO with enough ADA in it to the inputs (like so):

You must provide enough ADA to cover the transaction fees and any potential change assets.

For example, if you have a UTxO with a single NFT - it is guaranteed to have some minimal required ADA in in, something like 1.4 ADA, if you put this into the inputs and burn that NFT - there 1.4 ADA will be freed and it will be most probably enough to pay the transaction fees and get the remaining ~1.2 ADA back as change.

But if, for example, you have a UTxO with 2 NFTs - it will also have at least some minimal required ADA, like 1.5 ADA, and if you add it to the inputs and burn **only one of the two NFTs** - the remaining NFT must be sent back as change and then the 1.5. ADA will not be enough to both pay the tx fee and also include required ~1.4 ADA into the change to store the change NFT.

> This is the code for Step 1 and 2, yes? (It adds the NFT "asdNFT5" to the inputs with the negative amount?)

This only covers step 2 - you are specifying that you want to UNMINT this particular NFT in that transaction, but this function call cannot automatically add that NFT into the inputs for you, you must provide the UTxO with the NFT you want to burn and add it using `. add_key_input`.

> And I think this is the base64 tx?

In your transaction you only have one input:
```
[[h'D2EC8F3A6386CD859B6A6862F53C92B17F91452ADF97D54165C67B4B820B96B8', 1]]
```

This is the **second** output of this transaction: https://testnet.cardanoscan.io/transaction/d2ec8f3a6386cd859b6a6862f53c92b17f91452adf97d54165c67b4b820b96b8

On the explorer page you can see that this UTxO does not actually have the NFT that you are attempting to burn, it only has 458.665899 ADA in it. The NFT is in the **first** output, along with 1.344798 ADA.

You must update your code to include the correct UTxO alone (the 1.3 ADA would be enough for the fees and the change then) or add both of them together to be extra sure.

**Comment by vsubhuman** [comment]
> 3\. I've specified that I want to burn the "asdNFT5" token (with the negative amount):

You are specifying incorrect minting script.

The token in your input UTXO is this `asdNFT5` - https://testnet.cardanoscan.io/token/22aa930e3aa0d0c843b01fa529603929e04c8b5d82ecf2fac3bd10d56173644e465435

It has the policy ID `22aa930e3aa0d0c843b01fa529603929e04c8b5d82ecf2fac3bd10d5`

But in the transaction the calculated mint entry looks like this:
```
{h'D3AC22DB7E07E50823A7D8AC64FEB29652F0DD15E0C8AD81E1CD89B2': {h'6173644E465435': -1}}}
```

With the policy ID `d3ac22db7e07e50823a7d8ac64feb29652f0dd15e0c8ad81e1cd89b2` , which is actually from this token `asdNFT6` - https://testnet.cardanoscan.io/token/d3ac22db7e07e50823a7d8ac64feb29652f0dd15e0c8ad81e1cd89b26173644e465436

Make sure your mint script is matching **exactly** the script that has been used to mint the token you are trying to burn.

**Comment by iliketowritecode** [comment]
> > 3. I've specified that I want to burn the "asdNFT5" token (with the negative amount):
> 
> You are specifying incorrect minting script.
> 
> The token in your input UTXO is this `asdNFT5` - https://testnet.cardanoscan.io/token/22aa930e3aa0d0c843b01fa529603929e04c8b5d82ecf2fac3bd10d56173644e465435
> 
> It has the policy ID `22aa930e3aa0d0c843b01fa529603929e04c8b5d82ecf2fac3bd10d5`
> 
> But in the transaction the calculated mint entry looks like this:
> 
> ```
> {h'D3AC22DB7E07E50823A7D8AC64FEB29652F0DD15E0C8AD81E1CD89B2': {h'6173644E465435': -1}}}
> ```
> 
> With the policy ID `d3ac22db7e07e50823a7d8ac64feb29652f0dd15e0c8ad81e1cd89b2` , which is actually from this token `asdNFT6` - https://testnet.cardanoscan.io/token/d3ac22db7e07e50823a7d8ac64feb29652f0dd15e0c8ad81e1cd89b26173644e465436
> 
> Make sure your mint script is matching **exactly** the script that has been used to mint the token you are trying to burn.

Thank you so much! Figured it out. You're a life saver!!!!! Thank you for all your time and assistance on this issue!

**Comment by iliketowritecode** [comment]
@vsubhuman in this example, how can I burn an item that is in a different wallet than what it was minted in. I can easily burn the NFT if it's in the minting wallet, but how could I burn it, say after I sent it to someone else?

**Comment by vsubhuman** [comment]
> but how could I burn it, say after I sent it to someone else?

@iliketowritecode , only the minter can burn tokens and only when they own them

**Comment by BurningManNFT** [comment]
Not as high-tech, but if you just want the NFT out of your wallet you can always send it to a "Burn Wallet". I use this one:  
addr1qxvenr7488ywrgyqw9zdgahhgu3fmjvtllqwrl7vt25yn5e5xha8um202d3vr2kr6ppf9wg9ttt4xwjghwwqd44npezqp6xq50
