### ISSUE TITLE
'UTxO Balance Insufficient' when attempting to build multi asset transaction

### ISSUE THREAD

**Issue by hazryder** [Emurgo/cardano-serialization-lib#434]
I'm having issues building multi-asset transactions using the serialization lib. I'm able to send transactions with a single asset without issue, but receive the error `'UTxO Balance Insufficient'` when attempting to call `add_inputs_from()` when sending multiple assets from a single policy.

My relevant code is as follows:

```
// Build and add outputs to tx
var txOutputBuilder = TransactionOutputBuilder.new()
txOutputBuilder = txOutputBuilder.with_address(shelleyRecipientAddr)
txOutputBuilder = txOutputBuilder.next()

var multiAsset = MultiAsset.new()

for(const policyId in sendAssets) {
    var assets = Assets.new()

    for(const sendAsset of sendAssets[policyId]) {
        assets.insert(
            AssetName.new(Buffer.from(sendAsset.name, "hex")),
            BigNum.from_str(sendAsset.quantity.toString())
        )
    }

    multiAsset.insert(
        ScriptHash.from_bytes(Buffer.from(policyId, "hex")),
        assets
    )
}

txOutputBuilder = txOutputBuilder.with_asset_and_min_required_coin(multiAsset, BigNum.from_str(protocolParams.coinsPerUtxoWord))

const txOutput = txOutputBuilder.build()

txBuilder.add_output(txOutput)

// Get utxos and provide tx inputs
const txUnspentOutputs = await this.getTxUnspentOutputs()

txBuilder.add_inputs_from(txUnspentOutputs, 3)
```

`sendAssets` is an object structured as follows, and can contain multiple assets under multiple policies:

```
{
    {POLICY_ID} : [
        {
            name: {ASSET_HEX_NAME_STR},
            quantity: 1
        },
        ...
    ],
    ...
}
```

I've tried changing the coin selection algo, restructuring the `MultiAsset` in various ways, restructuring the outputs to add one output per asset, but still get the same error message. Any help greatly appreciated, it's likely something simple in the asset/output structure that I've misunderstood.

**Comment by rahilparsana** [comment]
same issue

**Comment by raamb** [comment]
We are likely facing the same issue https://github.com/Emurgo/cardano-serialization-lib/issues/467

**Comment by hazryder** [comment]
@raamb Unfortunately I still haven't found a solution, I've pivoted to using Lucid JS for creating/submitting multiasset txs in the meantime.

**Comment by eric248550** [comment]
@raamb Is the issue solved while using Lucid?
Got the same issue

**Comment by AlexDochioiu** [comment]
This issue still seems to exist for almost every single multi-asset transaction. Any plans on fixing it?

**Comment by vsubhuman** [comment]
@hazryder or @AlexDochioiu , would that be possible for you to provide an incorrect transaction hex produced with this? Would help us investigate and reproduce

**Comment by AlexDochioiu** [comment]
@vsubhuman That's not possible. The transaction hex/cbor never gets built. `UTxO Balance Insufficient` is an error thrown when calling `txBuilder.add_inputs_from(txUnspentOutputs, 3)`.

**Comment by vsubhuman** [comment]
> That's not possible. The transaction hex/cbor never gets built. UTxO Balance Insufficient is an error thrown when calling txBuilder.add_inputs_from(txUnspentOutputs, 3).

@AlexDochioiu , good point. Would that be possible for you then to provide the exact list of UTxOs you are passing into `.add_inputs_from` and the exact outputs you have added to the builder before that? Ideally, we really need to know what exact task the function is trying to solve, to see where it gets it wrong

**Comment by mkeen** [comment]
One thing that has helped me while awaiting a more permanent fix is just attempting to build the TX multiple times. I try both Multi Asset selection algos (randomimprove multiple times, largestasset once if no successes from randomimprove). I'm left with an array of entries either empty (if an exception was thrown for the attempt) or with tx's in them. I then, inspect all of them and choose whatever one has the lowest fee, and that's the one I forward on to the user. A bit dirty, but works well. I have found that this RandomImprove issue is actually intermittent. Finally, it is possible using Lucid would help. It doesn't use serialization-lib under the hood. It uses https://github.com/dcSpark/cardano-multiplatform-lib, though I haven't investigated using it.

**Comment by hazryder** [comment]
@vsubhuman I'm afraid I don't have the code set up to repro this right now, as I reworked the project to use Lucid instead. When I've got some free time though I could potentially set it up again to help test.

**Comment by lisicky** [comment]
Thanks all! Fix for Random Improve Multi Asset will be in the next CSL release.

**Comment by Innocent-Akim** [comment]
Error: [Transaction] An error occurred during build: UTxO Balance Insufficient.
    at P.build (mesh.js?a9b7:1133:1)

**Comment by lisicky** [comment]
> Error: [Transaction] An error occurred during build: UTxO Balance Insufficient.
> at P.build (mesh.js?a9b7:1133:1)

Hi @Innocent-Akim ! Could you provide your code and utxos, that emits the error ? What CSL version do you use ?

**Comment by lisicky** [comment]
Hi @noroxi7 ! Could you create a new issue and provide code snippet and CSL version ?

**Comment by noroxi7** [comment]
> Hi [@noroxi7](https://github.com/noroxi7) ! Could you create a new issue and provide code snippet and CSL version ?

NOW DID!
