### ISSUE TITLE
Different between poolID and pool_keyhash

### ISSUE THREAD

**Issue by congle-engineer** [Emurgo/cardano-serialization-lib#45]
Hi all,

I don't know the difference between poolID and pool_keyhash. How to create a new pool_keyhash from poolID to make a new delegation transaction.
Pleae help to take a look. Thank you so much

**Comment by SebastienGllmt** [comment]
it's the same thing. In Shelley, the pool id is defined as the hash of the pool's owner key

**Comment by congle-engineer** [comment]
Hi @SebastienGllmt ,

Thank you so much. I want to ask one more question, please help.
I don't know how to convert "signing-key" to ed25519 format. Could you please help?

**Comment by SebastienGllmt** [comment]
What format is the signing key? Is it a BIP32PrivateKey ? A PrivateKey ? Or maybe it's the weird large key that cardano-cli uses? It's not enough information for me to help you

**Comment by SebastienGllmt** [comment]
I'm going to close this issue since the original question is answered
