### ISSUE TITLE
Failed to load source for dependency `cardano-serialization-lib`

### ISSUE THREAD

**Issue by nntruong96** [Emurgo/cardano-serialization-lib#451]
I try to run npm run android, and i have this issue.

"@emurgo/react-native-haskell-shelley": "^3.1.3",
"react": "^17.0.2",
"react-dom": "^17.0.2",
"react-native": "^0.68.2"

![image](https://user-images.githubusercontent.com/32155558/172790508-b80f4a72-819e-47c1-877e-bb2d87cd52fb.png)

**Comment by ozgrakkurt** [comment]
Hi, can you try [this fix](https://github.com/rust-lang/cargo/issues/2078#issuecomment-434388584)? I can't test it since I don't have android env setup

**Comment by lisicky** [comment]
You also can use this solution https://stackoverflow.com/a/11383587
