### ISSUE TITLE
PPViewHashesDon'tMatch Exception on submit transaction for Cardano serialization-lib version 10.0.x

### ISSUE THREAD

**Issue by HinaMunir-Hm** [Emurgo/cardano-serialization-lib#455]
On emurgo/cardano serialization versions 10.0.X receiving error on submit transaction that: https://drive.google.com/file/d/1SNpM1LtEDPnZPMQXdz1X_Ujiy_FW9BJW/view?usp=sharing

Also, in emurgo/cardano-serialization version 10.2.0 there is a function in TransactionBulderConfigBuilder.ex_unit_prices() that takes ExUnitPrices Instance, what is the numerator and denominator in ExUnitPrices.new() function, how can one calculates them?

**Comment by vsubhuman** [comment]
Hi, @HinaMunir-Hm! The hash error should not be happening on `10.2.0`, plz try and report if you still have the issue.

The ex-unit prices are a protocol parameter, same as linear fee values, for example, they are specified in the Alonzo genesis block and can potentially change with any epoch in case IOHK post a protocol parameter update. Current values for right now can be found here: https://github.com/Emurgo/cardano-serialization-lib/blob/master/rust/src/tx_builder.rs#L1529 

- Memory unit price is `577/10000`
- CPU unit price is `721/10000000`

**Comment by HinaMunir-Hm** [comment]
Hello, @vsubhuman! Here is the code that I am using and unable to understand why I receive PPViewHashesDon'tMatch exception on submit transaction. Did I missed something or doing something wrong?

`const finalizeTxForUpdateListing = async ({txBuilder, changeAddress,  utxos,  outputs,  datums,  metadata,  action,  assetUtxo,
  plutusScripts,  newListingDatum,  currentListingDatum,  datumHash,
}) => {

//Creating plutus witness
  const plutusWitness = Cardano.Instance.PlutusWitness.new(
    plutusScripts.get(0),
    currentListingDatum,
    action(assetUtxo.input().index().toString())
  );


//setting inputs
  const txInputsBuilder = Cardano.Instance.TxInputsBuilder.new();
  txInputsBuilder.add_plutus_script_input(
    plutusWitness,
    assetUtxo.input(),
    assetUtxo.output().amount()
  );
  txBuilder.set_inputs(txInputsBuilder);

//setting output
  txBuilder.add_output(outputs.get(0));
  const collateral = (await Wallet.getCollateral()).map((utxo) =>
    Cardano.Instance.TransactionUnspentOutput.from_bytes(fromHex(utxo))
  );

//setting collateral
  setCollateral(txBuilder, collateral);
  console.log(changeAddress);
  let inputs = Cardano.Instance.TransactionUnspentOutputs.new();
  utxos.forEach((utxo) => {
    inputs.add(utxo);
  });
//calculating script data hash
  const redeemers = Cardano.Instance.Redeemers.new();
  redeemers.add(action(assetUtxo.input().index().toString()));

  const scriptDataHash = Cardano.Instance.hash_script_data(
    redeemers,
    Cardano.Instance.TxBuilderConstants.plutus_default_cost_models(),
    datums
  ); 
  txBuilder.set_script_data_hash(scriptDataHash);

//adding inputs in transaction builder
  txBuilder.add_inputs_from(inputs, 2);

//adding changeAddress
  txBuilder.add_change_if_needed(changeAddress.to_address());

//Building transaction
  const tx = txBuilder.build_tx();

//signing transaction
  let txVkeyWitnesses = await Wallet.signTx(toHex(tx.to_bytes()), true); //signing transaction using wallet

  txVkeyWitnesses = Cardano.Instance.TransactionWitnessSet.from_bytes(
    fromHex(txVkeyWitnesses)
  );
  const signedTx = Cardano.Instance.Transaction.new(
    tx.body(),
    txVkeyWitnesses,
    tx.auxiliary_data()
  );
//Submitting transaction
  const txHash = await Wallet.submitTx(toHex(signedTx.to_bytes())); //Wallet.submitTx(toHex(signedTx.to_bytes()));

  return txHash;`

**Comment by vsubhuman** [comment]
> const scriptDataHash = Cardano.Instance.hash_script_data(
> redeemers,
> Cardano.Instance.TxBuilderConstants.plutus_default_cost_models(),
> datums
> );
> txBuilder.set_script_data_hash(scriptDataHash);

First **potential** problem is in the hash calculating itself, unfortunately there's no enough information for me to know if the parameters you are putting into the `hash_script_data` are correct and match the parameters you are using in the `PlutusWitness`.

Actually, the information you provide with the `PlutusWitness` should be enough for the builder to be able to auto-calculate the required script data hash, **try replacing `.set_script_data_hash` with this:**

```
txBuilder.calc_script_data_hash(
  Cardano.Instance.TxBuilderConstants.plutus_default_cost_models(),
);
```

Make sure to call this function after adding all the inputs so no other Plutus inputs are added after that.

//Building transaction
const tx = txBuilder.build_tx();

//signing transaction
let txVkeyWitnesses = await Wallet.signTx(toHex(tx.to_bytes()), true); //signing transaction using wallet

txVkeyWitnesses = Cardano.Instance.TransactionWitnessSet.from_bytes(
fromHex(txVkeyWitnesses)
);
const signedTx = Cardano.Instance.Transaction.new(
tx.body(),
txVkeyWitnesses,
tx.auxiliary_data()
);

Second probable problem is that from the call to sign transaction you need to make sure you are receiving back the witness set with the Plutus data still present. This might depend on which exactly wallet API you are integrating with. I.e. when you calling `.build_tx()` the `PlutusWitness` data you have added before is placed into the `WitnessSet` within the resulting transaction. After calling `.signTx` you receive a new instance of a `WitnessSet` and completely replace the previous one with the new one. You need to make sure the resulting witness set from the wallet still contains the script, the datum, and the redeemer (for example, Yoroi **does** make sure to preserve all the data present in the witness set before adding signatures, but cannot guarantee if it's same for all wallets). Not likely, but possible as a source of the problem.

**Comment by HinaMunir-Hm** [comment]
@vsubhuman you are right after .signTx I am receiving a new instance of witnessSet and completely replacing the previous one. 
Why is this happening and if we set the script, redeemer and datum again in WitnessSet it is only throwing PPViewHashesDon'tMatch exception is there any solution for this?

**Comment by HinaMunir-Hm** [comment]
@vsubhuman Thank you I found the issue was after calling .signTx I am receiving a new instance of a WitnessSet that completely replace the previous one with the new one.
