### ISSUE TITLE
Got MIN_UTXO_ERROR while building the transaction if user have too many NFTs 

### ISSUE THREAD

**Issue by eric248550** [Emurgo/cardano-serialization-lib#472]
I Got **MIN_UTXO_ERROR** while building the transaction if the user has too many NFTs 

Is there any solution or has anyone faced it?

**Comment by nicolasayotte** [comment]
Doing what call? What is the actual error text?

"Value {} less than the minimum UTXO value {}"

**Comment by lisicky** [comment]
Hi @eric248550 ! Do you still have that error ? Could you tell how you got it ?

**Comment by eric248550** [comment]
@nicolasayotte Yes the error is like this, I suspect the old version CSL version have fee calculation issue when the user's UTXO big

@lisicky it's min fee error, just increase the transaction fee it will solve

**Comment by lisicky** [comment]
@eric248550 You have the error only with a old CSL version, is it correct ? Could you tell what CSL version you use ?

**Comment by eric248550** [comment]
v9 have calculation error, using v10 works fine

**Comment by lisicky** [comment]
@eric248550 Thanks for your answer! : )
