### ISSUE TITLE
`CostModel` still follows `COST_MODEL_OP_COUNT = 166` limit in `babbage`

### ISSUE THREAD

**Issue by jy14898** [Emurgo/cardano-serialization-lib#473]
It's impossible to use the `get`/`set` interface for the PlutusV2 cost model, which has more than 166 operations

https://github.com/Emurgo/cardano-serialization-lib/blob/28a140e44c9d18cdf3c5c2821f7c911c93b8c41f/rust/src/plutus.rs#L203-L240

**Comment by vsubhuman** [comment]
Thank you, @jy14898 ! This is getting fixed asap and included into the beta.2 release

**Comment by vsubhuman** [comment]
Should be fixed in `11.0.0-rc.1`

**Comment by vsubhuman** [comment]
https://github.com/Emurgo/cardano-serialization-lib/releases/tag/11.0.0
