### ISSUE TITLE
Source of Plutus V1 cost model for Vasil

### ISSUE THREAD

**Issue by ignaciodopazo** [Emurgo/cardano-serialization-lib#477]
I'm curious about [where it comes from](https://github.com/Emurgo/cardano-serialization-lib/blob/a58bfa583297705ffc0fb03923cecef3452a6aee/rust/src/tx_builder_constants.rs#L31). I've taken a look at [this JSON](https://github.com/input-output-hk/cardano-node/blob/master/scripts/babbage/alonzo-babbage-test-genesis.json) but it doesn't seem to correspond under my eyes. If anyone can point me where the array comes from I'll be glad!

**Comment by vsubhuman** [comment]
Hi, @ignaciodopazo ! The cost-model been taken from the latest node version, the node API allows you to query the protocol parameters and it will output the current used cost-model. The cost-model just got updated, tho, so there will be a change to that part in the code soon.
