### ISSUE TITLE
Error: Cannot find module '@emurgo/cardano-serialization-lib-asmjs'

### ISSUE THREAD

**Issue by margueriteblair** [Emurgo/cardano-serialization-lib#479]
Just installed cardano-serialization-lib-asmjs as a need for non-WASM solution. Ran 'npm install --save @emurgo/cardano-serialization-lib-asmjs' and it's definitely in my package.json.

When I run tests for my code I get
`Error: Cannot find module '@emurgo/cardano-serialization-lib-asmjs'`

Is this a version issue? I've tried reverting to earlier versions with the same problem. I've tried 10.1.0 as well as 10.2.0.

**Comment by tengu-br** [comment]
Same issue here!

**Comment by waltonwells** [comment]
> Just installed cardano-serialization-lib-asmjs as a need for non-WASM solution. Ran 'npm install --save @emurgo/cardano-serialization-lib-asmjs' and it's definitely in my package.json.
> 
> When I run tests for my code I get `Error: Cannot find module '@emurgo/cardano-serialization-lib-asmjs'`
> 
> Is this a version issue? I've tried reverting to earlier versions with the same problem. I've tried 10.1.0 as well as 10.2.0.

not working for me too

**Comment by 1612492** [comment]
I have same issue. Any update?

**Comment by lisicky** [comment]
Hi! Do you still have the issue with cardano-serialization-lib-asmjs installation ?

**Comment by waltonwells** [comment]
Thanks for reaching  out!

Currently  I don't have any project on Cardano.
