### ISSUE TITLE
PPViewHashesDontMatch when spending from a script - `11.0.0-rc.6`

### ISSUE THREAD

**Issue by abdelkrimdev** [Emurgo/cardano-serialization-lib#482]
I'm trying to spend a UTXO from a script, this is how I'm calculating the script hash
```ts
    const redeemers = Cardano.Instance.Redeemers.new();
    redeemers.add(action(assetUtxo.input().index().toString()));

    const cost_model_vals = [
      205665, 812, 1, 1, 1000, 571, 0, 1, 1000, 24177, 4, 1, 1000, 32, 117366,
      10475, 4, 23000, 100, 23000, 100, 23000, 100, 23000, 100, 23000, 100,
      23000, 100, 100, 100, 23000, 100, 19537, 32, 175354, 32, 46417, 4, 221973,
      511, 0, 1, 89141, 32, 497525, 14068, 4, 2, 196500, 453240, 220, 0, 1, 1,
      1000, 28662, 4, 2, 245000, 216773, 62, 1, 1060367, 12586, 1, 208512, 421,
      1, 187000, 1000, 52998, 1, 80436, 32, 43249, 32, 1000, 32, 80556, 1,
      57667, 4, 1000, 10, 197145, 156, 1, 197145, 156, 1, 204924, 473, 1,
      208896, 511, 1, 52467, 32, 64832, 32, 65493, 32, 22558, 32, 16563, 32,
      76511, 32, 196500, 453240, 220, 0, 1, 1, 69522, 11687, 0, 1, 60091, 32,
      196500, 453240, 220, 0, 1, 1, 196500, 453240, 220, 0, 1, 1, 806990, 30482,
      4, 1927926, 82523, 4, 265318, 0, 4, 0, 85931, 32, 205665, 812, 1, 1,
      41182, 32, 212342, 32, 31220, 32, 32696, 32, 43357, 32, 32247, 32, 38314,
      32, 9462713, 1021, 10,
    ];

    const costModel = Cardano.Instance.CostModel.new();
    cost_model_vals.forEach((x, i) =>
      costModel.set(i, Cardano.Instance.Int.new_i32(x))
    );

    const costModels = Cardano.Instance.Costmdls.new();
    costModels.insert(Cardano.Instance.Language.new_plutus_v1(), costModel);

    const scriptDataHash = Cardano.Instance.hash_script_data(
      redeemers,
      costModels,
      datums
    );

    txBuilder.set_script_data_hash(scriptDataHash);
```

I even tried to use `calc_script_data_hash` with no luck both are giving me the exact same error
```ts
    txBuilder.calc_script_data_hash(
      Cardano.Instance.TxBuilderConstants.plutus_vasil_cost_models()
    );
```

And this is the error I'm getting after submit the TX:
```
"transaction submit error ShelleyTxValidationError ShelleyBasedEraBabbage (ApplyTxError [
    UtxowFailure (FromAlonzoUtxowFail (PPViewHashesDontMatch
        (SJust (SafeHash \"b00f8ac1832f8d201728e4195d4742a3703b6593a3cbbe45997f494536fd20cb\"))
        (SJust (SafeHash \"63d54a03986784ca1f304795ce40d5bc4f16369eab43384fa02fc6269557d96d\"))
    )
)])"
```

**Comment by alice1989123** [comment]
Exactly the same error. Have you changed cost_model_vals to the corresponding used in Cli? I am tryng to do that now

**Comment by jmagan** [comment]
The cost models are changed from the start of the epoch. Now you should use the cost model for Vasil. You can find them in the TxBuilderConstants.plutus_vasil_cost_models() method.

**Comment by jmagan** [comment]
I faced the same problem and I changed to TxBuilderConstants.plutus_vasil_cost_models() and it's working again.

**Comment by abdelkrimdev** [comment]
> I faced the same problem and I changed to TxBuilderConstants.plutus_vasil_cost_models() and it's working again.

I tried both `TxBuilderConstants.plutus_alonzo_cost_models()` and `TxBuilderConstants.plutus_vasil_cost_models()` still getting the `PPViewHashesDontMatch ` error

**Comment by vsubhuman** [comment]
> I'm trying to spend a UTXO from a script, this is how I'm calculating the script hash

Hi, @abdelkrimdev! Can you plz show how are you adding the input itself to the builder, with the datum and the redeemer? 

Also if it's possible for you to provide the datum and the redeemer itself or to provide the resulting transaction CBOR body - I could try and investigate the hash mismatch locally. In our internal tests we are successfully using both V1 and V2 script inputs using the cost-models from the `TxBuilderConstants`.

**Comment by jmagan** [comment]
> > I faced the same problem and I changed to TxBuilderConstants.plutus_vasil_cost_models() and it's working again.
> 
> I tried both `TxBuilderConstants.plutus_alonzo_cost_models()` and `TxBuilderConstants.plutus_vasil_cost_models()` still getting the `PPViewHashesDontMatch` error

I forget to mention that this was in testnet and with the 1.35.1 version of the node.

**Comment by abdelkrimdev** [comment]
> > I'm trying to spend a UTXO from a script, this is how I'm calculating the script hash
> 
> Hi, @abdelkrimdev! Can you plz show how are you adding the input itself to the builder, with the datum and the redeemer?
> 
> Also if it's possible for you to provide the datum and the redeemer itself or to provide the resulting transaction CBOR body - I could try and investigate the hash mismatch locally. In our internal tests we are successfully using both V1 and V2 script inputs using the cost-models from the `TxBuilderConstants`.

Yes sure here is the TX CBOR:
```
84a500828258204768790d1b4ba1a642b1f590ba2f9f6b665b30328dbd72163a50bbfc847c36af028258209f6f248ae74c80f2d644efa74100b58412b1569173e44647ad99d3ff01e9057600018282583900bea1c521df58f4eeef60c647e5ebd88c6039915409f9fd6454a476b91a8ea09e37b6bc2faa01088556b94a163a79c8a6cdd539d360cc7ad2821a001e8480a2581c9a4e855293a0b9af5e50935a331d83e7982ab5b738ea0e6fc0f9e656a14e4652414d455f38333030325f4c3001581ca183bf86925f66c579a3745c9517744399679b090927b8f6e2f2e1bba14f6164617065416d616e734576616e730182583900bea1c521df58f4eeef60c647e5ebd88c6039915409f9fd6454a476b91a8ea09e37b6bc2faa01088556b94a163a79c8a6cdd539d360cc7ad21a19895fdb021a000ebfe50b5820cc1f32d1dde95e1ced2d65d7abbd19a87357ce2e79c0d93afc54e3bf7afdb50b0d8182582045f3c89baf41567c72cd095d8ce7e63b04757a4f331efd80078896b0765da50801a400818258204bff8fd3673d18fc30d684d637871d5d4e7b7d6a6610640623eb0016aec8fc475840df5bf1c5d6849af4381b46629281d901c49117409e7f133224d3603a43e16f9f2e4e40c268d41f8cd30485a06d060d966fd7ebdce99fb60d8f958104ac44c8070381590e68590e650100003323322332233223232333222323332223233333333222222223233322232333322223232332232333222323332223232332233223232333332222233223322332233223322332222323232223232533530343330093333573466e1cd55cea803a400046664446660a2006004002666aa092eb9d71aba150073335504975ceb8d5d0a8031bae357426ae8940188d4128d4c12ccd5ce249035054310004c499263333573466e1cd55ce9baa0044800081308d4128d4c12ccd5ce249035054310004c499263333573466e1cd55cea8012400046601864646464646464646464646666ae68cdc39aab9d500a480008cccccccccc068cd40a08c8c8cccd5cd19b8735573aa0049000119810181d9aba15002302d357426ae8940088d4168d4c16ccd5ce249035054310005c49926135573ca00226ea8004d5d0a80519a8140149aba150093335502f75ca05c6ae854020ccd540bdd728171aba1500733502804435742a00c66a05066aa0aa09aeb4d5d0a8029919191999ab9a3370e6aae754009200023350223232323333573466e1cd55cea80124000466a05466a086eb4d5d0a80118241aba135744a00446a0bc6a60be66ae712401035054310006049926135573ca00226ea8004d5d0a8011919191999ab9a3370e6aae7540092000233502833504375a6ae854008c120d5d09aba2500223505e35305f3357389201035054310006049926135573ca00226ea8004d5d09aba2500223505a35305b3357389201035054310005c49926135573ca00226ea8004d5d0a80219a8143ae35742a00666a05066aa0aaeb88004d5d0a801181d1aba135744a00446a0ac6a60ae66ae71241035054310005849926135744a00226ae8940044d5d1280089aba25001135744a00226ae8940044d5d1280089aba25001135573ca00226ea8004d5d0a8011919191999ab9a3370ea00290031180f981e1aba135573ca00646666ae68cdc3a801240084603c608c6ae84d55cf280211999ab9a3370ea00690011180f18189aba135573ca00a46666ae68cdc3a80224000460426eb8d5d09aab9e50062350513530523357389201035054310005349926499264984d55cea80089baa001357426ae8940088d4128d4c12ccd5ce249035054310004c49926104b13504935304a3357389201035054350004b4984d55cf280089baa001135744a00226aae7940044dd50009109198008018011000911111111109199999999980080580500480400380300280200180110009109198008018011000891091980080180109000891091980080180109000891091980080180109000909111180200290911118018029091111801002909111180080290008919118011bac001320013550362233335573e0024a01c466a01a60086ae84008c00cd5d100101991919191999ab9a3370e6aae75400d200023330073232323333573466e1cd55cea8012400046601a60626ae854008cd404c0b4d5d09aba250022350363530373357389201035054310003849926135573ca00226ea8004d5d0a801999aa805bae500a35742a00466a01eeb8d5d09aba25002235032353033335738921035054310003449926135744a00226aae7940044dd50009110919980080200180110009109198008018011000899aa800bae75a224464460046eac004c8004d540c088c8cccd55cf80112804919a80419aa81998031aab9d5002300535573ca00460086ae8800c0b84d5d08008891001091091198008020018900089119191999ab9a3370ea002900011a80418029aba135573ca00646666ae68cdc3a801240044a01046a0526a605466ae712401035054310002b499264984d55cea80089baa001121223002003112200112001232323333573466e1cd55cea8012400046600c600e6ae854008dd69aba135744a00446a0466a604866ae71241035054310002549926135573ca00226ea80048848cc00400c00880048c8cccd5cd19b8735573aa002900011bae357426aae7940088d407cd4c080cd5ce24810350543100021499261375400224464646666ae68cdc3a800a40084a00e46666ae68cdc3a8012400446a014600c6ae84d55cf280211999ab9a3370ea00690001280511a8111a981199ab9c490103505431000244992649926135573aa00226ea8004484888c00c0104488800844888004480048c8cccd5cd19b8750014800880188cccd5cd19b8750024800080188d4068d4c06ccd5ce249035054310001c499264984d55ce9baa0011220021220012001232323232323333573466e1d4005200c200b23333573466e1d4009200a200d23333573466e1d400d200823300b375c6ae854014dd69aba135744a00a46666ae68cdc3a8022400c46601a6eb8d5d0a8039bae357426ae89401c8cccd5cd19b875005480108cc048c050d5d0a8049bae357426ae8940248cccd5cd19b875006480088c050c054d5d09aab9e500b23333573466e1d401d2000230133016357426aae7940308d407cd4c080cd5ce2481035054310002149926499264992649926135573aa00826aae79400c4d55cf280109aab9e500113754002424444444600e01044244444446600c012010424444444600a010244444440082444444400644244444446600401201044244444446600201201040024646464646666ae68cdc3a800a400446660106eb4d5d0a8021bad35742a0066eb4d5d09aba2500323333573466e1d400920002300a300b357426aae7940188d4040d4c044cd5ce2490350543100012499264984d55cea80189aba25001135573ca00226ea80048488c00800c888488ccc00401401000c80048c8c8cccd5cd19b875001480088c018dd71aba135573ca00646666ae68cdc3a80124000460106eb8d5d09aab9e500423500a35300b3357389201035054310000c499264984d55cea80089baa001212230020032122300100320011122232323333573466e1cd55cea80124000466aa01a600c6ae854008c014d5d09aba25002235007353008335738921035054310000949926135573ca00226ea800449848004800488848ccc00401000c0088004448848cc00400c008448004448c8c00400488cc00cc008008004c8c8c8ccc888c8c8c8cc88c8cc88c8c8c8ccc888ccc888cccccccc88888888cc88ccccc88888cccc8888cc88cc88cc88ccc888cc88ccc888cc88cc88cc88cc88c8c8c8c8cc88c8c8cccc8888c8cc88c8c8cc88888c8d4c01400ccc140cc0592412342656e65666963696172792773207369676e6174757265206e6f7420636f727265637400332235301c002222222222253353503133355301d1200133501f22533535033002210031001503225335305f333573466e3c0300041841804d40d0004540cc00c84184417d4004c124010cc140cc0592410d4e465431206e6f742073656e6400333504f5051333015330075001304900433550555504c3048004335505555017304800448008cc0592410d4e465432206e6f742073656e6400333504f5051333015330075001304900433550555504c30470043355055550173047004480084d4c05c0048800848004800488ccd54c0184800488cd54c034480048d4d5412c00488cd54138008cd54c040480048d4d5413800488cd54144008ccd4d5403c0048cc1692000001223305b00200123305a00148000004cd54c034480048d4d5412c00488cd54138008ccd4d540300048cd54c044480048d4d5413c00488cd54148008d5404c00400488ccd5540280580080048cd54c044480048d4d5413c00488cd54148008d54044004004ccd5540140440080054074d4c0540088888888888ccd54c0404800488d4c094008888d4c0b400c88cd4c14000894cd4c17cccd5cd19b8f013001061060133502e00500710072007502700911122233355300612001501c3355300b1200123535504900122335504c00235500d00133355300612001223535504a002225335305133355301012001323350132233353500b0032200200200135350090012200133500922533530530021055100105223535504d001223300a00200500610031335020004003501d0013355300b120012353550490012232335504d00330010053200135505522533535020001135500d0032213535504f00222533530563300c00200813355012007001130060030021221233001003002120013200135504c221122253353501a001100222133005002333553007120010050040011121222300300411221222330020050041121222300100411200132001355047221122533535014001150162213350173004002335530061200100400132001355046221122253353501400113535006003220012213335350080052200230040023335530071200100500400112212330010030021200122333573466e3c008004108104888c8c8c004014c8004d5411888cd4d4044005200022353550400022253353047333573466e3c0080241241204c01c0044c01800cc8004d5411488cd4d40400052000223535503f0022253353046333573466e3c00801c12011c40044c01800c894cd4c0f800441004cd5ce00101f8891a9aa81b800910009109198008018011000911111111109199999999980080580500480400380300280200180110009109198008018011000911091998008020018011000889100109109119800802001890009109198008018011000890911801001889100089000891091980080180109000891091980080180109000891091980080180109000890911180180208911001089110008900090911118020029091111801802909111180100290911118008029000910919800801801100090911111118038041109111111198030048041091111111802804091111110020911111100191091111111980100480411091111111980080480410009091180100191109119980080280200190009091180100190911800801900091a980200091100111a980180091100191a98010009110009110919980080200180110008891a9aa80100091001089109198008018010890008900091299a980200108008802891199ab9a3370e00400200a0082440042440024002224460040024466e00008004448c8c00400488cc00cc008008005049fd8799fd8799f581ca183bf86925f66c579a3745c9517744399679b090927b8f6e2f2e1bb4f6164617065416d616e734576616e73ffd8799f581c9a4e855293a0b9af5e50935a331d83e7982ab5b738ea0e6fc0f9e6564e4652414d455f38333030325f4c30ff581cbea1c521df58f4eeef60c647e5ebd88c6039915409f9fd6454a476b9ffff0581840001d87980821a006acfc01ab2d05e00f5f6
```

**Comment by abdelkrimdev** [comment]
> > > > I faced the same problem and I changed to TxBuilderConstants.plutus_vasil_cost_models() and it's working again.
> > > 
> > > 
> > > I tried both `TxBuilderConstants.plutus_alonzo_cost_models()` and `TxBuilderConstants.plutus_vasil_cost_models()` still getting the `PPViewHashesDontMatch` error
> > 
> > 
> > I forgot to mention that this was in testnet and with the 1.35.1 version of the node. Maybe that's help.
> 
> Ah, good point. @abdelkrimdev ! Please clarify if you are experiencing the issue on the testnet or on the mainnet?

I having this issue on `testnet`... mainnet works fine so far 🤞 😅

**Comment by vsubhuman** [comment]
> > > I'm trying to spend a UTXO from a script, this is how I'm calculating the script hash
> > 
> > 
> > Hi, @abdelkrimdev! Can you plz show how are you adding the input itself to the builder, with the datum and the redeemer?
> > Also if it's possible for you to provide the datum and the redeemer itself or to provide the resulting transaction CBOR body - I could try and investigate the hash mismatch locally. In our internal tests we are successfully using both V1 and V2 script inputs using the cost-models from the `TxBuilderConstants`.
> 
> Yes sure here is the TX CBOR:
> 
> ```
> 84a500828258204768790d1b4ba1a642b1f590ba2f9f6b665b30328dbd72163a50bbfc847c36af028258209f6f248ae74c80f2d644efa74100b58412b1569173e44647ad99d3ff01e9057600018282583900bea1c521df58f4eeef60c647e5ebd88c6039915409f9fd6454a476b91a8ea09e37b6bc2faa01088556b94a163a79c8a6cdd539d360cc7ad2821a001e8480a2581c9a4e855293a0b9af5e50935a331d83e7982ab5b738ea0e6fc0f9e656a14e4652414d455f38333030325f4c3001581ca183bf86925f66c579a3745c9517744399679b090927b8f6e2f2e1bba14f6164617065416d616e734576616e730182583900bea1c521df58f4eeef60c647e5ebd88c6039915409f9fd6454a476b91a8ea09e37b6bc2faa01088556b94a163a79c8a6cdd539d360cc7ad21a19895fdb021a000ebfe50b5820cc1f32d1dde95e1ced2d65d7abbd19a87357ce2e79c0d93afc54e3bf7afdb50b0d8182582045f3c89baf41567c72cd095d8ce7e63b04757a4f331efd80078896b0765da50801a400818258204bff8fd3673d18fc30d684d637871d5d4e7b7d6a6610640623eb0016aec8fc475840df5bf1c5d6849af4381b46629281d901c49117409e7f133224d3603a43e16f9f2e4e40c268d41f8cd30485a06d060d966fd7ebdce99fb60d8f958104ac44c8070381590e68590e650100003323322332233223232333222323332223233333333222222223233322232333322223232332232333222323332223232332233223232333332222233223322332233223322332222323232223232533530343330093333573466e1cd55cea803a400046664446660a2006004002666aa092eb9d71aba150073335504975ceb8d5d0a8031bae357426ae8940188d4128d4c12ccd5ce249035054310004c499263333573466e1cd55ce9baa0044800081308d4128d4c12ccd5ce249035054310004c499263333573466e1cd55cea8012400046601864646464646464646464646666ae68cdc39aab9d500a480008cccccccccc068cd40a08c8c8cccd5cd19b8735573aa0049000119810181d9aba15002302d357426ae8940088d4168d4c16ccd5ce249035054310005c49926135573ca00226ea8004d5d0a80519a8140149aba150093335502f75ca05c6ae854020ccd540bdd728171aba1500733502804435742a00c66a05066aa0aa09aeb4d5d0a8029919191999ab9a3370e6aae754009200023350223232323333573466e1cd55cea80124000466a05466a086eb4d5d0a80118241aba135744a00446a0bc6a60be66ae712401035054310006049926135573ca00226ea8004d5d0a8011919191999ab9a3370e6aae7540092000233502833504375a6ae854008c120d5d09aba2500223505e35305f3357389201035054310006049926135573ca00226ea8004d5d09aba2500223505a35305b3357389201035054310005c49926135573ca00226ea8004d5d0a80219a8143ae35742a00666a05066aa0aaeb88004d5d0a801181d1aba135744a00446a0ac6a60ae66ae71241035054310005849926135744a00226ae8940044d5d1280089aba25001135744a00226ae8940044d5d1280089aba25001135573ca00226ea8004d5d0a8011919191999ab9a3370ea00290031180f981e1aba135573ca00646666ae68cdc3a801240084603c608c6ae84d55cf280211999ab9a3370ea00690011180f18189aba135573ca00a46666ae68cdc3a80224000460426eb8d5d09aab9e50062350513530523357389201035054310005349926499264984d55cea80089baa001357426ae8940088d4128d4c12ccd5ce249035054310004c49926104b13504935304a3357389201035054350004b4984d55cf280089baa001135744a00226aae7940044dd50009109198008018011000911111111109199999999980080580500480400380300280200180110009109198008018011000891091980080180109000891091980080180109000891091980080180109000909111180200290911118018029091111801002909111180080290008919118011bac001320013550362233335573e0024a01c466a01a60086ae84008c00cd5d100101991919191999ab9a3370e6aae75400d200023330073232323333573466e1cd55cea8012400046601a60626ae854008cd404c0b4d5d09aba250022350363530373357389201035054310003849926135573ca00226ea8004d5d0a801999aa805bae500a35742a00466a01eeb8d5d09aba25002235032353033335738921035054310003449926135744a00226aae7940044dd50009110919980080200180110009109198008018011000899aa800bae75a224464460046eac004c8004d540c088c8cccd55cf80112804919a80419aa81998031aab9d5002300535573ca00460086ae8800c0b84d5d08008891001091091198008020018900089119191999ab9a3370ea002900011a80418029aba135573ca00646666ae68cdc3a801240044a01046a0526a605466ae712401035054310002b499264984d55cea80089baa001121223002003112200112001232323333573466e1cd55cea8012400046600c600e6ae854008dd69aba135744a00446a0466a604866ae71241035054310002549926135573ca00226ea80048848cc00400c00880048c8cccd5cd19b8735573aa002900011bae357426aae7940088d407cd4c080cd5ce24810350543100021499261375400224464646666ae68cdc3a800a40084a00e46666ae68cdc3a8012400446a014600c6ae84d55cf280211999ab9a3370ea00690001280511a8111a981199ab9c490103505431000244992649926135573aa00226ea8004484888c00c0104488800844888004480048c8cccd5cd19b8750014800880188cccd5cd19b8750024800080188d4068d4c06ccd5ce249035054310001c499264984d55ce9baa0011220021220012001232323232323333573466e1d4005200c200b23333573466e1d4009200a200d23333573466e1d400d200823300b375c6ae854014dd69aba135744a00a46666ae68cdc3a8022400c46601a6eb8d5d0a8039bae357426ae89401c8cccd5cd19b875005480108cc048c050d5d0a8049bae357426ae8940248cccd5cd19b875006480088c050c054d5d09aab9e500b23333573466e1d401d2000230133016357426aae7940308d407cd4c080cd5ce2481035054310002149926499264992649926135573aa00826aae79400c4d55cf280109aab9e500113754002424444444600e01044244444446600c012010424444444600a010244444440082444444400644244444446600401201044244444446600201201040024646464646666ae68cdc3a800a400446660106eb4d5d0a8021bad35742a0066eb4d5d09aba2500323333573466e1d400920002300a300b357426aae7940188d4040d4c044cd5ce2490350543100012499264984d55cea80189aba25001135573ca00226ea80048488c00800c888488ccc00401401000c80048c8c8cccd5cd19b875001480088c018dd71aba135573ca00646666ae68cdc3a80124000460106eb8d5d09aab9e500423500a35300b3357389201035054310000c499264984d55cea80089baa001212230020032122300100320011122232323333573466e1cd55cea80124000466aa01a600c6ae854008c014d5d09aba25002235007353008335738921035054310000949926135573ca00226ea800449848004800488848ccc00401000c0088004448848cc00400c008448004448c8c00400488cc00cc008008004c8c8c8ccc888c8c8c8cc88c8cc88c8c8c8ccc888ccc888cccccccc88888888cc88ccccc88888cccc8888cc88cc88cc88ccc888cc88ccc888cc88cc88cc88cc88c8c8c8c8cc88c8c8cccc8888c8cc88c8c8cc88888c8d4c01400ccc140cc0592412342656e65666963696172792773207369676e6174757265206e6f7420636f727265637400332235301c002222222222253353503133355301d1200133501f22533535033002210031001503225335305f333573466e3c0300041841804d40d0004540cc00c84184417d4004c124010cc140cc0592410d4e465431206e6f742073656e6400333504f5051333015330075001304900433550555504c3048004335505555017304800448008cc0592410d4e465432206e6f742073656e6400333504f5051333015330075001304900433550555504c30470043355055550173047004480084d4c05c0048800848004800488ccd54c0184800488cd54c034480048d4d5412c00488cd54138008cd54c040480048d4d5413800488cd54144008ccd4d5403c0048cc1692000001223305b00200123305a00148000004cd54c034480048d4d5412c00488cd54138008ccd4d540300048cd54c044480048d4d5413c00488cd54148008d5404c00400488ccd5540280580080048cd54c044480048d4d5413c00488cd54148008d54044004004ccd5540140440080054074d4c0540088888888888ccd54c0404800488d4c094008888d4c0b400c88cd4c14000894cd4c17cccd5cd19b8f013001061060133502e00500710072007502700911122233355300612001501c3355300b1200123535504900122335504c00235500d00133355300612001223535504a002225335305133355301012001323350132233353500b0032200200200135350090012200133500922533530530021055100105223535504d001223300a00200500610031335020004003501d0013355300b120012353550490012232335504d00330010053200135505522533535020001135500d0032213535504f00222533530563300c00200813355012007001130060030021221233001003002120013200135504c221122253353501a001100222133005002333553007120010050040011121222300300411221222330020050041121222300100411200132001355047221122533535014001150162213350173004002335530061200100400132001355046221122253353501400113535006003220012213335350080052200230040023335530071200100500400112212330010030021200122333573466e3c008004108104888c8c8c004014c8004d5411888cd4d4044005200022353550400022253353047333573466e3c0080241241204c01c0044c01800cc8004d5411488cd4d40400052000223535503f0022253353046333573466e3c00801c12011c40044c01800c894cd4c0f800441004cd5ce00101f8891a9aa81b800910009109198008018011000911111111109199999999980080580500480400380300280200180110009109198008018011000911091998008020018011000889100109109119800802001890009109198008018011000890911801001889100089000891091980080180109000891091980080180109000891091980080180109000890911180180208911001089110008900090911118020029091111801802909111180100290911118008029000910919800801801100090911111118038041109111111198030048041091111111802804091111110020911111100191091111111980100480411091111111980080480410009091180100191109119980080280200190009091180100190911800801900091a980200091100111a980180091100191a98010009110009110919980080200180110008891a9aa80100091001089109198008018010890008900091299a980200108008802891199ab9a3370e00400200a0082440042440024002224460040024466e00008004448c8c00400488cc00cc008008005049fd8799fd8799f581ca183bf86925f66c579a3745c9517744399679b090927b8f6e2f2e1bb4f6164617065416d616e734576616e73ffd8799f581c9a4e855293a0b9af5e50935a331d83e7982ab5b738ea0e6fc0f9e6564e4652414d455f38333030325f4c30ff581cbea1c521df58f4eeef60c647e5ebd88c6039915409f9fd6454a476b9ffff0581840001d87980821a006acfc01ab2d05e00f5f6
> ```
> 
> Edit: here is the error I'm getting after submit that particular TX
> 
> ```
> transaction submit error ShelleyTxValidationError ShelleyBasedEraBabbage (ApplyTxError [
>   UtxowFailure (FromAlonzoUtxowFail (PPViewHashesDontMatch
>     (SJust (SafeHash \"cc1f32d1dde95e1ced2d65d7abbd19a87357ce2e79c0d93afc54e3bf7afdb50b\"))
>     (SJust (SafeHash \"357041b88b914670a3b5e3b0861d47f2ac05ed4935ea73886434d8944aa6dfe0\"))
>   ))
> ])
> ```

@abdelkrimdev , plz provide the code on how you are adding the plutus input and which cost model you have used to calculate the hash, and also specify which library version exactly you have used to build it?


I have just tested hashing with the data and redeemers from your transaction and I am getting the correct hash that is expected in the error you have received:

<details>
  <summary>The full test code</summary>
  <pre class="notranslate">
  <code>
  use crate::tx_builder_constants::TxBuilderConstants;
        let pdata = PlutusList::from(vec![
            PlutusData::new_constr_plutus_data(
                &ConstrPlutusData::new(
                    &BigNum::zero(),
                    &PlutusList::from(vec![
                        PlutusData::new_constr_plutus_data(
                            &ConstrPlutusData::new(
                                &BigNum::zero(),
                                &PlutusList::from(vec![
                                    PlutusData::new_bytes(hex::decode("A183BF86925F66C579A3745C9517744399679B090927B8F6E2F2E1BB").unwrap()),
                                    PlutusData::new_bytes(hex::decode("6164617065416D616E734576616E73").unwrap())
                                ]),
                            ),
                        ),
                        PlutusData::new_constr_plutus_data(
                            &ConstrPlutusData::new(
                                &BigNum::zero(),
                                &PlutusList::from(vec![
                                    PlutusData::new_bytes(hex::decode("9A4E855293A0B9AF5E50935A331D83E7982AB5B738EA0E6FC0F9E656").unwrap()),
                                    PlutusData::new_bytes(hex::decode("4652414D455F38333030325F4C30").unwrap())
                                ]),
                            ),
                        ),
                        PlutusData::new_bytes(hex::decode("BEA1C521DF58F4EEEF60C647E5EBD88C6039915409F9FD6454A476B9").unwrap()),
                    ]),
                ),
            ),
        ]);
        let redeemers = Redeemers(vec![
            Redeemer::new(
                &RedeemerTag::new_spend(),
                &BigNum::one(),
                &PlutusData::new_empty_constr_plutus_data(&BigNum::zero()),
                &ExUnits::new(&to_bignum(7000000), &to_bignum(3000000000)),
            ),
        ]);
        let v1 = Language::new_plutus_v1();
        let v1_costmodel = TxBuilderConstants::plutus_vasil_cost_models().get(&v1).unwrap();
        let mut retained_cost_models = Costmdls::new();
        retained_cost_models.insert(&v1, &v1_costmodel);
        let hash = hash_script_data(
            &redeemers,
            &retained_cost_models,
            Some(pdata),
        );
        assert_eq!(hex::encode(hash.to_bytes()), "357041b88b914670a3b5e3b0861d47f2ac05ed4935ea73886434d8944aa6dfe0");
  </code>
  </pre>
</details>

**Comment by abdelkrimdev** [comment]
Hi @vsubhuman, here is the code I'm using:

This function to add the plutus script
```ts
const addPlutusScripts = (scripts, datum, redeemer, utxo, inputBuilder) => {
  const plutusWitness = Cardano.Instance.PlutusWitness.new(
    scripts.get(0),
    datum,
    redeemer(utxo.input().index().toString())
  );

  inputBuilder.add_plutus_script_input(
    plutusWitness,
    utxo.input(),
    utxo.output().amount()
  );
};
```

This to calculate the script hash
```ts
txBuilder.calc_script_data_hash(
  Cardano.Instance.TxBuilderConstants.plutus_alonzo_cost_models()
);
```

Those are the Protocol Parameters
```js
  {
    linearFee: {
      minFeeA: "44",
      minFeeB: "155381",
    },
    minUtxo: "4310",
    poolDeposit: "500000000",
    keyDeposit: "2000000",
    maxValSize: 5000,
    maxTxSize: 16384,
    priceMem: 0.0577,
    priceStep: 0.0000721,
    coinsPerUtxoWord: "4310",
  }
```

The version I'm using is: `11.0.0-rc.6`

**Comment by vsubhuman** [comment]
> This to calculate the script hash
> 
> ```ts
> txBuilder.calc_script_data_hash(
>   Cardano.Instance.TxBuilderConstants.plutus_alonzo_cost_models()
> );
> ```

@abdelkrimdev , for testnet you must be using `.plutus_vasil_cost_models()`

**Comment by abdelkrimdev** [comment]
Oh man, thank you!! you are the best 😁
so the `PPViewHashesDontMatch` is gone after I moved `calc_script_data_hash` all the way to the end just before calling `build_tx`

previously I was calling:
`calc_script_data_hash -> add_inputs_from -> add_change_if_needed -> build_tx`

the correct order is:
`add_inputs_from -> add_change_if_needed -> calc_script_data_hash -> build_tx`

**Comment by vsubhuman** [comment]
@alice1989123 , plz check if that might solve your issue as well - https://github.com/Emurgo/cardano-serialization-lib/issues/482#issuecomment-1189228086

**Comment by alice1989123** [comment]
> @alice1989123 , plz check if that might solve your issue as well - [#482 (comment)](https://github.com/Emurgo/cardano-serialization-lib/issues/482#issuecomment-1189228086)

Yes @vsubhuman your Rust code is a good reference on how to use the new protocol parameters. In Js it worked for me :
`    const costModel = wasm.TxBuilderConstants.plutus_vasil_cost_models().get(
      wasm.Language.new_plutus_v1()
    );

    const costModels = wasm.Costmdls.new();
    costModels.insert(wasm.Language.new_plutus_v1(), costModel);

   

    const scriptDataHash = wasm.hash_script_data(redeemers, costModels, datums);
    txBody.set_script_data_hash(scriptDataHash);`

**Comment by nmaddp1995** [comment]
I saw the example here https://dapp-connector-web.emurgo-rnd.com/ (https://github.com/Emurgo/dapp-connector-web)
still got this error when running the function SignSpendDatum. It's in the correct order that @abdelkrimdev mentioned above but still get the same error. Can anyone help me check that

**Comment by abdelkrimdev** [comment]
> I saw the example here https://dapp-connector-web.emurgo-rnd.com/ (https://github.com/Emurgo/dapp-connector-web) still got this error when running the function SignSpendDatum. It's in the correct order that @abdelkrimdev mentioned above but still get the same error. Can anyone help me check that

this is really strange sometimes it works sometimes it doesn't same code same TX CBOR I'm super confused 🤔

**Comment by nmaddp1995** [comment]
@abdelkrimdev you can try upgrading to version 11.0.0 to check if it works

**Comment by abdelkrimdev** [comment]
> @abdelkrimdev you can try upgrading to version 11.0.0 to check if it works

I already upgraded the version 🤔 it works perfectly fine when the datum is simple when I add nested lists it starts behaving weirdly
