### ISSUE TITLE
Sending token using cardano-serialization-lib 11rc6 to smart contract

### ISSUE THREAD

**Issue by AdamMachera** [Emurgo/cardano-serialization-lib#484]
I'm trying to move from version CSL 9.1.4 to 11rc6.

I'm using below code to create transaction:

`const nftMoveFixedPrice = "2000000";

export const offer = async (api: CardanoApi, policyId: string, assetName: string, askingPrice: string): Promise<string> => {

    const cardano = cardanoApiAdapter(api)
    const protocolParameters = await getProtocolProtocolParams()

    const txBuilder = await createTransactionBuilder(protocolParameters)
    const scriptAddress = getContractAddress();
    const shelleyChangeAddress = await cardano.getWalletAddress() 

    const selfAddress = await cardano.getWalletAddress()
    const baseAddress = BaseAddress.from_address(selfAddress)!
    const pkh = toHex(baseAddress.payment_cred().to_keyhash()?.to_bytes() as Uint8Array);

    const offerDatum = createSalesOfferDatum(pkh, askingPrice, policyId, assetName);
    const plutusData = toPlutusData(offerDatum);
    const offerDatumHash = hash_plutus_data(plutusData);

    let txOutputBuilder = TransactionOutputBuilder.new();
    txOutputBuilder = txOutputBuilder.with_address(scriptAddress);
    txOutputBuilder = txOutputBuilder.with_data_hash(offerDatumHash)

    const txOutputAmountBuilder = txOutputBuilder.next();

    const lovelaceWithAsset = getContractOutput(nftMoveFixedPrice, policyId, assetName)
    const txOutputAmountBuilderWithCoins = txOutputAmountBuilder.with_value(lovelaceWithAsset)

    const txOutput = txOutputAmountBuilderWithCoins.build();

    txBuilder.add_output(txOutput)

    // Find the available UTXOs in the wallet and
    const txUnspentOutputs  = TransactionUnspentOutputs.new();
    const walletOutputs  = await cardano.getUtxos();
    walletOutputs.forEach(utxo => txUnspentOutputs.add(utxo))
    txBuilder.add_inputs_from(txUnspentOutputs, 3)

    txBuilder.add_change_if_needed(shelleyChangeAddress)
    const txBody = txBuilder.build();

    const transactionWitnessSet = TransactionWitnessSet.new();

    const tx = Transaction.new(
        txBody,
        TransactionWitnessSet.from_bytes(transactionWitnessSet.to_bytes())
    )

    let signedtxVkeyWitnesses: TransactionWitnessSet
    try {
        signedtxVkeyWitnesses = await cardano.signTx(tx, true);
    }
    catch (err) {
        throw handleSignError(err)
    }

    transactionWitnessSet.set_vkeys(signedtxVkeyWitnesses.vkeys()!);

    const signedTx = Transaction.new(
        tx.body(),
        transactionWitnessSet
    );

    try {
        const txHash = await cardano.submitTx(signedTx);
        console.log(`txHash for sales offer: ${txHash}`);
        return txHash
    } catch (err) {
        appInsights.trackException({ exception: err as Error }, {
            sellerAddress: selfAddress.to_bech32(),
            sellerPkh: pkh,
            policyId: policyId,
            assetName: assetName,
            price: askingPrice,
            method: "offer"
        });
        console.log(err)
        throw err;
    }
}
`

The transaction cbor that is being submitted looks like this:
84a30082825820c139481dbd8397e67c7f72390c4ada188b1cee2a4e4420904749942c03cb38ab00825820f3677f992c1a232104e9c0fa874d6722a26515639cc3f90a11820aafc213b6b601018383581d70aab69a551fc931c565f5262bf9b2ccea846551d952e98535309e3f39821a001e8480a1581cee8e37676f6ebb8e031dff493f88ff711d24aa68666a09d61f1d3fb3a14f43727970746f44696e6f3038363938015820011b79818770e5a8190581c67d1a10adc2ada4f38987006f23a90f9f2439d4a58258390045f6a506a49a38263c4a8bbb2e1e369dd8732fb1f9a281f3e88383878727ae504f79d260b6024ac8590c934899b65734d835378badd32300821a0005da6aa4581c07e8df329b724e4be48ee32738125c06000de5448aaf93ed46d59e28a14844696e6f436f696e1904e2581c34b5b8c25f0ee8c44bac8f88dae27432759203ffb0ae558d847f08ffa95243727970746f44696e6f2d312d3030303034015243727970746f44696e6f2d312d3030303035015243727970746f44696e6f2d312d3030303036015243727970746f44696e6f2d312d3030303037015243727970746f44696e6f2d312d3030303038015243727970746f44696e6f2d312d3030303039015243727970746f44696e6f2d312d3030303131015243727970746f44696e6f2d312d3030303132015243727970746f44696e6f2d332d303030303001581ce61bfc106338ed4aeba93036324fbea8150fd9750fcffca1cd9f1a19a34f44696e6f536176696f723030313133014f44696e6f536176696f723030343034014f44696e6f536176696f72303034353001581cee8e37676f6ebb8e031dff493f88ff711d24aa68666a09d61f1d3fb3a74f43727970746f44696e6f3035393839014f43727970746f44696e6f3036323734014f43727970746f44696e6f3036333039014f43727970746f44696e6f3036353332014f43727970746f44696e6f3037383933014f43727970746f44696e6f3037393336014f43727970746f44696e6f3038323532018258390045f6a506a49a38263c4a8bbb2e1e369dd8732fb1f9a281f3e88383878727ae504f79d260b6024ac8590c934899b65734d835378badd323001a73a0dd79021a0002ff51a10081825820729b9d4d9df2d95ef199ec817242534f9e649fef8fccfce5880b909ae10efcdd58402883b36aa1ba745109a1c526ec8e2742ce9400754dc9f23dbb48c49d5413d867390cbeaf6bc2ea076323359553ff7e4b18c3c5767b382415a525974d4556ce05f5f6

Once decoded:
`[{0: [[h'C139481DBD8397E67C7F72390C4ADA188B1CEE2A4E4420904749942C03CB38AB', 0], [h'F3677F992C1A232104E9C0FA874D6722A26515639CC3F90A11820AAFC213B6B6', 1]], 1: [[h'70AAB69A551FC931C565F5262BF9B2CCEA846551D952E98535309E3F39', [2000000, {h'EE8E37676F6EBB8E031DFF493F88FF711D24AA68666A09D61F1D3FB3': {h'43727970746F44696E6F3038363938': 1}}], h'011B79818770E5A8190581C67D1A10ADC2ADA4F38987006F23A90F9F2439D4A5'], [h'0045F6A506A49A38263C4A8BBB2E1E369DD8732FB1F9A281F3E88383878727AE504F79D260B6024AC8590C934899B65734D835378BADD32300', [383594, {h'07E8DF329B724E4BE48EE32738125C06000DE5448AAF93ED46D59E28': {h'44696E6F436F696E': 1250}, h'34B5B8C25F0EE8C44BAC8F88DAE27432759203FFB0AE558D847F08FF': {h'43727970746F44696E6F2D312D3030303034': 1, h'43727970746F44696E6F2D312D3030303035': 1, h'43727970746F44696E6F2D312D3030303036': 1, h'43727970746F44696E6F2D312D3030303037': 1, h'43727970746F44696E6F2D312D3030303038': 1, h'43727970746F44696E6F2D312D3030303039': 1, h'43727970746F44696E6F2D312D3030303131': 1, h'43727970746F44696E6F2D312D3030303132': 1, h'43727970746F44696E6F2D332D3030303030': 1}, h'E61BFC106338ED4AEBA93036324FBEA8150FD9750FCFFCA1CD9F1A19': {h'44696E6F536176696F723030313133': 1, h'44696E6F536176696F723030343034': 1, h'44696E6F536176696F723030343530': 1}, h'EE8E37676F6EBB8E031DFF493F88FF711D24AA68666A09D61F1D3FB3': {h'43727970746F44696E6F3035393839': 1, h'43727970746F44696E6F3036323734': 1, h'43727970746F44696E6F3036333039': 1, h'43727970746F44696E6F3036353332': 1, h'43727970746F44696E6F3037383933': 1, h'43727970746F44696E6F3037393336': 1, h'43727970746F44696E6F3038323532': 1}}]], [h'0045F6A506A49A38263C4A8BBB2E1E369DD8732FB1F9A281F3E88383878727AE504F79D260B6024AC8590C934899B65734D835378BADD32300', 1939922297]], 2: 196433}, {0: [[h'729B9D4D9DF2D95EF199EC817242534F9E649FEF8FCCFCE5880B909AE10EFCDD', h'2883B36AA1BA745109A1C526EC8E2742CE9400754DC9F23DBB48C49D5413D867390CBEAF6BC2EA076323359553FF7E4B18C3C5767B382415A525974D4556CE05']]}, true, null]`

The exception that I'm getting is:
"
message: "\"transaction submit error ShelleyTxValidationError ShelleyBasedEraBabbage (ApplyTxError [UtxowFailure (UtxoFailure (BabbageOutputTooSmallUTxO [((Addr Testnet (KeyHashObj (KeyHash \\\"45f6a506a49a38263c4a8bbb2e1e369dd8732fb1f9a281f3e8838387\\\")) (StakeRefBase (KeyHashObj (KeyHash \\\"8727ae504f79d260b6024ac8590c934899b65734d835378badd32300\\\"))),Value 383594 (fromList [(PolicyID {policyID = ScriptHash \\\"07e8df329b724e4be48ee32738125c06000de5448aaf93ed46d59e28\\\"},fromList [(44696e6f436f696e,1250)]),(PolicyID {policyID = ScriptHash \\\"34b5b8c25f0ee8c44bac8f88dae27432759203ffb0ae558d847f08ff\\\"},fromList [(43727970746f44696e6f2d312d3030303034,1),(43727970746f44696e6f2d312d3030303035,1),(43727970746f44696e6f2d312d3030303036,1),(43727970746f44696e6f2d312d3030303037,1),(43727970746f44696e6f2d312d3030303038,1),(43727970746f44696e6f2d312d3030303039,1),(43727970746f44696e6f2d312d3030303131,1),(43727970746f44696e6f2d312d3030303132,1),(43727970746f44696e6f2d332d3030303030,1)]),(PolicyID {policyID = ScriptHash \\\"e61bfc106338ed4aeba93036324fbea8150fd9750fcffca1cd9f1a19\\\"},fromList [(44696e6f536176696f723030313133,1),(44696e6f536176696f723030343034,1),(44696e6f536176696f723030343530,1)]),(PolicyID {policyID = ScriptHash \\\"ee8e37676f6ebb8e031dff493f88ff711d24aa68666a09d61f1d3fb3\\\"},fromList [(43727970746f44696e6f3035393839,1),(43727970746f44696e6f3036323734,1),(43727970746f44696e6f3036333039,1),(43727970746f44696e6f3036353332,1),(43727970746f44696e6f3037383933,1),(43727970746f44696e6f3037393336,1),(43727970746f44696e6f3038323532,1)])]),NoDatum,SNothing),Coin 3073030)]))])\""
"

Any idea why it might not be working. 
I'm signing transaction using nami wallet.

**Comment by vsubhuman** [comment]
Hi, @AdamMachera ! Please clarify what protocol parameters values do you have and how exactly the transaction builder is created

**Comment by AdamMachera** [comment]
Thanks for getting back @vsubhuman.

This is how I construct transaction builder:

`
export const createTransactionBuilder = async (protocolParams: CardanoProtocolParameters) => {
    //tempary skip parameters taken from the blockfrost and use below ones
    const params = {
        linearFee: {
          minFeeA: "44",
          minFeeB: "155381",
        },
        minUtxo: "4310",
        poolDeposit: "500000000",
        keyDeposit: "2000000",
        maxValSize: 5000,
        maxTxSize: 16384,
        priceMem: 0.0577,
        priceStep: 0.0000721,
        coinsPerUtxoWord: "4310",
    }

    const txBuilder = TransactionBuilder.new(
        TransactionBuilderConfigBuilder.new()
            .fee_algo(LinearFee.new(BigNum.from_str(params.linearFee.minFeeA), BigNum.from_str(params.linearFee.minFeeB)))
            .pool_deposit(BigNum.from_str(params.poolDeposit))
            .key_deposit(BigNum.from_str(params.keyDeposit))
            .coins_per_utxo_word(BigNum.from_str(params.coinsPerUtxoWord))
            .max_value_size(params.maxValSize)
            .max_tx_size(params.maxTxSize)
            .prefer_pure_change(true)
            .build()
    );

    return txBuilder
}`

**Comment by vsubhuman** [comment]
> coinsPerUtxoWord: "4310",

Yup, the value `4310` is coins per utxo **byte**, not per utxo **word**. The correct value of coins per utxo **word** is `34482`.

You need to call `.coins_per_utxo_byte` on the TransactionBuilderConfigBuilder builder, instead of deprecated `.coins_per_utxo_word`.

**Comment by AdamMachera** [comment]
Thanks it worked.

```
    const params = {
        linearFee: {
          minFeeA: "44",
          minFeeB: "155381",
        },
        minUtxo: "4310",
        poolDeposit: "500000000",
        keyDeposit: "2000000",
        maxValSize: 5000,
        maxTxSize: 16384,
        priceMem: 0.0577,
        priceStep: 0.0000721,
        coinsPerUtxoWord: "4310"
    }

    const txBuilder = TransactionBuilder.new(
        TransactionBuilderConfigBuilder.new()
            .fee_algo(LinearFee.new(BigNum.from_str(params.linearFee.minFeeA), BigNum.from_str(params.linearFee.minFeeB)))
            .pool_deposit(BigNum.from_str(params.poolDeposit))
            .key_deposit(BigNum.from_str(params.keyDeposit))
            .coins_per_utxo_byte(BigNum.from_str(params.coinsPerUtxoWord))
            .max_value_size(params.maxValSize)
            .max_tx_size(params.maxTxSize)
            .prefer_pure_change(true)
            .build()
    );

    return txBuilder
```
