### ISSUE TITLE
private TxInputsBuilder

### ISSUE THREAD

**Issue by maxtori** [Emurgo/cardano-serialization-lib#492]
The whole tx_inputs_builder module is set to private, which makes impossible to use TransactionBuilder::{set_inputs, set_collateral}.

**Comment by lisicky** [comment]
Hi @maxtori ! How do you import `TxInputsBuilder` ? Just checked this this line and everything was fine. 

```
use cardano_serialization_lib::tx_builder::tx_inputs_builder::TxInputsBuilder;
```
