### ISSUE TITLE
Fee calculation error: FeeTooSmallUTxO

### ISSUE THREAD

**Issue by prodderman** [Emurgo/cardano-serialization-lib#496]
Hi! I get a partial transaction created by PAB, try to balance it, calculate fee and submit it to testnet but I always get this error:
> transaction submit error ShelleyTxValidationError ShelleyBasedEraBabbage (ApplyTxError [UtxowFailure (UtxoFailure (FromAlonzoUtxoFail (FeeTooSmallUTxO (Coin 172629) (Coin 171265))))])

I've checked all other similar issues but they didn't help.

This is a silly transaction that lock some ada (100 ADA) in a smart contract with datum (public key hash). It has only one output, one required signer and there are no any plutus scripts, native scripts, other assets, auxiliary data, metadata and so on.

@emurgo/cardano-serialization-lib-browser: "11.0.0"
nami-wallet: 3.2.5
cardano-node: 1.35.2

PAB response
```
{
    inputs: [],
    redeemers: [],
    transaction: '84a600800d80018183581d701395201dc505b14f3ff52246501109c65b13866f671d6d21f8f85ee01a05f5e10058205b04431c5c5695c4e10c5755cf2181ac55da0dd5789770235e98199fea2914e802000e81581c99b407d1ee17fe8e2a0920e053def7ab2a6b5beadf6be04c10bcc7be0b5820d0b130d5ac899a4e2ec7e1d16d259956a2c05814df45976622c82221124966dca10481d8799f581c99b407d1ee17fe8e2a0920e053def7ab2a6b5beadf6be04c10bcc7befff5f6'
}
```

<details>
  <summary>Simplified code</summary>
  
  ```typescript
// https://playground.plutus.iohkdev.io/doc/haddock/plutus-contract/html/Plutus-Contract-Wallet.html#t:ExportTx
type ExportTx = {
    transaction: string,
    inputs: ExportTxInput[],
    redeemers: ExportTxRedeemer[]
}

const balanceTx = async ({ transaction }: ExportTx) => {
    // create txBuilderConfig acconding to https://adapools.org/protocol-parameters
    const linearFee = LinearFee.new(BigNum.from_str('44'), BigNum.from_str('155381'));
    const memoryUnitInterval = UnitInterval.new(BigNum.from_str('577'), BigNum.from_str('10000'));
    const stepsUnitInterval = UnitInterval.new(BigNum.from_str('721'), BigNum.from_str('10000000'));
    const exUnitPrices = ExUnitPrices.new(memoryUnitInterval, stepsUnitInterval);
    const config = TransactionBuilderConfigBuilder.new()
        .fee_algo(linearFee)
        .max_tx_size(16384)
        .key_deposit(BigNum.from_str('2000000'))
        .pool_deposit(BigNum.from_str('500000000'))
        .max_value_size(5000)
        .coins_per_utxo_byte(BigNum.from_str('4310'))
        .prefer_pure_change(true)
        .ex_unit_prices(exUnitPrices)
        .build();

    const txBuilder = TransactionBuilder.new(config);
    const partialTx = Transaction.from_bytes(Buffer.from(transaction, 'hex'));

    const outputs = partialTx.body().outputs();
    for (let idx = 0; idx < outputs.len(); idx++) {
        const output = outputs.get(idx);
        txBuilder.add_output(output);
     }

    const rquiredSigners = partialTx.body().required_signers();
    if (signers) {
        for (let idx = 0; idx < signers.len(); idx++) {
            const signer = signers.get(idx);
            txBuilder.add_required_signer(signer);
        }
    }

    const scriptDataHash = partialTx.body().script_data_hash();
    if (scriptDataHash) {
        txBuilder.set_script_data_hash(scriptDataHash);
    }

    const walletApi = await window.cardano?.nami?.enable()!;
    const utxos = (await walletApi.getUtxos()) ?? [];
    const walletOutputs = TransactionUnspentOutputs.new();
    utxos.forEach(utxo =>
        walletOutputs.add(TransactionUnspentOutput.from_bytes(Buffer.from(utxo, 'hex')))
    );
    txBuilder.add_inputs_from(walletOutputs, CoinSelectionStrategyCIP2.LargestFirst);

    const changeAddress = await walletApi.getChangeAddress();
    const deserializedChangeAddress = Address.from_bytes(Buffer.from(changeAddress, 'hex'));
    txBuilder.add_change_if_needed(deserializedChangeAddress);

    const txBody = txBuilder.build();
    const balancedTx = Transaction.new(txBody, partialTx.witness_set(), partialTx.auxiliary_data());

    // sign transaction
    const witnessSet = await walletApi.signTx(
        Buffer.from(balancedTx.to_bytes()).toString('hex'),
        true
    );
    const deserializedWitnessSet = TransactionWitnessSet.from_bytes(Buffer.from(witnessSet, 'hex'));
    const currentWitnessSet = balancedTx.witness_set();
    const signatures = deserializedWitnessSet.vkeys()!;
    currentWitnessSet.set_vkeys(signatures);
    const signedTx = Transaction.new(
        balancedTx.body(),
        currentWitnessSet,
        balancedTx.auxiliary_data()
    );

    const txHash = await walletApi.submitTx(Buffer.from(signedTx.to_bytes()).toString('hex'));

    return txHash;
};

// usage
const transaction = '...' // CBOR
balanceTx({ inputs: [], redeemers: [], transaction })
```
</details>

Final signed transaction:
> 84a50081825820e55d17e4145d29184d9d29dcf959287bacba677fe5663395ee74c4397ef88c7901018283581d701395201dc505b14f3ff52246501109c65b13866f671d6d21f8f85ee01a05f5e10058205b04431c5c5695c4e10c5755cf2181ac55da0dd5789770235e98199fea2914e88258390099b407d1ee17fe8e2a0920e053def7ab2a6b5beadf6be04c10bcc7be8643b8a82ef61ad98b4577d44c796335b31ad4b17ec9794645cda2951a29b144b5021a00029d010b5820d0b130d5ac899a4e2ec7e1d16d259956a2c05814df45976622c82221124966dc0e81581c99b407d1ee17fe8e2a0920e053def7ab2a6b5beadf6be04c10bcc7bea20081825820c00546065dc900b006aeb12817d22c66d298f46d1d0666b685e759cbe9f46dab5840a5efebbf21d2d62b20c175f26654c8ea57bdeee5c4d038a452892a0908b4fc437c730ef13025a02840644c6ea35a741c8479d024d16dff65b517be85010e620b0481d8799f581c99b407d1ee17fe8e2a0920e053def7ab2a6b5beadf6be04c10bcc7befff5f6

Am I doing something wrong? Thanks!

**Comment by prodderman** [comment]
I found this [issue](https://github.com/Emurgo/cardano-serialization-lib/issues/443) and it seems the library really doesn't take into account datum hashes size.

**Comment by vsubhuman** [comment]
@prodderman , you resulting transaction contains an arbitrary datum in the field 4 of the witness set : 

![image](https://user-images.githubusercontent.com/5585355/184115998-055f4e16-48a2-4e8f-ad06-4c6e8409086f.png)

As you can see in the code, the builder performs the fee size estimation before you create the full transaction and place that witness set to be a part of that full transaction:

![image](https://user-images.githubusercontent.com/5585355/184116078-1eb19925-2787-40e1-bf89-6fd5023e090a.png)

This the transaction-builder has no information that you want to have that additional arbitrary datum in the witness set and there's no protocol logic that would require for that datum to be there. And therefore the builder cannot in any reasonable way guess that the transaction size must be larger than what it has estimated it to be. The only reason to include datums into witness sets is when you **spend** Plutus inputs. If you are just locking funds with a Plutus script address - you don't need to include the datum in the witness-set, you only put the datum hash as a part of the output. If you really want for the datum itself to be on-chain as a part of the same transaction, for some logic, you should rather use new inlined datums available in the new protocol version (note, available only on the testnet for now), for that you need to include the datum itself into the output instead of a datum hash.

**Comment by prodderman** [comment]
@vsubhuman It works. Thank you
