### ISSUE TITLE
Utxos MissingVKeyWitnessesUTXOW, ValueNotConservedUTxO 11.0.1

### ISSUE THREAD

**Issue by francisluz** [Emurgo/cardano-serialization-lib#502]
Hey guys,

We're having this. we send our utxos to the dApp, then we sign and when the dApp tries to send it we get this.
`{"error":"Bad Request","message":"\"transaction submit error ShelleyTxValidationError ShelleyBasedEraBabbage (ApplyTxError [UtxowFailure (FromAlonzoUtxowFail (WrappedShelleyEraFailure (MissingVKeyWitnessesUTXOW (WitHashes (fromList [KeyHash \\\"fb48f4bce10f8339e5413031842e8b38c12720595b2cc324f41c3023\\\"]))))),UtxowFailure (UtxoFailure (FromAlonzoUtxoFail (ValueNotConservedUTxO (Value 1230000 (fromList [])) (Value 953750638 (fromList [])))))])\"","status_code":400}`

And this KeyHash `fb48f4bce10f8339e5413031842e8b38c12720595b2cc324f41c3023` is from the output account which shouldn't be consider here.

Here's how we parse the Utxos from blockfrost:
```
const input = instance.TransactionUnspentOutput.new(
    instance.TransactionInput.new(
        instance.TransactionHash.from_bytes(
            Buffer.from(utxo.txHash, 'hex')
        ),
        instance.BigNum.from_str(
            utxo.outputIndex.toString()
        )
    ),
    instance.TransactionOutput.new(
        instance.Address.from_bech32(addr),
        assetsToValue(instance, utxo.amount)
    )
);
```

When we build the transaction using `cardano-multiplatform-lib ` and send it all goes well.

**Comment by lisicky** [comment]
Hi @francisluz! Could you provide the code with cardano-serialization-lib and cardano-multiplatform-lib and cbor from both of them ?

**Comment by francisluz** [comment]
Hey @lisicky,

Following below the details ;)

This issue is happing with two old accounts I have on Testnet, I run a test with a brand new wallet with only ADA and both codes below worked.

**TxSigned Hex**
`84a3008182582096f90c12ef1a193d8d0ca93fe2015da68f8233acd9429047f9c9f08ee73930f20001828258390085e76ddb90294e1cb03596acf111631c0d3070f5b7e74fb8136de6690bee88503f60afc7730731db3bdc45a2a3ecba4469f0645dc2373ebd1a00e4e1c0825839005f7f150f55cc0e3ce6d4e2d7f6b6a5f650f2c8a7cbc1d45540f02377258566d39cabb7ec800d2789d2fe116a4d28c4911b3091bc545975b31a37f1a239021a00029075a1008182582010333f1716e720ec2b9bb3b770f5667aa46cc1e4980f4ab2fd7cb0d8426da1cc5840bd49db44ff8959d961362f7d714b229bf3c444137ebb46147ad1a526e09dbfc127c44d8efc942a22d06d0c1e21106bcba18eea64879c1371725c8e0854983901f5f6`

**Error message:**
`{"error":"Bad Request","message":"\"transaction submit error ShelleyTxValidationError ShelleyBasedEraBabbage (ApplyTxError [UtxowFailure (FromAlonzoUtxowFail (WrappedShelleyEraFailure (MissingVKeyWitnessesUTXOW (WitHashes (fromList [KeyHash \\\"fb48f4bce10f8339e5413031842e8b38c12720595b2cc324f41c3023\\\"]))))),UtxowFailure (UtxoFailure (FromAlonzoUtxoFail (ValueNotConservedUTxO (Value 1230000 (fromList [])) (Value 953750638 (fromList [])))))])\"","status_code":400}
`


**CODE: cardano-serialization-lib**
``` ts
const serializationLib = await loadCardanoWasm();

const protocolParams = {
    linearFee: {
        minFeeA: '44',
        minFeeB: '155381'
    },
    minUtxo: '34482',
    poolDeposit: '500000000',
    keyDeposit: '2000000',
    maxValSize: 5000,
    maxTxSize: 16384,
    priceMem: 0.0577,
    priceStep: 0.0000721,
    coinsPerUtxoWord: '34482'
};

const txBuilder = serializationLib.TransactionBuilder.new(
    serializationLib.TransactionBuilderConfigBuilder.new()
        .fee_algo(
            serializationLib.LinearFee.new(
                serializationLib.BigNum.from_str(protocolParams.linearFee.minFeeA),
                serializationLib.BigNum.from_str(protocolParams.linearFee.minFeeB)
            )
        )
        .pool_deposit(serializationLib.BigNum.from_str(protocolParams.poolDeposit))
        .key_deposit(serializationLib.BigNum.from_str(protocolParams.keyDeposit))
        .coins_per_utxo_word(serializationLib.BigNum.from_str(protocolParams.coinsPerUtxoWord))
        .max_value_size(protocolParams.maxValSize)
        .max_tx_size(protocolParams.maxTxSize)
        .prefer_pure_change(true)
        .build()
);

const { address, lovelaceAmount, changeAddress } = paymentDetails;
const shelleyOutputAddress = serializationLib.Address.from_bech32(address);

txBuilder.add_output(
    serializationLib.TransactionOutput.new(
        shelleyOutputAddress,
        serializationLib.Value.new(serializationLib.BigNum.from_str(lovelaceAmount))
    )
);

if (feeDetails) {
    const feeOutputAddress = serializationLib.Address.from_bech32(feeDetails.address);
    txBuilder.add_output(
        serializationLib.TransactionOutput.new(
            feeOutputAddress,
            serializationLib.Value.new(serializationLib.BigNum.from_str(feeDetails.lovelaceAmount))
        )
    );
}

const rawUtxos = await this.getUtxos();
const txUnspentOutputs = rawUtxos.reduce((acc, utxo) => {
    const fromBytes = serializationLib.TransactionUnspentOutput.from_bytes(Buffer.from(utxo, 'hex'));
    acc.add(fromBytes);
    return acc;
}, serializationLib.TransactionUnspentOutputs.new());

txBuilder.add_inputs_from(txUnspentOutputs, 0);

const shelleyChangeAddress = serializationLib.Address.from_bech32(changeAddress);
txBuilder.add_change_if_needed(shelleyChangeAddress);

const transaction = serializationLib.Transaction.new(
    txBuilder.build(),
    serializationLib.TransactionWitnessSet.new()
);

return Buffer.from(transaction.to_bytes()).toString('hex');
```

**Same UTXO SET Working here:**

**TxSigned Hex**
`84a4008182582096f90c12ef1a193d8d0ca93fe2015da68f8233acd9429047f9c9f08ee73930f201018282583900fb48f4bce10f8339e5413031842e8b38c12720595b2cc324f41c3023a16ca9964c9f0a8123831bb730b48d86c1abb83848b1b3a22ad23a621a05f5e100825839005f7f150f55cc0e3ce6d4e2d7f6b6a5f650f2c8a7cbc1d45540f02377258566d39cabb7ec800d2789d2fe116a4d28c4911b3091bc545975b31a32e0a1f1021a0002917d031a03fc20a3a1008182582010333f1716e720ec2b9bb3b770f5667aa46cc1e4980f4ab2fd7cb0d8426da1cc58400da130197ee835d42565add66d1e12b63284d59d769b11b3a6c0dd7299a6524024ed30d3318408db85767a2856c0c2cf168a15e3665cde90c8a8bb4cf5163600f5f6`


**CODE: cardano-multiplatform-lib**
``` ts
const txBuilderConfig = this.Cardano.TransactionBuilderConfigBuilder.new()
    .coins_per_utxo_byte(
    protocolParameters.coinsPerUtxoWord
    )
    .fee_algo(
    this.Cardano.LinearFee.new(
        protocolParameters.minFeeA,
        protocolParameters.minFeeB
    )
    )
    .key_deposit(protocolParameters.keyDeposit)
    .pool_deposit(
    protocolParameters.poolDeposit
    )
    .max_tx_size(protocolParameters.maxTxSize)
    .max_value_size(protocolParameters.maxValSize)
    .ex_unit_prices(this.Cardano.ExUnitPrices.new(
    this.Cardano.UnitInterval.new(this.Cardano.BigNum.zero(), this.Cardano.BigNum.zero()),
    this.Cardano.UnitInterval.new(this.Cardano.BigNum.zero(), this.Cardano.BigNum.zero())
    ))
    .collateral_percentage(protocolParameters.collateralPercentage)
    .max_collateral_inputs(protocolParameters.maxCollateralInputs)
    .build();

const txBuilder = this.Cardano.TransactionBuilder.new(txBuilderConfig);

txBuilder.add_output(outputs.get(0));

if (auxiliaryData) {
    txBuilder.set_auxiliary_data(auxiliaryData);
}

txBuilder.set_ttl(
    this.Cardano.BigNum.from_str(
    (protocolParameters.slot + TX.invalid_hereafter).toString()
    )
);

utxos.forEach((utxo) => txBuilder
    .add_utxo(
    this.Cardano.SingleInputBuilder.new(utxo.input(), utxo.output()).payment_key()
    )
)
txBuilder.select_utxos(CoinSelectionStrategyCIP2.LargestFirstMultiAsset)
txBuilder.add_change_if_needed(this.Cardano.Address.from_bech32(account.paymentAddr));

const transaction = txBuilder.build().build_unchecked()

return transaction;
```


**Signing method is the same for both:**

``` ts
const account = new Account(this.Cardano);
const { paymentKey, stakeKey } = account.generateAccountKeyPair(
    password,
    accountIndex,
    encryptedRootKey
)

const paymentPubKey = paymentKey.to_public();
const stakePubKey = stakeKey.to_public();

const paymentPubKeyHash = Buffer.from(
    paymentPubKey.hash().to_bytes()
).toString('hex');
const stakePubKeyHash = Buffer.from(
    stakePubKey.hash().to_bytes()
).toString('hex');

const rawTx = this.Cardano.Transaction.from_bytes(Buffer.from(tx, 'hex'));

// const txWitnessSet = rawTx.witness_set();
const txWitnessSet = this.Cardano.TransactionWitnessSet.new();
const vKeyWitnesses = this.Cardano.Vkeywitnesses.new();
const txHash = this.Cardano.hash_transaction(rawTx.body());

keyHashes.forEach(keyHash => {
    let sigingKey;
    if (keyHash === paymentPubKeyHash) sigingKey = paymentKey;
    else if (keyHash === stakePubKeyHash) sigingKey = stakeKey;
    else if (!partialSign) throw 'Sign Error Proof Generation';
    else return;

    const vKey = this.Cardano.make_vkey_witness(txHash, sigingKey);
    vKeyWitnesses.add(vKey)
});

paymentKey.free();
stakeKey.free();

txWitnessSet.set_vkeys(vKeyWitnesses);
return txWitnessSet
```

**Comment by francisluz** [comment]
We've fixed it by using the latest version and going with only cardano-multiplatform-lib.

**Comment by yerycs** [comment]
@francisluz I am getting same error like you. Could you send me full transfer code here using cardano-multiplatform-lib?
I checked your above multiplatform code, there are several uninitialized or unimport variables, I am not sure what they are.
