### ISSUE TITLE
Coin Selection implementation for React Native bindings

### ISSUE THREAD

**Issue by khoanguyen-yang** [Emurgo/cardano-serialization-lib#509]
I am looking for the method `TransactionBuilder.add_inputs_from` of `@emurgo/cardano-serialization-lib-nodejs` but can not find it in `@emurgo/react-native-haskell-shelley` (3.1.3)

The bindings for React Native seems do not provide any method for coin selection? Does anyone have any idea?

Many thanks 🙏

**Comment by dynamicstrategies** [comment]
The React Native library lags behind this main one by at least a few months. As a workaround you can run a service in the backend that builds your transactions and sends them back to React native through an API - this way you can maintain the same code base across front end and backend.

**Comment by lisicky** [comment]
The last CSL is fully ported RN https://github.com/Emurgo/csl-mobile-bridge
