### ISSUE TITLE
Minting same asset to two different addresses breaks value conservation

### ISSUE THREAD

**Issue by miguelaeh** [Emurgo/cardano-serialization-lib#510]
Creating a single TX that mints two different amounts of the same native token to two different addresses breaks the value conservation.

If you use the `add_mint_asset_and_output_min_required_coin` twice like below:

```
    txBuilder.add_mint_asset_and_output_min_required_coin(
        mintScript,
        tokenAssetName,
        CardanoWasm.Int.new_i32(10000000),
        CardanoWasm.TransactionOutputBuilder.new().with_address(outputAddress).next(),
    );

    txBuilder.add_mint_asset_and_output_min_required_coin(
        mintScript,
        tokenAssetName,
        CardanoWasm.Int.new_i32(5000000),
        CardanoWasm.TransactionOutputBuilder.new().with_address(outputAddress).next(),
    );
```

You will obtain a `ValueNotConservedUTxO` error with the following specification:
```
...
(Value 14000000 (fromList [(PolicyID {policyID = ScriptHash "hash"},fromList [(asset_name,5000000)])]))
...
(Value 14000000 (fromList [(PolicyID {policyID = ScriptHash "hash"},fromList [(asset_name,15000000)])])
```

Note the amounts of the asset at the end of each line. It means that as total output we have `15000000` units of the asset, which is correct, but, as total input we have `5000000` units of the asset, which is not correct.

I am not too familiar with the library code itself, but looks like in this [code](https://github.com/Emurgo/cardano-serialization-lib/blob/8b0a2b2342d1494794c9232f8e4751430c7a5113/rust/src/tx_builder.rs#L1100):
```
    fn _add_mint_asset(
        &mut self,
        policy_id: &PolicyID,
        policy_script: &NativeScript,
        asset_name: &AssetName,
        amount: Int,
    ) {
        let mut asset = self
            .mint
            .as_ref()
            .map(|m| m.get(&policy_id).as_ref().cloned())
            .unwrap_or(None)
            .unwrap_or(MintAssets::new());
        asset.insert(asset_name, amount);
        self._set_mint_asset(&policy_id, policy_script, &asset);
    }
```

The insert is overriding the previous value when you specify the second one. I would say it happens in the `insert` function, but since I am not too familiar with the library maybe someone can provide a deeper vision.

**Comment by miguelaeh** [comment]
For the record, a temporal workaround for this is to execute the following after adding all the outputs with the total combined amount, so the inputs are overwritten and fixed:

```
        txBuilder.add_mint_asset(
            nativeScript,
            assetName,
           totalAmount
        );
```

**Comment by vsubhuman** [comment]
Thank you, @miguelaeh ! The fix for this is being merged at the moment
