### ISSUE TITLE
Tx serialization in offline mode raise error

### ISSUE THREAD

**Issue by hakimehmordadi** [Emurgo/cardano-serialization-lib#524]
Summary
I created transaction with @emurgo/cardano-serialization-lib-nodejs
Singed tx with this library
Send signed tx to the my local node (cardano-rossetta)

BUT

With that (signed tx which transfred to the node ) , can not create offline txId before sending transaction.

So, why signed-tx-hex (txHex) can transfer to the node but can not deseriaize and create txId?

If my code for creating txId is not correct , please guid me to create txId offline before sending tx to the network.

Steps to reproduce the bug
txHex == signed transaction hash

1- Send well formatted transaction with:
const hashResponse = await constructionSubmit(txHex);
return hashResponse.transaction_identifier.hash;
2- Try to create offline txId from txHex (which is input of constructionSubmit function) with below code:

      ```
const txHas =  'signed-tx-hash';
      const signedTransactionBytes = Buffer.from(txHas, 'hex');
      const parsed = TransactionHash.from_bytes(signedTransactionBytes);  ----> This line created above error, instead of deserialization of signed-tx-hash
     const hashBuffer = parsed && parsed.body() && Buffer.from(hash_transaction(parsed.body()).to_bytes());
```

Actual Result
Getting Error:
Deserialization failed in TransactionHash because: Invalid cbor: expected tuple 'hash length' of length 32 but got length Len(485).

From The Code :

      ```
const txHas =  'signed-tx-hash';
      const signedTransactionBytes = Buffer.from(txHas, 'hex');
      const parsed = TransactionHash.from_bytes(signedTransactionBytes);  ----> This line created above error, instead of deserialization of signed-tx-hash
     const hashBuffer = parsed && parsed.body() && Buffer.from(hash_transaction(parsed.body()).to_bytes());
```

Expected Result
I expect that, create offline txId. Actually I need to create txId offline.

Environment
Mainnet - local node using cardano-rosetta

Platform
 Linux (Ubuntu)

Runtime
 Node.js
 Docker

Runtime version
v12.18.3

**Comment by lisicky** [comment]
Hi @hakimehmordadi ! It seems that you put something wrong to the `const txHas = 'signed-tx-hash';`, it can be transaction body or transaction or something else according to length in the error that you got. Could you provide cbor ? 

Also,
> const parsed = TransactionHash.from_bytes(signedTransactionBytes); ----> This line created above error, instead of deserialization of signed-tx-hash
> const hashBuffer = parsed && parsed.body() && Buffer.from(hash_transaction(parsed.body()).to_bytes());

On the first line you are trying to create `TransactionHash` object from bytes. But in the on the second line you are using `parsed` like instance of `Transaction` because  only `Transaction` has `body` field.

**Comment by hakimehmordadi** [comment]
Hi @lisicky  Sorry for mistake, Yea actually it is:

const parsed = Transaction.from_bytes(signedTransactionBytes);

Instead of Transaction I wrote TransactionHash.
So,
This line can not deserialize the signed and sent txHash:

const parsed = Transaction.from_bytes(signedTransactionBytes);

**Correction**:

```
      const txHas =  'signed-tx-hash';
      const signedTransactionBytes = Buffer.from(txHash, 'hex');
      const parsed = Transaction.from_bytes(signedTransactionBytes); ----> This line created above error, instead of deserialization of signed-tx-hash
     const hashBuffer = parsed && parsed.body() && Buffer.from(hash_transaction(parsed.body()).to_bytes());
```

**Comment by lisicky** [comment]
@hakimehmordadi do your correction works or you get new error ? If you get error provide cbor that you are trying deserialize please.

**Comment by hakimehmordadi** [comment]
I'm getting error. 
@lisicky  with correction.

I am trying to get TXID from the bellow CBOR (It is a signed tx hash). I can create txId with /construction/hash for my cbor. But I need to use offline txId. So the code (correction) is my code for gettin txid offline by cbor. But decode runs with issue.

My Cbor is :
`827901d4383461343030383138323538323039386163636539396364373131363731303337383362383866353263663866653263366562353538383434646265633139343138363935323330636435316338303130313832383235383164363132643038663266646138383033313663616536313662366433623963616537316639633730323132356566666232663139386533346565623161303031306338653038323538316436313161613731653034373962613235366633626236336561666233626636633633366231626664333731313734316639353537613130323764316130333564623963393032316130303032386430353033316130343439653031316131303038313832353832303938623739613235613864346230343266643435353866323138343230383633336165386438636538323766623765613666333736326638323262323332383235383430393461343739336262353535353139613437333633656235663237643763626634363133643138326537653565326639336465323033366433396539373331663861306266303466653737653633633431343761373065363465366663386332383335353538623164323433656165323765323363323362313934353238303366356636a16a6f7065726174696f6e7380`

This cbor create this txId with /construction/hash ----> 7805e1dcd4e43189b8efda6b9fec98a34dfb6c8594c266bb50ec4b904e226773


If you check this tx --> https://cardanoscan.io/transaction/7805e1dcd4e43189b8efda6b9fec98a34dfb6c8594c266bb50ec4b904e226773  You will see tx sent & confirmed but I can not construct Txid from the cbor.

**Comment by hakimehmordadi** [comment]
@lisicky  Also I'm using  @emurgo/cardano-serialization-lib-nodejs: 7.0.0 for creating transaction and signing.
:

**Comment by lisicky** [comment]
@hakimehmordadi the CBOR that you provided is wrapped data, probably you put object with bytes or text field to `const txHas =  'signed-tx-hash';` and CSL can't deserialize that wrapped data. But I extracted tx cbor from your CBOR and it should be 
`84a4008182582098acce99cd71167103783b88f52cf8fe2c6eb558844dbec19418695230cd51c801018282581d612d08f2fda880316cae616b6d3b9cae71f9c702125effb2f198e34eeb1a0010c8e082581d611aa71e0479ba256f3bb63eafb3bf6c636b1bfd3711741f9557a1027d1a035db9c9021a00028d05031a0449e011a1008182582098b79a25a8d4b042fd4558f2184208633ae8d8ce827fb7ea6f3762f822b23282584094a4793bb555519a47363eb5f27d7cbf4613d182e7e5e2f93de2036d39e9731f8a0bf04fe77e63c4147a70e64e6fc8c2835558b1d243eae27e23c23b19452803f5f6`

It might help you. The latest CSL version can deserialize the CBOR that I provided. And it would be better if you update CSL version to the latest version.

**Comment by hakimehmordadi** [comment]
@lisicky  Please send me , how you extracted tx cbor from my cbor, please send me the code. Thank you

**Comment by hakimehmordadi** [comment]
I did test your cbor (the one you extract from my cbor, it works) - but I need your way, please.

**Comment by hakimehmordadi** [comment]
Kindly @lisicky  Actually our problem is we can not decode our cbors, we have old code and can not update. It is in production but because we can not extract txId from our cbors (Like the sample you saw), this give us issue and we need to fix it urgently. 
So if you share me how you could extract your tx cbor from my cbor, it would be great help to us. Thank

**Comment by lisicky** [comment]
@hakimehmordadi I checked your CBOR by cbor.nemo157.com. [link](https://cbor.nemo157.com/?type=auto&value=827901d4383461343030383138323538323039386163636539396364373131363731303337383362383866353263663866653263366562353538383434646265633139343138363935323330636435316338303130313832383235383164363132643038663266646138383033313663616536313662366433623963616537316639633730323132356566666232663139386533346565623161303031306338653038323538316436313161613731653034373962613235366633626236336561666233626636633633366231626664333731313734316639353537613130323764316130333564623963393032316130303032386430353033316130343439653031316131303038313832353832303938623739613235613864346230343266643435353866323138343230383633336165386438636538323766623765613666333736326638323262323332383235383430393461343739336262353535353139613437333633656235663237643763626634363133643138326537653565326639336465323033366433396539373331663861306266303466653737653633633431343761373065363465366663386332383335353538623164323433656165323765323363323362313934353238303366356636a16a6f7065726174696f6e7380) I recommend to check type of `txHash` in `Buffer.from(txHash, 'hex');` or source of `txHash`, It seems that you serialized object that contains tx CBOR as a object field.

**Comment by lisicky** [comment]
Hi @hakimehmordadi ! Did you extract the tx cbor ?
