### ISSUE TITLE
Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by TelmoFrancisco** [Emurgo/cardano-serialization-lib#527]
Hi, 

I'm getting this error with "@emurgo/cardano-serialization-lib-asmjs": "^11.0.5", is there someone with the same? Is some node specific version needed?

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)

**Comment by lisicky** [comment]
@TelmoFrancisco could your provide code example that emits the error ?

**Comment by lisicky** [comment]
Nothing was provided
