### ISSUE TITLE
Can't spend a UTxO with inline datum from a `PlutusV1` smart contract

### ISSUE THREAD

**Issue by abdelkrimdev** [Emurgo/cardano-serialization-lib#537]
Hi, I am using the latest CSL `11.1.0` on the preview network. I'm trying to spend a UTxO with inline datum from the always succeed smart contract. I'm getting `NonOutputSupplimentaryDatums` and `InlineDatumsNotSupported` on submit. it used to work perfectly fine on CSL `11.0.5`.

```ts
    const witness = csl.PlutusWitness.new_with_ref(
      csl.PlutusScriptSource.new(script),
      csl.DatumSource.new(datum),
      toRedeemer(redeemer),
    );

    this._txInputsBuilder.add_plutus_script_input(
      witness, utxo.input(), utxo.output().amount(),
    );
```

**Comment by lisicky** [comment]
Hi @abdelkrimdev ! Could you tell me how you did it in 11.0.5 ? Because unfortunately if you use Plutus V1 with inlined datum, the input become unspendable. See https://cips.cardano.org/cips/cip32/

**Comment by will991** [comment]
@lisicky is right. You can't mix plutus v2 features like reference inputs/ inline datums or reference scripts with Plutus v1 scripts.

**Comment by abdelkrimdev** [comment]
Yeah guys this is what I'm trying to understand as well 😅
can you please check the TX I just submitted using `11.0.5`
txHash: `223332f57461b43467271438a6831cdfe1d42b086b2cbcdee15947cfa83d66e3`
I just spend a UTxO with inline datum from a V1 smart contract... am I missing something here? 🤔

**Comment by abdelkrimdev** [comment]
Yeah guys this is what I'm trying to understand as well 😅
can you please check the TX I just submitted using 11.0.5
txHash: `223332f57461b43467271438a6831cdfe1d42b086b2cbcdee15947cfa83d66e3`
I just spend a UTxO with inline datum from a V1 smart contract... am I missing something here? 🤔

EDIT: I think I kind of understand what is going on here...
So it seems like on version `11.0.5` `TransactionOutputBuilder.new().with_plutus_data(datum)` is not doing anything
I just made a double check the UTxO I'm getting doesn't have an inline datum.
After I upgraded to `11.1.0` the `with_plutus_data` method got fixed and that's why I'm getting that error 🤔 cool!!
