### ISSUE TITLE
`calc_script_data_hash` doesn't support reference Plutus script

### ISSUE THREAD

**Issue by longngn** [Emurgo/cardano-serialization-lib#540]
https://github.com/Emurgo/cardano-serialization-lib/blob/master/rust/src/tx_builder.rs#L1658-L1675
If we use reference Plutus script, then `retained_cost_models` will be an empty map. However the node will expect it to be a map with Language v2 cost models, thus tx can't be submitted

**Comment by lisicky** [comment]
Fix will be in the next CSL release
