### ISSUE TITLE
`calc_script_data_hash` doesn't consider empty datum list

### ISSUE THREAD

**Issue by longngn** [Emurgo/cardano-serialization-lib#541]
https://github.com/Emurgo/cardano-serialization-lib/blob/master/rust/src/tx_builder.rs#L1679
A use case is when using reference input to spend a script, the tx will have 0 datums in witness so we should pass `None` to `hash_script_data` here.
We can change to like this:

```rust
            self.script_data_hash = Some(hash_script_data(
                &redeemers,
                &retained_cost_models,
                if datums.len() == 0 { None } else { Some(datums) },
            ));
```

**Comment by lisicky** [comment]
Fix will be in the next CSL release
