### ISSUE TITLE
I try to send big amount of HOSKY but is work only in smaller portions under 1B

### ISSUE THREAD

**Issue by Teodor-Iancu** [Emurgo/cardano-serialization-lib#545]
I use 4 different addresses with the same issue.
The error in frontend: _An error occurred. Please retry._
The error in console:
`yoroi.bundle.js:1 Failed to construct tx change! missing input or output for some native asset
AdaApi::createUnsignedTxForUtxos error: "missing input or output for some native asset" `

If I change the amount to send from billions to millions is work

**Comment by gitmachtl** [comment]
You're not using decimals right? so its really 1B tokens?

**Comment by lisicky** [comment]
Hi @Teodor-Iancu! Could you provide more information like used utxos and outputs in a tx ? Also there is case when "missing input or output for some native asset" means that you don't have enough ada to cover total output value + fee.

**Comment by lisicky** [comment]
Close since have no answer
