### ISSUE TITLE
Calculation of invalid rates

### ISSUE THREAD

**Issue by paulobressan** [Emurgo/cardano-serialization-lib#549]
Hi guys, how are you? I'm doing some tests with the lib using rust, so I created a simple application that generates a transaction based on the data contained in dbsync, so I just pass to the application, my staka address, asset that will be minted and the output addresses . But for some reason the transaction fee is invalid with the difference of 132 lovelace. And when you add more than one input the difference gets bigger...

When I add more than utxo in the transaction of the same stake addres but with a different payment address, do I need to change the number of witnesses?

Below is my test rust code

**Comment by paulobressan** [comment]
if there is a better option to build transactions with mint tokens and multiple inputs and outputs, please show me?

**Comment by paulobressan** [comment]
This is my test transaction

`84a50081825820def25e25fea268ef23d426a765e5b9f057c06e0a6cbe00f955d918f3449fde3500018282583900644dc73a19f9ada39d61b8802173823873554ac66e3d6ca8466e2aba510a57130a75b2a23a05c6b4d5aa52b83116a6a25e5970b8cbaa6b18821a333443f7a2581c1327bb881ba78c0560bc1632be8cc20284c36fb3eea02d08b8085cd9a44754686961676f31014754686961676f32014754686961676f33014754686961676f3401581cb563c601a79f314511e9da1aa1beee64b7f6920db7bdc068ee2441e5a445546573743101455465737432014554657374330145546573743401825839000c910b67c7df444218c11716af01551281e12ed76d20947572ccf2f25f3b1a84768160f611b1baf7601f2c7a60dce9cadca7fdf254d701731a00989680021a0002dea9075820a0268cf99664281b89e8dbbf2f6af8d1263c7d42d9a15ed4f933b682b2df752109a1581c1327bb881ba78c0560bc1632be8cc20284c36fb3eea02d08b8085cd9a24754686961676f33014754686961676f3401a200828258209c1480d8f086d31467e3db06abd261bb0998663381f9f576eefec4eae828116d5840417e669f2a5e0b36fad148fb2b59a724e6f8da0166e15908f857197665363d01182e854c4e01ae14b8dc6ceaefc1be33f90b8a4fd3eadd2b7d8dbd71acd614008258209c1480d8f086d31467e3db06abd261bb0998663381f9f576eefec4eae828116d5840417e669f2a5e0b36fad148fb2b59a724e6f8da0166e15908f857197665363d01182e854c4e01ae14b8dc6ceaefc1be33f90b8a4fd3eadd2b7d8dbd71acd6140001818201818200581cb3c591a15d6ab85084de787f294e3b581ea7e2a8806c0f7dc6b312eff5a11902d1a178383133323762623838316261373863303536306263313633326265386363323032383463333666623365656130326430386238303835636439a26754686961676f33a26473697a6514647479706563646e736754686961676f34a26473697a6514647479706563646e73`

This is the error generated
`{"error":"Bad Request","message":"\"transaction submit error ShelleyTxValidationError ShelleyBasedEraBabbage (ApplyTxError [UtxowFailure (UtxoFailure (FromAlonzoUtxoFail (FeeTooSmallUTxO (Coin 188205) (Coin 188073))))])\"","status_code":400}`

**Comment by lisicky** [comment]
Hi @paulobressan! Could you explain why you don't use `TransactionBuilder`? `TransactionBuilder` usually handles most situations with fee calculation. I strongly recommend using `TransactionBuilder` instead creating `tx` by "your hands". For a test, try to deserialize your `tx` from CBOR from your last message and call `min_fee` with deserialized `tx`, and you likely see that a new fee is differ from the fee from the `tx`. Also, fee value can increase the size of a tx, and a fee depends on a tx size.  Anyway you could check `epoch_param` and it upload there, probably you have something in  `epoch_param` too. But as I said I strongly recommend using `TransactionBuilder`.

**Comment by paulobressan** [comment]
Hi @lisicky, thanks for the answer. Do you have an example of mint using the builder? I tested it with him, but I had difficulty setting up the transaction. As I get X assets for mint, I did a for to mount the metadata and add it to mint and then I did another for to go through the utxos returned from db sync and create inputs and calculate the rate, if the rate is ok, I I stop the for and continue the flow. Could you send me an example, please?

**Comment by paulobressan** [comment]
@lisicky Thank you for your help. I was having trouble using the builder, but I was studying how it was implemented and I managed to use it, it's much simpler now lol. Thanks

**Comment by paulobressan** [comment]
@lisicky Thank you for your help. I was having trouble using the builder, but I was studying how it was implemented and I managed to use it, it's much simpler now lol. Thanks
