### ISSUE TITLE
TypeError: WebAssembly.Module(): Argument 0 must be a buffer source

### ISSUE THREAD

**Issue by bigirishlion** [Emurgo/cardano-serialization-lib#552]
I'm getting this error when I run jest tests.

```javascript
TypeError: WebAssembly.Module(): Argument 0 must be a buffer source

    > 1 | import lib from '@emurgo/cardano-serialization-lib-nodejs';
```

Any idea why this is happening?

**Comment by lisicky** [comment]
Hi @bigirishlion! Do you still have that problem ? Could you provide information about used CSL version and your environment ?

**Comment by bigirishlion** [comment]
Seems to be working now. Thanks @lisicky
