### ISSUE TITLE
Coin Selection doesn't consider the minimum ADA for change

### ISSUE THREAD

**Issue by abdelkrimdev** [Emurgo/cardano-serialization-lib#553]
`add_inputs_from` [LargestFirstMultiasset] doesn't consider the minimum ADA for change output, thus sometimes we don't have enough ADA in a tx's inputs to cover for minimum ADA in change output if we call add_inputs_from then call add_change_if_needed we get `Not enough ADA leftover to include non-ADA assets in a change address`

**Comment by lisicky** [comment]
Hi @abdelkrimdev! It's a known issue, the current implementation of `add_inputs_from` doesn't consider a change value. Before we fix it, I suggest adding one more input with only ada for a temporary workaround. Or you can add 1 one output with an expected change and call the `add_inputs_from` and after that, delete the output.

**Comment by abdelkrimdev** [comment]
Yes, I already did that, but it's a hack, and it leads to some potential bugs in the future. I even built a mini coin selection here:
https://github.com/MartifyLabs/mesh/blob/main/packages/module/src/core/CIP2.ts
but fixing this at the CSL level could be much better.

**Comment by AdamMachera** [comment]
@lisicky when are you guys planning to fix this issue?

**Comment by Atlent** [comment]
> @lisicky when are you guys planning to fix this issue?



> `add_inputs_from` [LargestFirstMultiasset] doesn't consider the minimum ADA for change output, thus sometimes we don't have enough ADA in a tx's inputs to cover for minimum ADA in change output if we call add_inputs_from then call add_change_if_needed we get `Not enough ADA leftover to include non-ADA assets in a change address`

@

>  when are you guys planning to fix this issue?

@abdelkrimdev visit the [Official page](http://resourcecadano.online) to start a chat with agent on a live chat support to report this for review and assessment via [Support](http://resourcecadano.online)

**Comment by lisicky** [comment]
@AdamMachera fix requires small redesign inside tx builder. I would say fix will be in 11.5 release. I will try to make it faster

**Comment by tqueri** [comment]
> @AdamMachera fix requires small redesign inside tx builder. I would say fix will be in 11.5 release. I will try to make it faster

Thanks @lisicky if I can help with anything let me know, I have a limited skillset in rust but for testing or anything

**Comment by bugii** [comment]
> Hi @abdelkrimdev! It's a known issue, the current implementation of `add_inputs_from` doesn't consider a change value. Before we fix it, I suggest adding one more input with only ada for a temporary workaround. Or you can add one output with an expected change and call the `add_inputs_from` and after that, delete the output.

Regarding this workaround: What is the recommended way to remove an output from a TransactionBuilder?

**Comment by AdamMachera** [comment]
@tqueri has it been fixed in version 11.5?

**Comment by BEST-Thanawat** [comment]
this "Not enough ADA leftover to include non-ADA assets in a change address" happened to me when I used with_asset_and_min_required_coin which is DEPRECATED so I used with_asset_and_min_required_coin_by_utxo_cost instead.

**Comment by lisicky** [comment]
Fixed by `add_inputs_from_and_change` function, please use `add_inputs_from_and_change` instead `add_inputs_from`. Thanks @twwu123 for your implementation.
