### ISSUE TITLE
Javascript: MintBuilder doesn't support Plutus Reference Scripts

### ISSUE THREAD

**Issue by Karakatiza666** [Emurgo/cardano-serialization-lib#567]
Reference scripts aren't supported for plutus minting. When calling `mintBuilder.set_asset(...` passing `MintWitness.new_plutus_script(PlutusScriptSource.new_ref_input_with_lang_ver(...` , `mintBuilder.get_plutus_witnesses().len()` doesn't change, and related redeemer is not added after `builder.set_mint_builder(mintBuilder)` when transaction is built.

**Comment by lisicky** [comment]
Hi @Karakatiza666 ! Thanks for reporting about issue. Fix on the way, you can track it by linked PR.
