### ISSUE TITLE
Undesired Sorting of Maps inside Inline Datums

### ISSUE THREAD

**Issue by MitchyCola** [Emurgo/cardano-serialization-lib#573]
CSL uses `BTreeMap` in it's default implementation for serializing/deserializing CBOR maps from/to `PlutusMap`. Lexicographically ordered keys are an invariant property of `BTreeMap`. Since inline datums also utilize `PlutusMap` in CSL, this has an adverse effect on smart contracts that expect datums that contain unsorted maps. `AssocMap` from `PlutusTx` respects the insertion order when appending data into a map, since it is just a wrapper around a list of tuples. With the differences in behavior between `PlutusMap` and `AssocMap`, CSL does not capture the entire scope of possible inline datums.

For example, there could be a smart contract that validates:
1. The consumption of a UTxO that has an inline datum which contains an unsorted map.
2. The creation of a new UTxO that appends data to that map in the new inline datum. 
 
By enforcing the sorting of maps inside inline datums, this would waste onchain resources for unnecessary computation, since the smart contract would also need to sort the map in order to perform validation.

**Comment by lisicky** [comment]
Hi @MitchyCola ! It's a good point :) We can change the CSL `PlutusMap` to respect insertion order. However, If you deserialize `PlutusData` it remembers the original cbor bytes, and deserialization/serialization roundtrip gives datum with the same hash. 
Could you help me understand why a smart contract needs to sort the map to perform the validation?

**Comment by lisicky** [comment]
Thanks for explanation @MitchyCola ! @twwu123 what do you thinks about that changes ? Draft PR with it - https://github.com/Emurgo/cardano-serialization-lib/pull/574
