### ISSUE TITLE
Obtaining network id from preprod Byron address failing with "Unknown network 1" error

### ISSUE THREAD

**Issue by refi93** [Emurgo/cardano-serialization-lib#583]
When I try to obtain the network id from a preprod Byron address it fails with an "Unknown network 1" error

```typescript
const csl = require("@emurgo/cardano-serialization-lib-nodejs")
const address = 'KjgoiXJS2coTnqpCLHXFtd89Hv9ttjsE6yW4msyLXFNkykUpTsyBs85r2rDDia2uKrhdpGKCJnmFXwvPSWLe75564ixZWdTxRh7TnuaDLnHx'

csl.ByronAddress.from_base58(address).to_address().network_id() // error "Unknown network 1"
```

This logic seems to be missing a branch for preprod:

https://github.com/Emurgo/cardano-serialization-lib/blob/f90602b7f0edc4b6325cb50ea748f9220f039567/rust/src/address.rs#L278

**Comment by lisicky** [comment]
Thanks @refi93 ! Fix on the way
