### ISSUE TITLE
How to calculate redeemer ex_units?

### ISSUE THREAD

**Issue by jeffhappily** [Emurgo/cardano-serialization-lib#587]
There's an `ex_units` field in `Redeemer`
https://github.com/Emurgo/cardano-serialization-lib/blob/dbcd3e3562d782def91a9f04f04377fa77a02a0a/rust/src/plutus.rs#L816-L821

I _think_ it's possible to use tool like [blockfrost](https://docs.blockfrost.io/#tag/Cardano-Utilities/paths/~1utils~1txs~1evaluate/post) to calculate the budget, but is there any other way to do it, preferably just using this library? Or is there any other way to construct the `Redeemer` without having to calculate the budget myself?

**Comment by lisicky** [comment]
@jeffhappily you can do by cardano-cli or Ogmios

**Comment by lisicky** [comment]
Unfortunately CSL doesn't support ExUnits calculation for Redeemer

**Comment by jeffhappily** [comment]
@lisicky Thanks for the pointer, what about for collateral amount, is there a way to calculate it too?

**Comment by lisicky** [comment]
@jeffhappily for collateral it would be better if you crate a new issue
