### ISSUE TITLE
FR - Adding functions to sign/verify a challenge with a VRF-Secret/Public Key

### ISSUE THREAD

**Issue by gitmachtl** [Emurgo/cardano-serialization-lib#596]
Hi,

please include functions that are using the same method as the cardano libsodium flavour to:

* Generate a VRF prove (80 bytes) signature, by signing a given challenge (bytearray) via a VRF secret key
* Verify a VRF prove by providing the challenge and the VRF public key

There are no libs out there, that are providing these functions for NODE JS & Co for our Cardano workflow.

Best regards,
 Martin

**Comment by vsubhuman** [comment]
Hi, @gitmachtl ! If I have understood your request correctly, it is about the random function used on the nodes for the slot-leader schedule derivation. We currently don't have any plans to add VRF support in the library, as we don't have any internal demand for it, and so far we did not have a chance to properly look into the details of how it would need to be implemented, or what kind of cryptography exactly they are using there in the IOHK lib. Being an open-source project we would gladly consider and accept any contributions related to that though.

**Comment by gitmachtl** [comment]
hey @vsubhuman , no its not really about the random function. its about using the vrf skey/vkey to do signing and verification in the same manner as the node is using it internally. i have also opened a thread here (https://github.com/input-output-hk/cardano-js-sdk/issues/624), please take a read. thx
