### ISSUE TITLE
WithdrawalsJSON has wrong value type

### ISSUE THREAD

**Issue by MarcelKlammer** [Emurgo/cardano-serialization-lib#620]
See:

https://github.com/Emurgo/cardano-serialization-lib/blob/506f278724111c135249c89289dd4100435a429d/rust/pkg/cardano_serialization_lib.js.flow#L11003

should some representation of:

key: RewardAddress, value: BigNum

**Comment by lisicky** [comment]
Thanks @MarcelKlammer ! We will fix it
