### ISSUE TITLE
TransactionBuilder.set_certs() throws RuntimeError: unreachable

### ISSUE THREAD

**Issue by zxpectre** [Emurgo/cardano-serialization-lib#623]
Hi! I am adding multisig support on all transaction features. On `TransactionBuilder.set_certs()` (2 certs with the same native script stake credential), when trying to combine Registration and Delegation on a single transaction it fails with `RuntimeError: unreachable`. The issue appears on the Delegation certificate, the second on the provided list. 

When I only provide the Registration certificate (first one), transaction succeeds, so I guess this certificates are properly constructed.
I have succeded before combining Registration and Delegation certificates atomically on a single transaction using KeyHash credentials

**Certificates instance in hexadecimal:**
```
8282008201581c4658726c25d0b50454c143647a2d138a1f1727fa5ee8c3a6c75f609883028201581c4658726c25d0b50454c143647a2d138a1f1727fa5ee8c3a6c75f6098581cdb1018753659a073c43ad75c1f243f97a3896a45b81a61300ea96a9f
```
**Certificates instance in json schema 1:**
```
[
  {
    "StakeRegistration": {
      "stake_credential": {
        "Script": "4658726c25d0b50454c143647a2d138a1f1727fa5ee8c3a6c75f6098"
      }
    }
  },
  {
    "StakeDelegation": {
      "stake_credential": {
        "Script": "4658726c25d0b50454c143647a2d138a1f1727fa5ee8c3a6c75f6098"
      },
      "pool_keyhash": "db1018753659a073c43ad75c1f243f97a3896a45b81a61300ea96a9f"
    }
  }
]
```

Using  "@emurgo/cardano-serialization-lib-browser": "^11.3.1",
Testing in Chrome and Pre-Prod Testnet

**Comment by lisicky** [comment]
@zxpectre Does it fail when you interact with CSL or when you try to submit the tx ?

**Comment by zxpectre** [comment]
With CSL, more specifically `set_certs()` is throwing that error. 
Searching on google I found that it can be related to Rust/Wasm:

 [Example](https://developer.mozilla.org/en-US/docs/WebAssembly/Reference/Control_flow/unreachable)

**Comment by lisicky** [comment]
@zxpectre could you share a code example to reproduce it ?

**Comment by zxpectre** [comment]
> @zxpectre could you share a code example to reproduce it ?

Sorry @lisicky , I don't have much time now to make a full working code, this minimum lines reproduce it. 
```
	let certificatesObj=CardanoWasm().Certificates.from_hex("8282008201581c4658726c25d0b50454c143647a2d138a1f1727fa5ee8c3a6c75f609883028201581c4658726c25d0b50454c143647a2d138a1f1727fa5ee8c3a6c75f6098581cdb1018753659a073c43ad75c1f243f97a3896a45b81a61300ea96a9f");
	txBuilder.set_certs(certificatesObj);
```

I've cleaned/reinstall node_modules, tryied several other ways and no luck, same error. No other parts of the code had presented weird errors like this one so far, on a working product.

Here you have a successfull Stake Registration transaction CBOR with that script credential, proving at least Registration cert is working.

[CBOR](https://cbor.nemo157.com/?type=hex&value=84a50081825820ec416d0d492ce56192819f09d42e846d8c9381d26308f296ddee6a2843f11fb90a0189825839304658726c25d0b50454c143647a2d138a1f1727fa5ee8c3a6c75f60984658726c25d0b50454c143647a2d138a1f1727fa5ee8c3a6c75f60981a001e8480825839304658726c25d0b50454c143647a2d138a1f1727fa5ee8c3a6c75f60984658726c25d0b50454c143647a2d138a1f1727fa5ee8c3a6c75f60981a002dc6c0825839304658726c25d0b50454c143647a2d138a1f1727fa5ee8c3a6c75f60984658726c25d0b50454c143647a2d138a1f1727fa5ee8c3a6c75f60981a004c4b40825839304658726c25d0b50454c143647a2d138a1f1727fa5ee8c3a6c75f60984658726c25d0b50454c143647a2d138a1f1727fa5ee8c3a6c75f60981a00895440825839304658726c25d0b50454c143647a2d138a1f1727fa5ee8c3a6c75f60984658726c25d0b50454c143647a2d138a1f1727fa5ee8c3a6c75f60981a01036640825839304658726c25d0b50454c143647a2d138a1f1727fa5ee8c3a6c75f60984658726c25d0b50454c143647a2d138a1f1727fa5ee8c3a6c75f60981a01f78a40825839304658726c25d0b50454c143647a2d138a1f1727fa5ee8c3a6c75f60984658726c25d0b50454c143647a2d138a1f1727fa5ee8c3a6c75f60981a03dfd240825839304658726c25d0b50454c143647a2d138a1f1727fa5ee8c3a6c75f60984658726c25d0b50454c143647a2d138a1f1727fa5ee8c3a6c75f60981a07b06240825839304658726c25d0b50454c143647a2d138a1f1727fa5ee8c3a6c75f60984658726c25d0b50454c143647a2d138a1f1727fa5ee8c3a6c75f60981a0c9bab66021a0021f82d048182008201581c4658726c25d0b50454c143647a2d138a1f1727fa5ee8c3a6c75f609807582094657984562ef796be389bc665346932cb03d3b457af6e06ab5b84af4b6edb66a2008382582041957b087db5933d3b119567bdd1364a569803bdb3b28fda9eff3b98e8f738ea5840918af49703e5c2e09f71e4c0a8183440cc4d2a53bbd1cc2fab585cee85b41e52547c56ddad461605b5cebecb2bfb48ff2d83a167533af2023c38cf9cc8af64028258204fb8a4f4935f80888caa182f7ff078f82f0977d0fbedbd868e8aff552d31f58b5840c4b77086bb2b2030bfe35d722b6682da704d585824f7138f629891440cbb1b3809296d40854569e90a72e32efda2b3639e803845d5d1c4c9cbe55a3a44ba4c0b8258203b3a8cb3ea764ba81f26b5d8b76b2e806905c8d9d20498a1c0fe47f84a7c174d58403379f410fe8dc1e9e3c279075850541b4a732c67c7ce8e0cd5a1385b967b1e514ab38b7681be035dffb377f290c3c308818dbb62bfc03cf36deaa56f5dfdba060181830302868200581c3ecb73dee12d39d8787c9b87e71e857c6dd487d4fe7c5173e0bb8c748200581c1d46f358ba291245db79a6b953703a131e688ab2054e6a85b742d6218200581cad0a0ecf8ae61aba9b75d337b7348a4ad5d1a92aad9d8aeaf04b28d28200581c1a4c58b1374494657edefc5b8931c3a2299935d67f44d4db87ae902d8200581c898c5d9392158c9cf5dfb6576a083db1ce7b08f785c8976e50e09a128200581cb0dabc722178ff3494e21c376b080294af8f565e66fa283e14424fb5f5a11849a46872656665727265726063626964784038373562393338303836366539643536653731313062306565333130393632633136643964346165313033663832396436326264666664326362653763363164617663312e306474797065627478)

[Block Explorer](https://preprod.cardanoscan.io/transaction/7eec1f3fb84d865ee8f5276e57e8575b0359d7a8a1e8779609ec90843447067f)


Does anyone have a codepen/jsBin ready template for CSL around?

**Comment by zxpectre** [comment]
@lisicky  I've made this repo to replicate the error under similar runtime conditions
https://github.com/zxpectre/react-csl/blob/runtimeErrorUnreachable/src/app/main.js
you can try on your own.

Maybe I'm missing something? 
![image](https://github.com/Emurgo/cardano-serialization-lib/assets/15870846/ac48970a-6296-49d6-b501-24efa25c9301)

**Comment by zxpectre** [comment]
ok @lisicky, that would be very appreciated!

Maybe you don't know it yet but CSL powers GameChanger Wallet internal tx builder since 2021 Q2, with the v2 beta we are almost exporting your entire tx builder API to became accesible to users using low code JSON based scripting and URL links. I am so close to finally offer native full multisig support but I totally depend on you guys here.

So far script driven (multisig?) minting, spending works natively on GC UI and API, probably reward withdrawal of script reward addresses work as well (about to test it once delegation can be accomplished).  

![may-evidence-gcfs-nft-creator-smart-send-for-daos](https://github.com/Emurgo/cardano-serialization-lib/assets/15870846/140ddc86-e98e-48b2-9916-fea4839c9193)

**Comment by lisicky** [comment]
Hi @zxpectre ! I'll make a new CertificatesBuilder with script script stake credentials support. It will take around 1 week, but I can't predict a new CSL version release date now. But anyway for test you will able to build lib from the source code.

**Comment by zxpectre** [comment]
Thanks @lisicky !! much appreciated! Will show you the resulting implementation as soon as I can test this out if you are interested.

You expect to introduce any breaking changes on class and method definitions here?

**Comment by lisicky** [comment]
@zxpectre I have created PR after. You can try it on your side https://github.com/Emurgo/cardano-serialization-lib/pull/628 . The PR doesn't have any breaking changes, there are new classes `CertificatesBulilder` and `WithdrawalsBuilder`

**Comment by zxpectre** [comment]
Thanks @lisicky !!! 
I've been busy, will be trying it out this week and get back with feedback.

**Comment by lisicky** [comment]
Hi @zxpectre ! Did you have a chance to check it ?

**Comment by zxpectre** [comment]
Hi @lisicky ! I have been very busy, but now it's next on my TODO list. Will come back to you for sure.

**Comment by zxpectre** [comment]
@lisicky I've build your branch for browser and test it against this code on **React-CSL** with the same certificate, and seems to work ok.

```
    const scriptHex     ="830302868200581c3ecb73dee12d39d8787c9b87e71e857c6dd487d4fe7c5173e0bb8c748200581c1d46f358ba291245db79a6b953703a131e688ab2054e6a85b742d6218200581cad0a0ecf8ae61aba9b75d337b7348a4ad5d1a92aad9d8aeaf04b28d28200581c1a4c58b1374494657edefc5b8931c3a2299935d67f44d4db87ae902d8200581c898c5d9392158c9cf5dfb6576a083db1ce7b08f785c8976e50e09a128200581cb0dabc722178ff3494e21c376b080294af8f565e66fa283e14424fb5"
    const scriptHash    ="4658726c25d0b50454c143647a2d138a1f1727fa5ee8c3a6c75f6098";
    const poolKeyHash   ="7facad662e180ce45e5c504957cd1341940c72a708728f7ecfc6e349";
    const scriptObj     =CardanoWasm.NativeScript.from_hex(scriptHex);
    let certificateObj  = CardanoWasm.Certificate.new_stake_delegation(
        CardanoWasm.StakeDelegation.new(
            CardanoWasm.StakeCredential.from_scripthash	(CardanoWasm.ScriptHash		.from_hex(scriptHash) ),
            CardanoWasm.Ed25519KeyHash.from_hex(poolKeyHash)
        ),
    );
    logger("log"    ,"certificateObj ok");
    const certBuilderObj=CardanoWasm.CertificatesBuilder.new();
    certBuilderObj.add_with_native_script(certificateObj,CardanoWasm.NativeScriptSource.new(scriptObj))
    logger("log"    ,"certBuilderObj ok");
    certBuilderObj.build();
    logger("log",`certBuilderObj.build() ok`);
    txBuilder.set_certs_builder(certBuilderObj);
    logger("log"    ,"set_certs_builder ok");
```
![image](https://github.com/Emurgo/cardano-serialization-lib/assets/15870846/6d1577a6-d9fb-43d4-8db4-4b91aa6052fd)

Also checked out the proper error message regarding the previous deprecated method.

For actually integrating this on the wallet, it will take a while for me to focus and update properly my tx builder code to use your new **CertificatesBuilder**  with native and plutus scripts. 

Actually I hope to even use those helper methods that allows one to calculate deposits and refunds, thanks for doing this! Is very handy, and much needed! Was doing everything manually before so now I need to refactor more.  

Any idea when this will be included on next release?

Big thanks from our team, will keep working on it and probably return to you with more feedback

**Comment by zxpectre** [comment]
Hi @lisicky! I've been integrating all this classes and methods into the wallet tx builder.

I'm gathering some feedback and questions, but now the most urgent issue I spotted is that
 
 `certificatesBuilder.add_with_native_script (certObj,nativeScriptSourceObj);`
 throws
`"Your certificate does not have a required script witness.Please use .add instead."`
on this certificate:
```
      "registrationCert": {
        "kind": "StakeRegistration",
        "scriptHashHex": "1fc0f80586a89f78bf9779c35af0c2f2e0e80216f77c31ca77a1a403",
        "certHex": "82008201581c1fc0f80586a89f78bf9779c35af0c2f2e0e80216f77c31ca77a1a403",
"scriptHex":"830302868200581c3ecb73dee12d39d8787c9b87e71e857c6dd487d4fe7c5173e0bb8c748200581c1d46f358ba291245db79a6b953703a131e688ab2054e6a85b742d6218200581cad0a0ecf8ae61aba9b75d337b7348a4ad5d1a92aad9d8aeaf04b28d28200581cae0a3f747a760105b79dde3b46d37b81568568a86c7f4822e29504cb8200581c385c81a738af1779d645ba36c6108053c78516308af5af71131c71f38200581c9c9f4c9f088af2503515ca446e213573770f7d152b92491b3fb4da8c"
      }
```

**Comment by lisicky** [comment]
Hi @zxpectre ! Huge thanks for checking PR! You need to provide a script witness only for `StakeDeregistration` or `StakeDelegation` certificate

**Comment by zxpectre** [comment]
@lisicky should `txBuilder.set_certs_builder(certificatesBuilderObj)` call internally not only `certificatesBuilderObj.build()` for getting cert list but also `certificatesBuilderObj.get_certificates_deposit(..)` and `certificatesBuilderObj.get_certificates_refund(..)` to use their results later when calling `txBuilder.add_change_if_needed(changeAddressObj)`?

Im asking because `.add_change_if_needed()` is not taking into account deposits nor refunds and I think one of the reasons for doing the builders may be also to assist internally in fee and change calcs right?

Also, less importantly, why `.get_certificates_refund()` returns a Value and `.get_certificates_deposit()` a BigNum and not the same type both?

**Comment by zxpectre** [comment]
@lisicky should `txBuilder.set_certs_builder(certificatesBuilderObj)` call internally not only `certificatesBuilderObj.build()` for getting cert list but also `certificatesBuilderObj.get_certificates_deposit(..)` and `certificatesBuilderObj.get_certificates_refund(..)` to use their results later when calling `txBuilder.add_change_if_needed(changeAddressObj)`?

Im asking because `.add_change_if_needed()` is not taking into account deposits nor refunds and I think one of the reasons for doing the builders may be also to assist internally in fee and change calcs right?

Also, less importantly, why `.get_certificates_refund()` returns a Value and `.get_certificates_deposit()` a BigNum and not the same type both?

**Comment by zxpectre** [comment]
Update:
I've enabled our tx fee patcher to help with this issue and here are the first results.

Script certificates support on our dapp connector: https://youtu.be/cJZlU_TmZWU

Congratulations @lisicky !
Much more is coming as this triggers lot more of work on our side

**Comment by lisicky** [comment]
@zxpectre how did you check that `.add_change_if_needed()`  is not taking into account deposits  ? 
Your app connector looks cool : )

**Comment by zxpectre** [comment]
> @zxpectre how did you check that `.add_change_if_needed()` is not taking into account deposits ? Your app connector looks cool : )

Thanks @lisicky ! You could be using it for building and testing ;)
 
I'm super delayed to make you some examples, (only active dev on team since last year) but I had to use a fee patcher to make them work, and trust me, they work with the corrected fee.

Now I'm facing [this](https://github.com/Emurgo/cardano-serialization-lib/issues/610#issuecomment-1670142466) using this branch

**Comment by lisicky** [comment]
@zxpectre I have checked on my side and everything seems correct that's why I asked about how you did check it .
