### ISSUE TITLE
__dirname is not sufficient to derive the path to WASM file

### ISSUE THREAD

**Issue by mPaella** [Emurgo/cardano-serialization-lib#624]
## Problem
The compiled lib uses `__dirname` to resolve the path to `cardano_serialization_lib_bg.wasm` file, which does not always resolve correctly. Causing `Error: ENOENT: no such file or directory, open '/project/sandbox/.next/server/app/foo/cardano_serialization_lib_bg.wasm'`

## Reproduction

https://codesandbox.io/p/sandbox/gifted-einstein-mo56ss?file=%2Fnext.config.js%3A19%2C7

- View the code sandbox
- See that both the app dir and pages dir are being used, and are calling the same function
- Browse to `/`. See that the page loads
- Browse to `/foo`. See that the page errors, due to incorrectly deriving the path to the WASM file

## Fix?

As a hack to see if i could fix it, I tried editing the compiled files for `@emurgo/cardano-serialization-lib` under `node_modules`.

OLD - Not working - line ~14053 in the compiled code
```
const path = require('path').join(__dirname, 'cardano_serialization_lib_bg.wasm');
```

NEW - Working
```
const path = require('path').join(process.cwd(), "node_modules", "@emurgo", "cardano-serialization-lib-nodejs", 'cardano_serialization_lib_bg.wasm');
```

**Comment by mPaella** [comment]
This appears to be a problem with `wasm-pack` actually, ill bring it up over there

**Comment by lisicky** [comment]
Thanks for clarification @mPaella ! It's better to create issue in Wasm-pack or next.js repo. Because it is issue of third-party tool

**Comment by lisicky** [comment]
Seems it was done by https://github.com/vercel/next.js/issues/49783
