### ISSUE TITLE
Transaction.from_bytes() works for few times before breaking.

### ISSUE THREAD

**Issue by kushalpokharel** [Emurgo/cardano-serialization-lib#629]
**Problem**
I am using **serialization-lib-asmjs** for my website where I try to parse a Transaction from bytes. It works correctly for few times after which, it throws a decoding error. 
![image](https://github.com/Emurgo/cardano-serialization-lib/assets/33277358/7a696509-7f9b-48a4-953a-289d83fed8b7)
This is the code that leads to this situation
![image](https://github.com/Emurgo/cardano-serialization-lib/assets/33277358/47cfe64c-ee02-4b01-87e2-d838e8781d35)
I am using v11.4.0

**Reproduction**
The problem can be reproduced by cloning and running this repository: https://github.com/kushalpokharel/cardano-serialization-lib-test

**Comment by lisicky** [comment]
Hi @kushalpokharel ! CSL doesn't have an automatically memory management. Your code probably reached a memory limit. Call `free();` on your deserialized transaction and on every CSL object after you finish work with them.

**Comment by kushalpokharel** [comment]
Thank you for the reply, it doesn't crash if  I call free() after logging it. 

I tried experimenting with different sizes of transactions without calling free()

- With a transaction of size 290 bytes, it runs out  of memory after 32  iterations
- With a transaction of size 7Kb, it runs out  of memory in 4 iterations. (this is pretty quick)

This means that in my app, I can't hold more than 4  transactions at a time when transactions are large.

Is there any way to increase the limit?

 When I am developing a library using Cardano-serialization-lib, How do I handle this limitation?

**Comment by lisicky** [comment]
@kushalpokharel I would suggest to use "browser" version of the CSL if it possible to you. The "browser" version leverages wasm. This package will help you to integrate wasm into Vue project https://www.npmjs.com/package/vite-plugin-wasm
