### ISSUE TITLE
Conway [12.0.0-alpha.3] - Incorrect Credential in DRep Certificates (reg, dereg, update)

### ISSUE THREAD

**Issue by Ryun1** [Emurgo/cardano-serialization-lib#637]
Using Conway Alpha Build: [@emurgo/cardano-serialization-lib-nodejs@12.0.0-alpha.3](https://www.npmjs.com/package/@emurgo/cardano-serialization-lib-nodejs/v/12.0.0-alpha.3)
Based on Draft Conway Ledger design CDDL at commit: [1beddd3d9f10d8fcb163b5e83985c4bac6b74be7](https://github.com/input-output-hk/cardano-ledger/blob/1beddd3d9f10d8fcb163b5e83985c4bac6b74be7/eras/conway/test-suite/cddl-files/conway.cddl)

**Describe the bug**
- When creating `DrepDeregistration`, `DrepRegistration`, `DrepUpdate` using `.new()`.
- OR when running `.voting_credential()` on a `DrepDeregistration`, `DrepRegistration` or `DrepUpdate`.
- The parameter `voting_credential` is expected to be of type `StakeCredential`.
- This is incorrect, these certificates do not require a stake credential, see ledger design [here](https://github.com/input-output-hk/cardano-ledger/blob/1beddd3d9f10d8fcb163b5e83985c4bac6b74be7/eras/conway/test-suite/cddl-files/conway.cddl#L312-#L314).

**Expected behaviour**
- Rather these certificates should be taking a "DrepCredential" instead, [see CDDL](https://github.com/input-output-hk/cardano-ledger/blob/1beddd3d9f10d8fcb163b5e83985c4bac6b74be7/eras/conway/test-suite/cddl-files/conway.cddl#L332), I believe this should be its own new type of Credential.
- The naming of `voting_credential` is also outdated to match an older CDDL design and the latest naming is `drep_credential`.

**Comment by lisicky** [comment]
Hi @Ryun1 ! We will name it as `Credential`. `StakeCredential` is old legacy name and the new `Credential` will a new name for `StakeCredential` because we use it as a common type.

**Comment by lisicky** [comment]
StakeCredential was renamed to Credential in 12.0.0-alpha.4
