### ISSUE TITLE
Conway [12.0.0-alpha.4] - Anchor URL limited to 64 chars

### ISSUE THREAD

**Issue by Ryun1** [Emurgo/cardano-serialization-lib#641]
Using Conway Alpha Build: [@emurgo/cardano-serialization-lib-nodejs@12.0.0-alpha.4](https://www.npmjs.com/package/@emurgo/cardano-serialization-lib-nodejs/v/12.0.0-alpha.4).

When running:
```
    const dataHash = CSL.AnchorDataHash.from_hex("9bba8233cdd086f0325daba465d568a88970d42536f9e71e92a80d5922ded885");
    const url = CSL.URL.new("https://raw.githubusercontent.com/Ryun1/gov-metadata/main/governace-action/metadata.jsonld");
    const anchor = CSL.Anchor.new(url, dataHash);
```
I get: 
` Deserialization failed in URL because: Out of range: 90 - must be in range 0 - 64`

**Describe the bug**
- The new Anchor URLs are limited to 64 characters in length.
- Attempting to add a URL to an anchor that is longer than 64 chars causes the above error.

**Expected behaviour**
- Anchor URL character limit is much higher and would thus allow longer URLs.

**Comment by lisicky** [comment]
It is limit from CDDL https://github.com/input-output-hk/cardano-ledger/blob/cf05d70ea4e8eae4ce2ad349ed17850c0c8204d1/eras/conway/test-suite/cddl-files/conway.cddl#L371

**Comment by Ryun1** [comment]
Oh that is an unfortunate restriction! -- thank you
