### ISSUE TITLE
Conway [12.0.0-alpha.4] - New certificates .kind() return in correct value.

### ISSUE THREAD

**Issue by Ryun1** [Emurgo/cardano-serialization-lib#642]
Using Conway Alpha Build: [@emurgo/cardano-serialization-lib-nodejs@12.0.0-alpha.4](https://www.npmjs.com/package/@emurgo/cardano-serialization-lib-nodejs/v/12.0.0-alpha.4).

## Describe the bug
- When using the `.kind()` call on new Conway certificates I get incorrect indexes, when comparing to the [Conway CDDL schema](https://github.com/input-output-hk/cardano-ledger/blob/master/eras/conway/test-suite/cddl-files/conway.cddl).
- Using `.kind()` on older certificates the correct value is returned.
- Perhaps I misunderstand what `.kind()` is meant to do?

## Expected behaviour
Old Certificates (working):
- `console.log(CSL.Certificate.new_stake_registration(CSL.StakeRegistration.new(randomCredential)).kind());`
   - `0` is expected and `0` is returned.
- `console.log(CSL.Certificate.new_stake_deregistration(CSL.StakeDeregistration.new(randomCredential)).kind());`
   - `1` is expected and `1` is returned. 
- `console.log(CSL.Certificate.new_stake_delegation(CSL.StakeDelegation.new(randomCredential, randomKeyHash)).kind());`
   - `2` is expected and `2` is returned.

New Certificates (not working):
 - `console.log(CSL.Certificate.new_vote_delegation(CSL.VoteDelegation.new(randomCredential, randomDRep)).kind());` 
   - `9` is expected (see [CDDL](https://github.com/input-output-hk/cardano-ledger/blob/master/eras/conway/test-suite/cddl-files/conway.cddl#L303C20-L303C21)), but `15` is returned.
- `console.log(CSL.Certificate.new_drep_registration(dRepRegCert).kind());`
  - `16` is expected (see [CDDL](https://github.com/input-output-hk/cardano-ledger/blob/master/eras/conway/test-suite/cddl-files/conway.cddl#L312C18-L312C20)), but `10` is returned.
- `console.log(CSL.Certificate.new_drep_deregistration(dRepDeRegCert).kind());`
  - `17` is expected (see [CDDL](https://github.com/input-output-hk/cardano-ledger/blob/master/eras/conway/test-suite/cddl-files/conway.cddl#L313C20-L313C22)), but `9` is returned.

(sorry I did not have time to test every new cert🙏)

**Comment by Ryun1** [comment]
Understood - thank you @lisicky 🙏

**Comment by lisicky** [comment]
If you wanna to check a cbor map key of certificate you can serialize a certificate into cbor in look into cbor by third party tool. Like https://cardananium.github.io/cquisitor/ (made by me) or https://cbor.nemo157.com
