### ISSUE TITLE
`RewardAddress`, `BaseAddress`, `EnterpriseAddress`, `PointerAddress` have no getter for network id

### ISSUE THREAD

**Issue by klntsky** [Emurgo/cardano-serialization-lib#660]
`Address` type does have it, but it is not convenient to convert every time a network id is needed.

**Comment by gitmachtl** [comment]
wasn't the `PointerAddress`supposed to 'die', because noone ever used it? should it than being removed from the lib?

**Comment by lisicky** [comment]
@gitmachtl if it will be removed from the next CDDL we can deprecate PointerAddress in the CSL API. 
But as I see it still exists in the conway CDDL https://github.com/IntersectMBO/cardano-ledger/blob/5f76eb918c16645ed98a7fbab513c2d549837ed5/eras/conway/impl/cddl-files/conway.cddl#L264-L265

**Comment by lisicky** [comment]
the lates CSL 12 should have it
