### ISSUE TITLE
Fee calculation mismatch with conway certificates

### ISSUE THREAD

**Issue by Scitz0** [Emurgo/cardano-serialization-lib#663]
Hi,

I have noticed while developing against latest CSL 12 alpha-15 that fee calculation when including both drep registration and drep delegation is 4224 lovelace short. So it seems that CSL is currently unable to determine that the drep vkey witness is needed based on provided certificates. 

I also tried it against the bleeding edge evgenii/conway_certs e835403ef1b6714cf8ddbdb407fa66478907335f commit with no change. 

@lisicky as you seem to be developing many of the changes against the conway era, is this a known issue?

**Comment by lisicky** [comment]
@Ryun1 for node 8.8 it will be CSL 12 alpha 16

**Comment by Scitz0** [comment]
Ok thanks for input :+1:
