### ISSUE TITLE
tx hash

### ISSUE THREAD

**Issue by dev-dantealighieri** [Emurgo/cardano-serialization-lib#675]
hi

how can i get transaction hash from signed transaction that is ready to submit to the chain, using this library?

thanks, dante

**Comment by lisicky** [comment]
Hey @dev-dantealighieri ! If it tx that created by CSL you can use `hash_transaction` function

**Comment by dev-dantealighieri** [comment]
hi thanks,

i created it using cardano rosetta, i have the signed transaction, how can i extract it from that!

**Comment by lisicky** [comment]
This https://github.com/Emurgo/cardano-serialization-lib/issues/604#issuecomment-1475410869 should help to calculate correct tx hash from cbor of tx that was made by third party tool

**Comment by dev-dantealighieri** [comment]
i solved it, thank you anyway!

im leaving the [solution](https://github.com/cardano-foundation/cardano-rosetta/issues/566#issuecomment-2236181963) in case anyone needs it!
