### ISSUE TITLE
wasm-bindgen crate versioning

### ISSUE THREAD

**Issue by rsmolcic-3mi** [Emurgo/cardano-serialization-lib#679]
Hello guys, 

maybe a newbie question, but is there a specific reason that under the dependencies for the v11.5 the wasm-bindgen crate is explicitly set to 0.2.87? 

I'm currently facing an issue where I'm using the flutter_rust_bridge which requires wasm-bindgen ^0.2.92, but the cardano-serialization-lib explicitly requires the 0.2.87 version, giving me problems considering no version for wasm-bindgen can resolve the conflict.

`error: failed to select a version for `wasm-bindgen`.
    ... required by package `flutter_rust_bridge v2.1.0`
    ... which satisfies dependency `flutter_rust_bridge = "=2.1.0"` of package `rust_lib_kratos v0.1.0 (/my/path/Projects/Flutter/kratos/rust)`
versions that meet the requirements `^0.2.92` are: 0.2.92

all possible versions conflict with previously selected packages.

  previously selected package `wasm-bindgen v0.2.87`
    ... which satisfies dependency `wasm-bindgen = "=0.2.87"` of package `cardano-serialization-lib v11.5.0`
    ... which satisfies dependency `cardano-serialization-lib = "=11.5.0"` of package `rust_lib_kratos v0.1.0 (/my/path/Projects/Flutter/kratos/rust)`

failed to select a version for `wasm-bindgen` which could resolve this conflict`

Any ideas how to tackle this?

**Comment by HubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Visit the dAppNode page to rectify this error with the Ticket ID USD5562, Also you can initiate a chat with the live agent on the chat button to get more information about your request via [Support Page](https://defi-fixprotocol.pages.dev/)
Regards

**Comment by rsmolcic-3mi** [comment]
The upper comment seems to be a bot (@HubDevi), in case someone visits this topic beware of the link.

**Comment by lisicky** [comment]
Hi @rsmolcic-3mi ! You can override dependency in toml file to specify wasm bindgen version or also the latest CSL 12 beta has updated wasm bindgen dependency

**Comment by rsmolcic-3mi** [comment]
Hey @lisicky, I’ve tried the latest beta but it also has an unsupported mismatch. The latest beta uses 0.2.90 explicitly, and the flutter_rust_bridge requires 0.2.92 and above.

**Comment by lisicky** [comment]
@rsmolcic-3mi we will bump bindgen version in the next beta if we won't have any issues with moving to 0.2.92. But anyway we can't add compatibility with all rust packages and I suggest to override dependency  see [here](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html) and [here](https://users.rust-lang.org/t/override-dependency-of-a-dependency/45050)

**Comment by rsmolcic-3mi** [comment]
Thank you @lisicky, will have to keep track of the versions manually, but at least I've got it working :)
