### ISSUE TITLE
`12.0.0-beta.2`- Referencing Constitutional Committee Credentials as Keys

### ISSUE THREAD

**Issue by Ryun1** [Emurgo/cardano-serialization-lib#683]
Using `"@emurgo/cardano-serialization-lib-asmjs": "^12.0.0-beta.2"`

### What?

Throughout the library, Constitutional Committee Credentials are referenced as keys

For example;
- Within `class CommitteeColdResign`
- There is the method `committee_cold_key()` which returns a credential NOT a key
- This should probably be renamed to `committee_cold_credential()`

### Why is it an issue?

A credential can be key-based OR script-based
So should be referenced as a Credential within method/variable names
Otherwise this could cause confusion

**Comment by lisicky** [comment]
Thanks @Ryun1! Fixed in the CSL 12.0.0
