### ISSUE TITLE
UpdateCommitteeAction: missing field

### ISSUE THREAD

**Issue by klntsky** [Emurgo/cardano-serialization-lib#692]
1. https://github.com/Emurgo/cardano-serialization-lib/blob/e3ef4b1c2e0af24413bf8d721aa947533581d642/rust/src/protocol_types/governance/proposals/update_committee_action.rs#L16
2. https://github.com/IntersectMBO/cardano-ledger/blob/df783ed15f70b5b5c7a40dd5d8d62386f20bfec5/eras/conway/impl/cddl-files/conway.cddl#L478

**Comment by lisicky** [comment]
Which one field ? See `Committee` struct
