### ISSUE TITLE
Question: Redeemers as map

### ISSUE THREAD

**Issue by MarcelKlammer** [Emurgo/cardano-serialization-lib#693]
What's the currently handling for Redeemer maps in CSL?
Currently the lib only has array style APIs.

```
; Flat Array support is included for backwards compatibility and will be removed in the next era.
; It is recommended for tools to adopt using a Map instead of Array going forward.
redeemers = [+ [tag : redeemer_tag, index : uint .size 4, data : plutus_data, ex_units : ex_units]]
             / {+ [tag : redeemer_tag, index : uint .size 4] => [data : plutus_data, ex_units : ex_units]}
```

**Comment by lisicky** [comment]
Also, if you have issue with signing a transaction by CSL you can these functions in `FixedTransaction` structure.
```js
.sign_and_add_vkey_signature()
.sign_and_add_icarus_bootstrap_signature()
.sign_and_add_daedalus_bootstrap_signature()
.add_vkey_witness()
.add_bootstrap_witness()
```
`FixedTransaction` preserves tx body, and all witnesses expect signatures as is, that helps to avoid incorrect tx hash and script integrity hash

**Comment by lisicky** [comment]
Since CSL 13.0.0 redeemers map will be default serialization format.
