### ISSUE TITLE
Add set_min_fee() to allow babel fees without validation zones

### ISSUE THREAD

**Issue by elRaulito** [Emurgo/cardano-serialization-lib#699]
Good morning everyone,

Lately at Fluid we have been working on Babel fees, and in order to allow them without validation zones it is possible for users to setup ADA utxos in a contract, allowing to be spent if that ADA is used for fees, also users can ask CNTs in exchange for them

We had already working it using Blaze, however Blaze is not plutus v3 compatible

![image](https://github.com/user-attachments/assets/a6930653-69e2-4e3e-b9ad-9dacbbb9bbdb)
https://github.com/butaneprotocol/blaze-cardano/releases/tag/%40blaze-cardano%2Ftx%400.3.2

What's the result and use case?
![image](https://github.com/user-attachments/assets/ff028d16-9400-4305-ba5e-559c54bf3176)

Users able to interact with txs without having to spend ADA from their wallets

How does the set_min_fee() works?

Since the evaluation process changes dinamically the fee of the tx, set_min_fee would enforce the minimum fee, after evaluation if the fee of the tx could be lower than min fee, it's forced to be the one we set in the function

What if this function is missing?
In general is hard to pass as parameter the fee to the smart contract because the fee is not something that can be controlled or forecasted

If you need any more input let me know

**Comment by elRaulito** [comment]
Exactly! @lisicky

**Comment by lisicky** [comment]
Done in the CSL 13.2.0
